### ISSUE TITLE
OmniDB Server Windows 10 Oracle error

### ISSUE THREAD

**Issue by hj0707** [OmniDB/OmniDB#1013]
Hello, When i create an oracle connection and click save data then the following error show:

Oracle is not supported. Please install it with 'pip install Spartacus[oracle]'.

 already install anaconda and execute "pip install Spartacus[oracle]" on anaconda prompt, but it not fix the error. how to install oracle instant client on OmniDB server? (windows 10 64bit, OmniDB V2.16)

**Comment by rafaelthca** [comment]
Hi @hj0707,

Thank you for reporting this. There was an error in the build process for Windows, which did not include the python package related to Oracle connections. I'm rebuilding it. Will share soon.

**Comment by rafaelthca** [comment]
Done. Please reinstall your specific version and try again. Same download link in:

https://omnidb.org/en/downloads-en

Note that you still need the oracle instant client properly installed, as the document explains:

https://omnidb.org/en/documentation-en/installation

Let us know how that goes.

**Comment by hj0707** [comment]
Hi Rafaelthca:
     Thank you for your quickly replay, 
      it works, it is a good project , hope it become perfect
