### ISSUE TITLE
Postgresql: Editing materialized views not showing indexes

### ISSUE THREAD

**Issue by marcopin** [OmniDB/OmniDB#1022]
Great work of yours. I am testing postgresql database.

I use materialized views with "indexes", but when I tried to edit a materialized view editor does not show "create unique index ..." statement related to the mv. 

Because of this, when running the resulting code (drop materialized view...; create materialized view ...;)  index disappears.

I need this unique indexes in order to refresh mv "concurrently".

**Comment by wind39** [comment]
Closing this now.
