### ISSUE TITLE
Omnidb on the cloud server is always disconnected

### ISSUE THREAD

**Issue by chacarrons** [OmniDB/OmniDB#1026]
I packaged omnidb and ran it on a cloud server, connected omnidb locally, and always disconnected.It always fails to connect 5432 and 5430.why? How should solve?thanks

**Comment by felipebiox** [comment]
Hi @chacarrons ,

OmniDB 3 beta is now live and fixes alot of issues, including connectivity.

I'm closing this issue to properly organize trackings on the new major version and this should be solved there.

Thank you for your contribution. Please, feel free to open new issues if you need.

Best regards
