### ISSUE TITLE
omnidb-server always show alert message "session object was destroyed" when open from browser

### ISSUE THREAD

**Issue by alfabaria** [OmniDB/OmniDB#1028]
i just install omnidb-server on my server running with centos 7 and everything is ok,
the problem is when i first login to  omnidb via web browser using default admin user,
the page alwasy show alert message "session object was destroyed" when i click "connection" menu or click "user menu", and i really don't know what happen, please somebody help me to fix this.
 
![image](https://user-images.githubusercontent.com/47588662/62678317-5fef3780-b9db-11e9-89c8-e40e5ea99be4.png)

**Comment by rafaelthca** [comment]
Hi @alfabaria. I'm going to need more details to troubleshoot the issue.

Are you accessing OmniDB remotely or is it a local instance? 

Can I take a look at omnidb.conf that you are using? Or are you using default settings?

Are you accessing through a reverse proxy? Apache, nginx, etc.

Which browser are you using? If chrome, please press F12 and go to the network tab. Refresh the page and show me the errors you are getting there. That message was generated in a XHR request so you may want to filter only XHR requests.

Rafael.

**Comment by alfabaria** [comment]
thankyou @rafaelthca for your respond :
yes i access OmniDB remotely but i'm not using reverse proxy (Apache, nginx etc), 
and here omnidb.conf that i used for my server :
`# OmniDB Server configuration file

[webserver]

# What address the webserver listens to, 0.0.0.0 listens to all addresses bound to the machine
# listening_address    = 127.0.0.1
listening_address    = 0.0.0.0

# Webserver port, if port is in use another random port will be selected
listening_port       = 8000

# Websocket port, if port is in use another random port will be selected
websocket_port       = 25482

# External Websocket port, use this parameter if OmniDB isn't directly visible by the client
# external_websocket_port = 25482

# Security parameters
# is_ssl = True requires ssl_certificate_file and ssl_key_file parameters
# This is highly recommended to protect information
is_ssl               = False
ssl_certificate_file = /path/to/cert_file
ssl_key_file         = /path/to/key_file

# Trusted origins, use this parameter if OmniDB is configured with SSL and is being accessed by another domain
csrf_trusted_origins = origin1,origin2,origin3

# Url path to access OmniDB, default is empty
path =

[queryserver]

# Max number of threads that can used by each advanced object search request
thread_pool_max_workers = 2

# Number of seconds between each prompt password request. Default: 30 minutes
pwd_timeout_total = 1800`

and here the error message captured from my chrome browser in a XHR request :
![image](https://user-images.githubusercontent.com/47588662/62712197-91d8bc00-ba24-11e9-91ad-2913aa4b59ab.png)

**Comment by rafaelthca** [comment]
v_error : true and v_error_id : 1 Indicates that the session object was not found, which is weird, specially because before the `get_groups` call there are other XHR requests that perform the same session check. Were those other requests successful?

I also noticed that your client wasn't able to connect to the websocket server (blue icon at the top right). Can you check the contents of the WS filter in the developers interface? (You filtered by XHR, there is another one called WS.

What you can try to do is clear your browser cookies and try logging in again. If that doesn't work please try deleting the session database file. This file is located in: `~/.omnidb/omnidb-server/db.sqlite3`. After deleting and restarting OmniDB, the file will be recreated.

Let me know.

**Comment by alfabaria** [comment]
OK thanks for you suggestion, the problem is gone, i can add new connection, and new user, 

but now i have another problem i can't execute any sql query to my database, it always return "No response from query server", i think it caused by my ws client wasn't able connect to ws server  : 

![image](https://user-images.githubusercontent.com/47588662/62761053-ca71a780-baaf-11e9-902b-00fc48bf6065.png)

**Comment by alfabaria** [comment]
ok i know, the problem is my server ( CentOS 7) blocking omnidb on default WS port (25482) so i change the port to lowest number 8081 and omnidb running perfect now. thank you.
