### ISSUE TITLE
Cannot connect to websocket with ports 25482 (external) and 25482 (internal). Trying again in 2 seconds.

### ISSUE THREAD

**Issue by palianskas** [OmniDB/OmniDB#1029]
I'm running OmniDB-server v. 2.16.0 on Chrome OS Version 77.0.3865.18 (Official Build) dev (64-bit) with MySql version 10.1.38-MariaDB-0+deb9u1 Debian 9.8.

Right after starting the omnidb-server, going to localhost and logging in into the admin account, I get the mentioned error. I've tried running the server with specified ports (both "-w" and "-e"), but the server still goes for the default port.

I'm not sure what exactly is the issue - whether it's a bug, or is my connection closed off from the port (or something entirely different).

![Screenshot 2019-08-11 at 19 50 41](https://user-images.githubusercontent.com/35391538/62837106-3997f900-bc74-11e9-93cc-a4dcbfdfc7dd.png)
![Screenshot 2019-08-11 at 19 51 34](https://user-images.githubusercontent.com/35391538/62837108-3ef54380-bc74-11e9-927e-451e9b732eba.png)

**Comment by pgaro** [comment]
This just means that the web page can't reach the webserver to retrieve more information. I can't debug from here why that might be the case.

**Comment by Sharperr** [comment]
@pgaro can I provide any other info to diagnose the issue?

**Comment by pgaro** [comment]
I'm not sure. Did you try setting websocket_port in the onmidb.conf directly?

**Comment by dfithian** [comment]
I get this issue as well. Workaround is to hard refresh the page. If that doesn't work, log out and log back in.

**Comment by dfithian** [comment]
My load balancer is closing the connection after 1 min. What I'd like to do is increase the timeout - is there a websocket heartbeat interval? If I can set the timeout to be larger than the heartbeat interval the connection should never close.

**Comment by dfithian** [comment]
I found this: https://github.com/OmniDB/OmniDB/blob/master/OmniDB/OmniDB_app/static/OmniDB_app/js/QueryClient.js#L86-L111

By inspection it seems to be about every 2 minutes, and this code backs that up as I can see from the websocket request code of 12 in my Chrome console every 2 min. So I think this can be worked around by setting a load balancer timeout of >2 min.

**Comment by felipebiox** [comment]
Hi all,

OmniDB 3 beta is now live.

We are re-organizing the issues to work more effectively and have a big picture of things done and what's on the way.

There are several well-known issues related to websocket in OmniDB 2.x, as well as confusion and complexity in setting up environments.

We decided to adopt a different approach and re-designed our connections using long polling instead, and now websocket is no longer being used.

I will close this issue now but feel free to re-open or create issues as you need.

Thanks for your contributions.

Best regards
