### ISSUE TITLE
not all GRANT shown in DLL

### ISSUE THREAD

**Issue by marcofavale** [OmniDB/OmniDB#1034]
into tab DLL of the table all grant are not listed.

If I have a grant for a specfic column of the table, they are visible in psql but not into the DLL tab.

e.g. 

GRANT INSERT(columnA), UPDATE(columnA) ON TABLE mytable TO myuser;

**Comment by barthisrael** [comment]
Hi @marcofavale , thanks for reporting. Issue fixed for next release.

**Comment by wind39** [comment]
Closing this now.
