### ISSUE TITLE
Can't Query Any Tables in Postgres 9.1.4 Database

### ISSUE THREAD

**Issue by snowfi6916** [OmniDB/OmniDB#1040]
I am getting this error every time I right click a table in my Postgres 9.1.4 database and try to run a SELECT query.

![image](https://user-images.githubusercontent.com/30598385/64048613-32ac2a00-cb40-11e9-8d47-7f8704b028a9.png)

This is only happening in my Postgres 9.1.4 database.  I have other Postgres databases which are running a newer version that work fine when I right click a table and run a query.

Please help.

**Comment by snowfi6916** [comment]
I copied one of the databases in the 9.1.4 database into a newer version of Postgres that is running on a different port.  I am not getting the error there.  I am also not getting any errors in pgAdmin when I run a query on the 9.1.4 database.

So it's something to do with OmniDB and Postgres 9.1.4 not getting along.

**Comment by pgaro** [comment]
Ugh! Please consider updating! 9.1 is EOL for over 3 years now.

A lot of the ACL stuff changed between 9.0 (where a lot was new) and 9.4.

I can't point my finger to the specific version without looking it up, but it might very well include the acldefault function we have today (I obviously don't have a 9.1 running anymore, so I can't check).

All the best
pgaro

**Comment by snowfi6916** [comment]
Thanks for responding.  Unfortunately, it's not up to me when we will update our Postgres on that port, as we have multiple clients using that version.  However, I will pass along that we should upgrade everyone to a newer Postgres version.  Thanks for your help.
