### ISSUE TITLE
Connections feature request: add Name

### ISSUE THREAD

**Issue by mariusa** [OmniDB/OmniDB#1055]
Please add a Name property for each connection. If specified, this name should be shown in tabs and other places asking to connect to. People can fill in names such as 'project-dev', 'project-staging' etc.

Now it seems the database name is used, and that is a random string when using cloud providers such as Heroku.

**Comment by felipebiox** [comment]
Hi @mariusa 

I just replied to you in a different issue talking about Omnidb 3 beta being now live.

Outer connections now have names related to optional Titles that you can assign to them.

We are also doing another round of improving it more based on new feedback that we already received.

Bear in mind that this menu has different visuals depending on the size of the screen.

I will now close this issue, thank you for your contributions.

Best regards
