### ISSUE TITLE
Make snippets quicker accessible

### ISSUE THREAD

**Issue by mariusa** [OmniDB/OmniDB#1058]
When working within a db connection, it's useful to quickly select & run a snippet

Now, one has to switch to Snippets, right click desired snippet, select Run, select connection, then press Alt+Q. Phew.

Please make it faster by having a snippet icon in Query tab row of icons, after "Explain Analyze".
Clicking on it should show a dropdown with snippet names (similar to CSV/XLS dropdown).
Clicking on a snippet name would replace run that query (replace current query contents AND run the query).
This means only 2 clicks to see results.

In case some snippets require a parameter to be set before running (eg snippet is ```SELECT * FROM users WHERE id=?```), skip auto-run in this case. 

Thanks!

**Comment by felipebiox** [comment]
Hi @mariusa ,

Thank you for the great suggestion.
The new UI is bringing the snippet interface to a global panel easily accessible from any tab.

It's coming with v3, currently a WIP.

Best regards

**Comment by felipebiox** [comment]
Hi @mariusa ,

OmniDB 3 beta is live.

The global snippets panel is now available.
Also the editors have context menus with actions integrated to the snippets, allowing you to quick-save or use, navigating the snippets structure straight from the menu.

Here is a preview.

![snippets_info](https://user-images.githubusercontent.com/11302800/97460103-3b061d80-191b-11eb-8ab4-6e7d9878f2e3.png)

I'm now closing this ticket.

Best regards
