### ISSUE TITLE
Missing comment of tables, views and functions 

### ISSUE THREAD

**Issue by kondrat-net** [OmniDB/OmniDB#1065]
DDL is missing comments of table, views and functions. Will it be possible to preview and edit comments in next versions?

The application is great and I would like to use it in the future. Greetings.

**Comment by barthisrael** [comment]
Hi @kondrat-net , thanks for reporting that. We're currently working on this issue. We intend to add support to edit comments in all supported objects, as well shown it in objects DDL.

**Comment by wind39** [comment]
Closing this now.
