### ISSUE TITLE
Omni DB inaccessible due to high cpu usage used by Omni DB process

### ISSUE THREAD

**Issue by dewapurag** [OmniDB/OmniDB#1070]
Omni DB Web URL sometimes fails to load with connection timeout errors. Most of the times this is faced when omni db process is having more than 100% cpu usage.

**Comment by dewapurag** [comment]
@wind39 Could you advice on above issue.

**Comment by dewapurag** [comment]
@wind39 @rafaelthca  Currently we are using v2.16 and we get a lot of compalins from users that OmniDB isn't loading. Appreciate your advice on this.

**Comment by rafaelthca** [comment]
hi @dewapurag,

How many users access OmniDB concurrently? Just a rough estimation.

Is CPU usage 100% all the time? Do you have to restart OmniDB or does it go back to normal by itself?

How often do you experience that? This is a critical issue and we will work together to solve it.

Rafael.

**Comment by rafaelthca** [comment]
Another question, does one of your users use the SSH terminal feature?

**Comment by rafaelthca** [comment]
I just pushed a fix to the issue related to SSH terminal. When the SSH tunnel to the remote machine gets disconnected, there is a corner case where the thread waiting for console responses remains stuck in an infinite loop, resulting in 100% CPU.

We are going release 2.17 tomorrow with this fix.

I would still appreciate if you can answer my previous questions so we can investigate if your issue is happening due to something else.

**Comment by dewapurag** [comment]
Hi @rafaelthca 

Currently around 25 users access concurrently.
Not everytime but sometimes this cpu hit occurs and it resolves automatically too.
If it doesn't resolve automatically  have to restart OmniDB to get back to normal.
Atleast once per day this occur.

**Comment by rafaelthca** [comment]
Ok.

Is there anything useful in the logs at around the time you are experiencing high CPU usage? Please share it with us after masking sensitive data.

Please test 2.17 after tomorrow's release and let us know if issue is fixed. If not, we'll have to do a more in depth analysis.

What OS are you on?

**Comment by dewapurag** [comment]
@rafaelthca 
We don't use SSH Tunnel, currently we use only below values to connect;
Technology : mysql
Server -
Port -
Database -
User -
SSH Port -

Currenly syslog looks fine, is there any other log you want me to share

**Comment by dewapurag** [comment]
Please find below OS version
`root@xxx:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
`

**Comment by wind39** [comment]
Hi @dewapurag ,

Today we released OmniDB 2.17.0 with a bunch of fixes that might be related to your problem.

Please try upgrading OmniDB to 2.17.0 and see if the issue persists.

Best regards,

William

**Comment by ChrisLee1023** [comment]
Hi @ rafaelthca,
I also had a problem with webSocket disconnecting when the CPU was 100% and needed to restart the service to reconnect, but since I was new to Python, I haven't found a solution yet
The omnIDB version is 2.17.0
Do you have any Suggestions?

**Comment by ChrisLee1023** [comment]
@rafaelthca
I also had a problem with webSocket disconnecting when the CPU was 100% and needed to restart the service to reconnect, but since I was new to Python, I haven't found a solution yet
The omnIDB version is 2.17.0
Do you have any Suggestions?

**Comment by felipebiox** [comment]
Hi all,

OmniDB 3 beta is now live, coming with several improvements.

For example, websocket was replaced with a different strategy using long polling, which fixed quite a few connectivity and performance issues.

I'm closing this issue to organize the roadmap, but feel free to re-open issues if you need.

Thanks for your contribution.

Best regards
