### ISSUE TITLE
Hotkey for run query/refresh

### ISSUE THREAD

**Issue by kobaz** [OmniDB/OmniDB#1092]
Most other interfaces use the F5 key to reload/refresh or execute the current query in the sql window.

It would be very very useful to be able to hit a hotkey to refresh rather than clicking the play button every time to execute a query in a query window.

**Comment by wind39** [comment]
Hi @kobaz ,

Please check the Shortcuts in your user Settings. Default shortcut to run the current query on the query window is Ctrl-q on Linux/Windows or Meta-q on Mac. F5 is browser default to refresh the entire webpage.

Best regards,

William

**Comment by hginzel** [comment]
Ctrl+Enter is another often used combination.
