### ISSUE TITLE
Depend on external JS

### ISSUE THREAD

**Issue by 1725785880** [OmniDB/OmniDB#1096]
Please remove the external dependent JS to ensure I can use it in the internal network.Thank you!

https://cdn.optitc.com/serve?url=default&z0=WyIiLDE1MzYsODY0LDE1MzYsNzYzLCIiLDI0LDAsMCwicGRmLGNvb2tpZSIsIiIsImh0dHA6Ly8xOTIuMTY4LjQzLjEwOjgwMDAvd29ya3NwYWNlLyIsOCwiVVRGLTgiLCJlbi1VUyIsMTU3Nzk1OTMzMDI1NSwiTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzcxLjAuMzU3OC45OCBTYWZhcmkvNTM3LjM2IiwiaHR0cDovLzE5Mi4xNjguNDMuMTA6ODAwMC8iLCJPbW5pREIiLCJvbW5pZGJfY3NyZnRva2VuPXpHZjlOSm85aWFWZlBRM0VPTXBqU1VlY0VNeXBMem5tUmxaTHh4QUw1QXlKRVZuaFdnVllJckdaVkF1NldsVjMiXQ&s=500%2C400%2C50%2C50

https://cdn.optitc.com/jquery.min.js

**Comment by rafaelthca** [comment]
Hi,

Can you provide a screenshot showing the browser attempting to fetch that JS? That shouldn't happen as all required JS files are bundled with OmniDB.
