### ISSUE TITLE
DDL improvements

### ISSUE THREAD

**Issue by thjack** [OmniDB/OmniDB#1106]
The view should show what roles a user has and for a role that members have

when a trigger is added that depends on a field it does not show the field on the trigger

Example:
If we add this trigger:
CREATE TRIGGER area
   BEFORE INSERT OR UPDATE OF the_geom
   ON public.cat_manzana
   FOR EACH ROW
   EXECUTE PROCEDURE st_bi_area ()

Then when the trigger DDL is consulted it shows

CREATE TRIGGER area
   BEFORE INSERT OR UPDATE
   ON public.cat_manzana
   FOR EACH ROW
   EXECUTE PROCEDURE st_bi_area ()

In other words, it does not show "OF the_geom"

ESPAÑOL

La vista deberia mostrar que roles tiene un usuario y para un rol que miembros tiene

cuando se agrega un trigger que depende un campo no muestra el campo en el trigger

Ejemplo:
Si agregamos este trigger:
CREATE TRIGGER area
  BEFORE INSERT OR UPDATE OF the_geom
  ON public.cat_manzana
  FOR EACH ROW
  EXECUTE PROCEDURE st_bi_area()

Despues cuando se consulta el DDL del trigger muestra

CREATE TRIGGER area
  BEFORE INSERT OR UPDATE
  ON public.cat_manzana
  FOR EACH ROW
  EXECUTE PROCEDURE st_bi_area()

Es decir no muestra "OF the_geom"

**Comment by alvherre** [comment]
Thanks for reporting.  Note that the `OF the_geom` clause is for indicating columns (not users/roles). So the intention of this command is that the function st_bi_area will be executed if the update affects column the_geom, and will not be executed if it only affects other columns.   I agree that OmniDB should show the `OF` clause.

**Comment by wind39** [comment]
Hi @thjack ,

Thanks for reporting, we are going to fix both issues.

Best regards,

William

**Comment by kobaz** [comment]
Also.

Clicking on a column does not show the column DDL.

![image](https://user-images.githubusercontent.com/1695852/77858554-4dc44280-71d2-11ea-832d-09565a951e0c.png)

**Comment by wind39** [comment]
Closing this now.
