### ISSUE TITLE
how to limit functionalities on the UI - how to hide them 

### ISSUE THREAD

**Issue by Msojdehei** [OmniDB/OmniDB#1109]
is there a way to hide some of the functionalities on the UI from users, hide them altogether?  to customize the UI?

**Comment by felipebiox** [comment]
Hi @Msojdehei ,

At this moment the UI is fixed as provided, allowing only resizing in some cases.

On OmniDB v3 we are bringing more flexibility to the user on controlling the visibility state of quite a few UI elements, allowing him to show/hide them as well as resizing them.

This is a per-user approach based on interaction, and not a global configuration that hides them for all users.

**Comment by felipebiox** [comment]
Hi,

OmniDB 3 beta is now live.

Some UI elements are now togglable, allowing you to hide them, here's a preview.

![workspace_info](https://user-images.githubusercontent.com/11302800/97468477-16627380-1924-11eb-8d9e-a0c5b77e1c08.png)

In the case of the Properties/DDL panel, visibility also controls the activity of database tree actions that request this sort of info.

Please, feel free to open new issues if you need.

I will now close this issue, thanks for your contribution.

Best regards
