### ISSUE TITLE
Red "offline" on the upper right corner 

### ISSUE THREAD

**Issue by square-root3** [OmniDB/OmniDB#1117]
I installed onmidb2.6 on Windows 7 and accessed it by chrome browser on some other computers. Some visits are normal. Some of them have some problems: I can log in by browser, but after logging in, the a red "offline" icon appears on the upper right corner, and it's no response after clicking “Connections” on the upper left corner. Plz help me. 
![B6639C5F-7654-47DA-8284-64B3AD2917EC](https://user-images.githubusercontent.com/9866233/77742486-7bce4900-7051-11ea-845b-670d0ee4746e.jpeg)

**Comment by JohnnySJKim** [comment]
Me too. I encountered same problem. Could anybody help?

**Comment by felipebiox** [comment]
Hi @square-root3 and @JohnnySJKim 

I've seen other issues like this that were related to connectivity and they were based on websocket issues and/or bugs.

We are no longer using websocket now.

OmniDB 3 beta is now live and we designed a new strategy using long polling.

I will now close this issue.

Please, feel free to open new issues if you need and thank you for the contribution.

Best regards.
