### ISSUE TITLE
Users who cannot create their own connections

### ISSUE THREAD

**Issue by javc1974** [OmniDB/OmniDB#1122]
Hello! Congratulations for your software. It's really great.

I wish there was a possibility that users could not define their own connections. It would be very useful to use omniDB against production databases. It would be very reassuring for DBAs like me.

Thanks

**Comment by javc1974** [comment]
Neither create nor modify. Users with read-only connections. That they could not in any way define a connection against a production database.

**Comment by jdelramirez** [comment]
It would be a great idea, could you implement it ? very thanks
