### ISSUE TITLE
SQL: using Where throws an error

### ISSUE THREAD

**Issue by lizat** [OmniDB/OmniDB#1124]
I have a very simple SQL statement that throws this error:

syntax error at or near "WHERE"
LINE 6: WHERE t.name like '%sal%'

This must be really simple but I cannot see what on earth is wrong. the complete statement is:
SELECT t.id , t.name
FROM public.interests t
ORDER BY t.id
WHERE t.name like '%sal%'

I am using Omnidb 2.17

Thank you

**Comment by wind39** [comment]
Hi @lizat ,

Thanks for reaching out. The issue is with the order of the statements, `WHERE` is supposed to come before `ORDER BY`. So this would work:

```
SELECT t.id , t.name
FROM public.interests t
WHERE t.name like '%sal%'
ORDER BY t.id
```

Best regards,

William
