### ISSUE TITLE
OmniDB suddenly reporting "Cannot connect to websocket server..."

### ISSUE THREAD

**Issue by ccurvey** [OmniDB/OmniDB#1126]
not sure what changed, my guess is that it's something in one of the patches I just applied to my OS (and of course I have patched both my client and server today)

* omnidb 2.17 running in server mode at AWS
* local browser is Firefox 75.0 on Ubuntu 19.10 (fully patched)

Today I'm getting messages "Cannot connect to websocket server with ports 25482 (external) and 25482 (internal).  Trying again in two seconds...

* The website does load.
* I'm able to "telnet my-host-at-aws 25482" 
* I tried changing the websocket port to 8003, and I'm able to telnet to that as well

Possibly Interesting Facts:

There are some messages in syslog on the server that seem to pop up when I reload the page:
> Apr 29 15:35:59 hostname-obfuscated bash[10825]: WARNING:tornado.general:SSL Error on 19 ('ip.has.been.obfuscated', 53450): [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:833)
> Apr 29 15:36:08 hostname-obfuscated bash[10825]: WARNING:tornado.general:error on read: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:2273)

And most interestingly....If I try to use Chrome 81.0.4044.129, it works just fine.  So I guess that's my workaround for now.

**Comment by ccurvey** [comment]
I think I found the root cause (and a workaround) for this.

The root cause is that my certificate is self-signed.

The workaround is

1. In FF, point your browser to the websocket port (e.g. https://example.com:25482)
2. This will bring up FF's normal "Danger Ahead!" page due to the self-signed cert.
3. Keep clicking the buttons to let you through to the site, ignoring the security warnings.

This workaround also seems to solve #1134

**Comment by felipebiox** [comment]
Hi @ccurvey ,

Glad you are good.

I'm now closing this issue, feel free to open new ones if you need.

Best regards
