### ISSUE TITLE
Why chrome have different warning with firefox do?

### ISSUE THREAD

**Issue by yyyyyj45** [OmniDB/OmniDB#1136]
Using the same omnidb.conf ,open program via both chrome and firefox,google will alert the warning 'cannot connect to websocket server with ports external and internal.Trying again in 2 seconds'.However,there wont be any warning via firefox.

Is this service not compatiable to chrome or my chrome version is too old?
ps. chrome version: 79.0.3945.88

**Comment by barthisrael** [comment]
Hi @yyyyyj45 ,

Thanks for reaching us.

OmniDB is expected to work both in Chrome and Firefox. We have been facing a few issues related to websockets lately in OmniDB 2.x.

OmniDB 3.0 will be released soon. In such version we have abandoned the websockets technology and are now using long polling. By doing so, we expect to solve a lot of issues related to websockets.

Once it's released, we invite you to test it and let us know your thoughts about it.

Regards.

**Comment by felipebiox** [comment]
Hi @yyyyyj45 ,

We've replaced websocket with a new strategy using long polling. This shouldn't happen anymore.

Please, feel free to open new issues.

I'm now closing this issue.

Best regards
