### ISSUE TITLE
How can an admin user  see command history of all the other users 

### ISSUE THREAD

**Issue by maheshvasu** [OmniDB/OmniDB#1143]
Is there any option for an  admin ( super user ) to see the history of commands executed by "other users "  through the web client OR through any back end log files in the installation directory ? I want to track all the command executed by ALL the users

**Comment by barthisrael** [comment]
Hi @maheshvasu ,

Thanks for reaching us.

Currently there is no way to achieve what you want using the web interface. Although you can inspect that using **omnidb.db**, which is located in the path **~/.omnidb**, i. e., in **.omnidb** folder under home directory of the user that is running OmniDB. If you have access to such file, you'll be able to inspect it. Such file is a SQLite database. You can query the commands history by querying something like:

```sql
SELECT cl.*
FROM command_list cl
INNER JOIN users u
        ON cl.user_id = u.user_id
WHERE user_name = 'XXX';
```

**Comment by wind39** [comment]
Closing this now.
