### ISSUE TITLE
 mysql password 

### ISSUE THREAD

**Issue by Mr-Senven** [OmniDB/OmniDB#1146]
I do not want to enter the mysql password everytime when I want to connect my mysql sever. how to save the password ?

**Comment by barthisrael** [comment]
Hi @Mr-Senven ,

OmniDB 3.0 will be release soon, and it'll have the option to store connections passwords in OmniDB database, so you'll not be required to type it from time to time.

Regards.

**Comment by wind39** [comment]
Closing this now.
