### ISSUE TITLE
Heartbeat to keep websocket connection open

### ISSUE THREAD

**Issue by MaximKraev** [OmniDB/OmniDB#1148]
I have OmniDB running behind a proxy, and WebSocket connection is interrupted by inactivity timeout on proxy, is there a way to have Heartbeat (ping/pong messages) between client and server to keep the connection alive?

thank you.

**Comment by barthisrael** [comment]
Hi @MaximKraev ,

Thanks for reaching us.

We have redesigned backend and frontend of OmniDB for 3.0 version, which will be released soon. One of the main changes we have done was abandoning websocket connections. We were not using the most relevant features of websockets, so we converted it to long polling, fixing a lot of issues that were opened in GitHub related to websockets, and at the same time avoiding new ones. We expect long polling mechanism to to its job well.

Once OmniDB 3.0 is released, we invite you to test it and let us know your thoughts.

Regards.

**Comment by felipebiox** [comment]
Hi all,

Just refreshing this with the info that OmniDB 3 beta is now live.

Websocket has been dropped in favour of a different strategy using long polling, with much simpler configurations and a few connectivity issues fixed.

I'm closing this ticket but feel free to open new issues as needed.

Thank you for contributing.

Best regards
