### ISSUE TITLE
How to access user details related to OmniDB from backend when doing a migration

### ISSUE THREAD

**Issue by gimhana888** [OmniDB/OmniDB#1150]
I am using OmniDB version 2.16 , I need to migrate the current OmniDB to another server. 
The issues I have are;

How to query the user details from backend (what is the DB that should be checked to get user details?)
How to do the migration? (I copied the OmniDB-master directory to the new server and installed again on the new server but I couldn't find any way to get the old user details to the new server)

**Comment by gimhana888** [comment]
Any update on this

**Comment by barthisrael** [comment]
Hi @gimhana888 ,

Thanks for reaching us and sorry about the delay :(

All info related to OmniDB is stored in the following path: **~/.omnidb**. So, if you're running OmniDB as root, for example, you'll be able to find the OmniDB database in the path **/root/.omnidb/omnidb.db**.

As you want to migrate to another server, it would require installing the same OmniDB version in the other server, and then copy the **omnidb.db** file from old server and paste in the new one, under the *.omnidb* folder of the user that will run OmniDB.

Please keep in mind that the **.omnidb** folder is created under home directory of the user running OmniDB. So, it would require that you run OmniDB at least one time in the new server for it to create such folder. After that you can replace your **omnidb.db** file by the one retrieved from old server.

Hope that match your requirements.

Regards.

**Comment by felipebiox** [comment]
I'm now closing this issue.

Please, feel free to re-open if you have further questions or contributions.
