### ISSUE TITLE
Login page doesn't let you log in with a newly created user (with omnidb-config-server) if you run omnidb-server as root.

### ISSUE THREAD

**Issue by elegantcha0s** [OmniDB/OmniDB#1151]
If you run omnidb-server as root and later you create a user with 'omnidb-config-server -u user password', It doesn't let you login.

**Comment by wind39** [comment]
Hi @elegantcha0s ,

`omnidb-config-server` should be executed as the same user as `omnidb-server`, otherwise it will use/create the `~/.omnidb/` directory under the user you executed `omnidb-config-server`.

Regards,

William

**Comment by elegantcha0s** [comment]
@wind39
Thanks for your reply,
There Is a Docker Image here: https://hub.docker.com/r/taivokasper/omnidb/
However, Id doesn't seem to have support for command execution or omnidb-config-server.

Thanks for your help.
