### ISSUE TITLE
completely reset sqlite database?

### ISSUE THREAD

**Issue by ccurvey** [OmniDB/OmniDB#1153]
I forgot my password(s), and now I'm completely locked out of my omnidb server.  

I tried to reset the entire database with 

```
$ sudo ./omnidb-config-server --r
*** ATENTION *** ALL USERS DATA WILL BE LOST
Would you like to continue? (y/n) y
Cleaning users...
Done.
Cleaning sessions...
Done.
Vacuuming OmniDB database...
Done.
Vacuuming Sessions database...
Done.
Cleaning temp folder...
Done.
Creating superuser...
Superuser created.
```

but admin/admin does not let me login. ("Invalid username or password")

I tried

```
$ sudo ./omnidb-config-server -s ccurvey bigsecret`
```

and ccurvey/bigsecret also gives me "Invalid username or password"

I tried deleting and recreating ~/.omnidb/omnidb-server/omnidb.db.  (I can use sqlite3 to look in there and I can see my admin and ccurvey users.)

I tried completely removing omnidb-server (via `dpkg -P omnidb-server`) and then reinstalling (`dpkg -i ...`), and I still can't connect.

How do I get my server working again?

**Comment by luss** [comment]
OmniDB is likely so information in a configuration directory that doesn't
get deleted when you remove it.  Perhaps it is storing some info in
~/.omnidb directory?

**Comment by ccurvey** [comment]
Ah.  It seems that the sqlite database that gets used is stored in /root/.omnidb/omnidb-server

So maybe a few suggestions for the future

1. Let's not run the service as root.  That makes the security kittens in my brain scream in pain.
2. It would be nice if we could specify the location of the sqlite databases in the omnidb.conf file.
3  And it would also be nice if the server would say "I'm using /path/to/omnidb.db" on startup.

**Comment by wind39** [comment]
Closing this now.
