### ISSUE TITLE
OmniDB generate errors in pgsql logs

### ISSUE THREAD

**Issue by FGU1** [OmniDB/OmniDB#1157]
OmniDB 2.16.0
PostgreSQL 11.7 on Debian 10
When OmniDB is started, we can see lots of lines in postgresql logs : 
"du: ... 'pg_xlog': No such file or directory" (translated)
I guess this is due to pgsql changing pg_xlog directory name to pg_wal.

Thanks for your work on OmniDB, very usefull for me !

**Comment by barthisrael** [comment]
Hi @FGU1 ,

Thanks for reporting this issue. This was already fixed for next release, 3.0, which will be available soon.

Regards.

**Comment by wind39** [comment]
Closing this now.
