### ISSUE TITLE
Proposing a new feature - saving a query

### ISSUE THREAD

**Issue by ahmed-r-hashim** [OmniDB/OmniDB#1159]
Would it be possible to save the query as snippet by right-click and save? This would be a handy usability feature, especially for who dislikes using copy/paste the query content and back and forth between the tabs just to save the query into snippet tree, like me.
By the way, I love OmniDB and it has a big potentials.

**Comment by barthisrael** [comment]
Hi @ahmed-r-hashim ,

Thanks for your interest in OmniDB and for proposing new features. This one was implemented and will be available in 3.0 version, which will be released soon.

Regards.
