### ISSUE TITLE
question: why so many open issues?

### ISSUE THREAD

**Issue by MichaelDBA** [OmniDB/OmniDB#1165]
It is hard to get a birds eye view of open issues and which of those would concern me before using this tool.  What is the rationale for keeping issues open for months?

**Comment by felipebiox** [comment]
Hi @MichaelDBA ,

That's a great point. The short answer is that we are releasing a new major version of OmniDB [#1067 ](https://github.com/OmniDB/OmniDB/issues/1067)

Major version 2 is frozen, thus, many issues were accumulated;

This is a refactor of the tool with dependency upgrades, architectural changes, new UI, and of course, we are covering several of those issues on this release.

Best Regards

**Comment by MichaelDBA** [comment]
Thanks for the info.
