### ISSUE TITLE
The update is deleting data

### ISSUE THREAD

**Issue by Leonardofreua** [OmniDB/OmniDB#1166]
When upgrading to the new version (3.0), I lost all my **connections** and **snippets**.

I performed the updated via **.deb** file.

**Comment by wind39** [comment]
Hi @Leonardofreua ,

Are you using OmniDB app or server? What version were you running before the upgrade?

Also, if it's server, do you run it as `root` or a different operating system user?

Regards,

William

**Comment by Leonardofreua** [comment]
I'm using the OmniDB app and the previous version was 2.16.

**Comment by wind39** [comment]
Hi @Leonardofreua ,

Two days ago we released 3.0.1b with an improvement to the automatic migration process. If you install the newest beta package now, it should migrate your users, connections, snippets and monitoring units from 2.17.

We are preparing release of 3.0.2b, it should be out later today.

Best regards,

William

**Comment by Leonardofreua** [comment]
Ok, I will install this version. Thanks for attention.

**Comment by felipebiox** [comment]
Hi all,

I'm closing this issue now that the fix is available on the latest version.

Please, feel free to open new issues. Thanks for your contribution.

Best regards
