### ISSUE TITLE
3.0.1b Shortcut outer tab navigation

### ISSUE THREAD

**Issue by pgaro** [OmniDB/OmniDB#1173]
Another thing I miss coming from OmniDB 2 is the ability to cycle though outer tabs with keyboard shortcuts. Is that on the roadmap somewhere?

**Comment by felipebiox** [comment]
Hi @pgaro ,

We are re-including this shortcut.

We have pinned a issue (#1196) to facilitate tracking a list of desired shortcuts in omnidb.

I'm now closing this issue.

Thank you for contribution.

Best regards
