### ISSUE TITLE
3.0.1b cpu usage

### ISSUE THREAD

**Issue by pgaro** [OmniDB/OmniDB#1177]
Only tested with firefox: Just after login OmniDB "Web Content" subprocess of firefox uses a lot of cpu (45-70 % measured with top on my local machine) idly sitting around.

That slightly raises upon execution of a query, but the baseline seems way to high for not really doing anything.

**Comment by rafaelthca** [comment]
Thanks. Already found the problem and working on a hotfix that should be out tomorrow.

**Comment by pgaro** [comment]
Much better!
