### ISSUE TITLE
can't log in as admin

### ISSUE THREAD

**Issue by msalka** [OmniDB/OmniDB#1182]
After build, and run docker image, can't login as admin
Version : 3.0.2b 
Branch : dev
![obrázok](https://user-images.githubusercontent.com/39370267/97716185-9bd05a00-1ac3-11eb-84a0-a20913c456b3.png)

**Comment by felipebiox** [comment]
Hello @msalka ,

I just made a fresh attempt with this and it worked. Some considerations:

Did you proceed with the step to create the admin user with [docker exec](https://hub.docker.com/r/omnidbteam/omnidb)
Section: **Creating a super user**

if you executed it like this
`docker exec -it my_container python omnidb-server.py --createsuperuser=admin pass`
Your access would be user `admin` password `pass`

Best regards

**Comment by felipebiox** [comment]
If you still have problems, please confirm and I will label this as bug to be better assessed

**Comment by msalka** [comment]
Thank you, your answer, solved my problem.
