### ISSUE TITLE
ctrl+up arrow doesn't show the last query in console tab

### ISSUE THREAD

**Issue by erdusa** [OmniDB/OmniDB#1188]
In 3.0.2b I cannot use the very useful option ctrl+up arrow for view the last query I had executed, please do not remove this feature

**Comment by erdusa** [comment]
I would like adding to this issue this: when I put cursor at the beginning to the line and I press shift + down arrow, it doesn't select the row

**Comment by felipebiox** [comment]
Hi @erdusa ,

We created an issue (#1196) to centralize a list of desired shortcuts in OmniDB.

Already added it to the list.

Editor keyboard navigation and selection has been reported and is also being worked.

I'm now closing this issue, thank you for your contribution.

Best regards
