### ISSUE TITLE
Could we add a password option to --createconnection?

### ISSUE THREAD

**Issue by cyrilcros** [OmniDB/OmniDB#1195]
Hi,
could you please add an option to create a new database **with a configured password** in `omnidb-server.py`? you can't add the password via CLI right now. The relevant code starts here: https://github.com/OmniDB/OmniDB/blob/feb6bf8006cd6c8e3527b7982ca3ec5a75af4d80/OmniDB/omnidb-server.py#L342
I could make a pull request and:

- reuse the same command but extend it to consume 8 args. That's a breaking change?
- copy paste the code to get a new `--createconnectionwithpassword` option
- instead use a connection string? `--createconnectionfromstring username title url`

That would help for Omnidb config in Docker etc... I see your code already allows setting password for users, that's just as safe.

**Comment by barthisrael** [comment]
Hi @cyrilcros 

Implemented and ready for next release. Straight forward change as you suspected.

Regards,
Israel.

**Comment by cyrilcros** [comment]
@barthisrael Awesome, thanks for your work!
