### ISSUE TITLE
SERIOUS WARNING: Download of Windows Version comes with VIRUS!

### ISSUE THREAD

**Issue by MichaelDBA** [OmniDB/OmniDB#1201]
I downloaded the current version of OmniDB for windows (3.0.2b) today, Sunday, Nov. 22, 2020 from the official OmniDB site and my Virus protector, McAfee, detected a virus (**Suspect!5c9c7bf8fff5**) embedded in the **omnidb-server.exe** file.  It removed it successfully but I thought it was important to bring this to your attention.

**Comment by sabatex** [comment]
Windows 10 detect - "Trojan:Win32/Wacatac.D9!ml"

**Comment by felipebiox** [comment]
Hello folks,

This has already been reported and researched: `false-positive` #1185 

We are working on a solution for this.

Thank you for your contribution.

Best regards

**Comment by felipebiox** [comment]
I'm closing this one to avoid the duplicate discussions, the other will remain open and you can ask questions there if you want to know more.
