### ISSUE TITLE
Private reporting of security vulnerability

### ISSUE THREAD

**Issue by Sim4n6** [OmniDB/OmniDB#1318]
Hi OmniDB team,

I may have identified a security vulnerability in "OmiDB". Could you please enable the [Private reporting of security vulnerability](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) feature in GitHub, so that I could proceed privately?

Thank you in advance

**Comment by Sim4n6** [comment]
![image](https://user-images.githubusercontent.com/13036531/207829577-9cb1cba8-8ea8-4532-b75f-8765b0664b80.png)

**Comment by masc-be** [comment]
Since few months, 2ndQuadrant become a part of EnterpriseDB. EDB is the maintainer of pgAdmin. I imagine this project, the developers and his skills, move to pgAdmin.

**Comment by Sim4n6** [comment]
alright, thank you for the response.
