### ISSUE TITLE
doesn't perform well on mobile devices

### ISSUE THREAD

**Issue by zedweein** [OmniDB/OmniDB#1324]
It doesn't perform well on mobile devices, are there plans to adapt it to a responsive web interface?

**Comment by eug3nix** [comment]
Hi @zedweein.
We at Commandprompt Inc. have forked Omnidb and actively working on its development. The new name of project is PgManage:
https://github.com/commandprompt/pgmanage/releases
https://pgmanage.readthedocs.io/

P.S. While our version is not optimized for mobile platforms and is build as a desktop app, still it has a lot of improvements done when compared to original Omnidb, so feel free to check it out
Bug reports, feature requests and any other feedback is appreciated!

**Comment by zedweein** [comment]
Thanks for your answer and best wishes
