### ISSUE TITLE
Worst practices / broken by design.

### ISSUE THREAD

**Issue by MrJoy** [OmniDB/OmniDB#17]
Live schema updates are incompatible with any sort of dev-->staging-->production workflow, even *before* you consider common scenarios like multiple developers with local schema.

Please take some time to understand why "database migrations" started becoming (widely) popular around 2005 -- and why live schema updates of *any* sort are a mortifying concept to ops folks everywhere.

Shoot-from-the-hip is incompatible with adhering to SLAs and meeting business needs.

**Comment by wind39** [comment]
Database First approach is still used on many business scenarios. Our design is not far from many well-known and wide-used graphical database management tools out there.

We agree that database migrations is a hot topic and is spreading very fast, we are receiving a lot of requests to implement it on OmniDB and we will surely do that.

OmniDB schema conversion feature is not meant to replace or mimic database migrations, not at all. This feature is meant to be used in scenarios where a change of technology is necessary. I can give you a real example, our company recently decided to abandon Oracle and started using PostgreSQL, so we had to convert all our databases to the new technology.

Thank you for your feedback, we will use it to improve this tool the best way we can.
