### ISSUE TITLE
Does omnidb support linux ?

### ISSUE THREAD

**Issue by pmaingi** [OmniDB/OmniDB#18]
Hi,
I love omni and i would like to start using it. Where can i find the linux version, am using ubuntu 14.

**Comment by rafaelthca** [comment]
Hello pmaigi.

Thank you for your feedback!

Yes, OmniDB is supported on linux. Note that OmniDB is a web application, so you need a webserver to host it.

On Linux you can use Mono (virtual machine) along with XSP4 (webserver) to run OmniDB.

It is very easy to install these requirements:

sudo apt-get install mono-complete mono-xsp4

After that, go to the folder where OmniDB is and just type

xsp4 --port PORT

where PORT is the port of your choice.

And that's it. Open your browser and type 127.0.0.1:PORT

If you need further info, just ask :)

**Comment by pmaingi** [comment]
Thanks @rafaelthca
