### ISSUE TITLE
Update tree view after creating a snippet

### ISSUE THREAD

**Issue by madflow** [OmniDB/OmniDB#196]
When I create a snippet - I want the tree view on the left to be updated after creating the snippet.

Current behavior:

A user has to reload the page to view the newly created smippet.

Proposed behavior:

The tree view is updated after saving the snippet.

**Comment by rafaelthca** [comment]
Hi madflow,

you don't have to reload the page, you can right click the parent node and refresh it to get the current children, but updating the tree automatically would be more appropriate indeed. Issue noted.

**Comment by madflow** [comment]
👍 Thanks for the tip! Yes - I was aiming at "no user triggered refresh needed".

**Comment by rafaelthca** [comment]
Implemented. This will be available in the next release, which is coming out next week (12 Sept)

**Comment by madflow** [comment]
:+1:
