### ISSUE TITLE
Switch from Workspace tab to Connections tab and back removes Queries tabs

### ISSUE THREAD

**Issue by ed-g** [OmniDB/OmniDB#200]
OmniDB 2.0.4 on linux, connecting to postgresql 9.6.

When I switch from Workspace tab to Connections tab and back deletes all Snippets and Query sub-tabs are removed and their previous contents are gone.

That would no big deal if there were a warning but it's been an easy way for me to accidentally lose all the queries I was using.

OmniDB is great, keep up the good work!

**Comment by rafaelthca** [comment]
Hi ed-g,

We are already implementing an automatic way of saving all query sub-tabs and the snippets, this will come out in the next release. Thank your for the feedback!

Rafael.

**Comment by rafaelthca** [comment]
Fixed in 2.3.0.

Query tabs are saved and restored when the user comes back to the workspace.

Closing this.
