### ISSUE TITLE
Fresh install on macosx el capitan. Fails to start.

### ISSUE THREAD

**Issue by timuckun** [OmniDB/OmniDB#201]
Launch the app nothing happens. No server? Also omnidb does not show up as an app when using spotlight.

**Comment by rafaelthca** [comment]
Hi Timuckun,

Python isn't backwards compatible in mac OSX builds. Version 2.0.4 was bundled with a python bundled in Sierra and that is probably why isn't running on El Capitan. A new build is being prepared in Yosemite, which will work on all newer versions (El Capitan and Sierra).

A server version for Mac is also being prepared.

Rafael.

**Comment by rafaelthca** [comment]
When you open the app, it opens and closes in the Dock?

**Comment by rafaelthca** [comment]
Timuckun,

a new build was done, this should work in Yosemite, El Capitan and Sierra. You can download it in:

https://omnidb.org/index.php/en/downloads-en

**Comment by wind39** [comment]
Hi @timuckun ,

For the last months, we have been building OmniDB app for MacOSX supporting Yosemite, El Capitan and Sierra. I'm closing this ticket now, but if you are still having trouble running OmniDB app, please open a new issue.
