### ISSUE TITLE
Save databases password

### ISSUE THREAD

**Issue by n9010** [OmniDB/OmniDB#203]
Hi,
We are evaluating this software and so far seems really nice. I have succesfully installed the server version on a FreeBSD machine.
Is there a way to store the password of the servers? Is a bit annoying to have to retype them all the time and i think is a bit redundant to have another password to type after login in with the user.

Thanks in advance for any reply.

**Comment by wind39** [comment]
Hi n9010,

Thanks for testing the tool, we appreciate the feedback.

The password is kept in memory, not disk, and it expires every 30 minutes
without interacting with the database, in order to enforce security. In the next
release we will allow the user to store the password encrypted inside OmniDB
database, but the user should be aware that this is a security risk.

In the meantime, you can store your password in a .pgpass file [1] in the home
directory of the user who started OmniDB. OmniDB will use the password from
this file every 30 minutes, and the user won't need to type a password again.
But please bear in mind that, even if .pgpass file needs to have 0600
permissions, it is still plain text.

[1] https://www.postgresql.org/docs/9.6/static/libpq-pgpass.html

**Comment by n9010** [comment]
Thanks for the quick reply, i'll use this method for now. 
Keep up with the good job.

**Comment by kobaz** [comment]
The last update on this was from 2017... I don't see a save password feature in omnidb yet (without using .pgpass).  Is this something that's going to be included?

Thanks!

**Comment by phasath** [comment]
We're on 2020 and we still don't have this feature =/ Sadly

**Comment by martinmurciego** [comment]
It is a great tool, we begin to use and ask you to save the password in the connections, or else please show us how to implement that change for our production version.

**Comment by felipebiox** [comment]
Hi everyone,

First of all, thank you for the patience. This is one of those features that, as awesome as it is, it wasn't prioritized in earlier versions. The roadmap has many other cool features in line, along with critical implementations that need immediate attention.

As stated in #1067 we are closing gaps and plan to reintroduce scheduled releases every 2 months to get back on track.

Rest assured this feature is coming with OmniDB 3.0

**Comment by gt-novelt** [comment]
You can now enter connection string which kinda solves the issue.

I like neither the connection string nor the .pgpass solutions. I would rather have the password encrypted where I know it is safe. But at least it saves the burden of typing it over and over.

**Comment by drewdle** [comment]
I'm trying to configure omnidb with .pgpass file and SSH tunnel. It seems no matter where I put the .pgpass file, omnidb doesn't see it. It's set with permissions of 600. 
I do get it to work with connection strings, but it has trouble with any non-alpha characters in the password.
Thanks, Andy

**Comment by goldencut** [comment]
Hi, These seemingly unimportant issues (for devs) can make a world of difference to users, and in the long run also to the project (no users - no project). So just an idea - maybe add an option to save all the connections user has added to a .pgpass file? Just a tickbox in settings. And user can add the passwords manually to the file if s/he chooses to.  

BR,
M.

**Comment by rafaelthca** [comment]
Hi,

We are adding the possibility to save the password in OmniDB 3.0, coming out very soon.

We are not going to touch pgpass though. Password will be stored in OmniDB's metadata if the user decides to do that.

**Comment by martinmurciego** [comment]
If I have different connections for different databases (MySQL, Postgres, etc.), can I also save the passwords and open connections without being asked again?

**Comment by barthisrael** [comment]
Hello everyone,

This feature was released in OmniDB 3.0 beta. We invite you to use it.

About your question @martinmurciego , yes, once you save it, you'll not be prompted again for that.

Regards.
