### ISSUE TITLE
Problem loading with psycopg2 and glibc 2.26

### ISSUE THREAD

**Issue by madflow** [OmniDB/OmniDB#220]
Hi,

I packaged omnidb-* for Arch Linux just for lulz.

* https://aur.archlinux.org/packages/omnidb-server
* https://aur.archlinux.org/packages/omnidb-app

However - since an Arch Linux uprade to glibc 2.26 the app/server does not start anymore.

```
[root@frosch ~]# python --version
Python 3.6.2
[root@frosch ~]# omnidb-server 
Traceback (most recent call last):
  File "omnidb-server.py", line 33, in <module>
  File "/root/.pyenv/versions/3.5.2/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/psycopg2/__init__.py", line 50, in <module>
  File "/root/.pyenv/versions/3.5.2/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
ImportError: /opt/omnidb-server/libresolv-2-c4c53def.5.so: symbol __res_maybe_init, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
Failed to execute script omnidb-server
``` 

This is due to: https://github.com/psycopg/psycopg2-wheels/issues/2

When I copy the latest psycopg2 (2.7.3.1) over the the extension in the omnidb-server directory:

```
sudo cp /usr/lib/python3.6/site-packages/psycopg2/_psycopg.cpython-36m-x86_64-linux-gnu.so psycopg2._psycopg.so
```

then it starts again.

For convenience - I just used the Debian packages for packaging. This would probably not be a problem when I would invest more time compiling a build for Arch Linux from scratch.
Clearly Arch Linux is not targeted in your builds - so I do not expect extensive support here.

However: I reckon that since psycopg2 is bundled via pyinstaller - the app and server will not be able to start on any system with glibc 2.26 at the moment.

Maybe you can consider updating psycopg2 in the next release?

**Comment by wind39** [comment]
Hi @madflow ,

Thanks for using OmniDB and for packaging it for Arch Linux :+1: 

Also thanks for reporting this. We compile the build on the oldest operating system as possible, taking advantage of glibc backward compatibility. But we weren't aware of this bug in psycopg2-wheels.

glibc 2.26 was released on 2017-08-02, it's brand new. I think updating psycopg2 for the next release is the way to go.

We intend to build specific packages for Arch Linux in the near future, and we would gladly accept any piece of information or help on that matter :)

**Comment by MightySCollins** [comment]
It might help if you reinstall psycopg2 and don't use the binary using the below command I found at https://lists.archlinux.org/pipermail/arch-general/2017-August/044157.html

    pip install --no-binary :all: psycopg2

**Comment by wind39** [comment]
Psycopg2 was updated for the build of 2.2.

**Comment by madflow** [comment]
👍 I can confirm: The Arch package is working again!

**Comment by yw-fang** [comment]
I also got this error when using other codes, my way to resolve this error is upgrading my psycopg2 (e.g. pip install psycopg2). After roughly reading the above answers, it seems that this error can be usually caused by an old version of psycopg2 package.
