### ISSUE TITLE
Unable to use some password

### ISSUE THREAD

**Issue by noizo** [OmniDB/OmniDB#239]
While connecting to postgres instance as `postgres` user, we have some problems using password which contains some special characters.

`!0B'>p8dH_&L`

Try it :)

**Comment by wind39** [comment]
Hi @noiso,

Thanks for reporting this. Next release will contain this fix.

In the meantime, you can escape the quote like this: `\'`

Regards,
William

**Comment by rafaelthca** [comment]
Fixed in 2.3.0. Closing this.
