### ISSUE TITLE
Click and drag image

### ISSUE THREAD

**Issue by scottmangiapane** [OmniDB/OmniDB#261]
Hello,

This doesn't impact functionality, just a little quirk I noticed that you may or may not care about. I noticed that if I click and drag a picture from my computer to the OmniDB window, the contents of the OmniDB window are replaced with the image. I'm guessing this behavior is a result of the app being chromium based.

**Comment by rafaelthca** [comment]
Hi Scott,

Yeah, that is chromium behaviour, it is possible to prevent that by adding some event listeners.  I will add this to the roadmap. Thanks for bringing this up.

Rafael.

**Comment by scottmangiapane** [comment]
Awesome. Thank you :)

**Comment by rafaelthca** [comment]
Fixed in 2.3.0. Closing this.
