### ISSUE TITLE
Version 2.4 replication query problems on PG 10

### ISSUE THREAD

**Issue by MichaelDBA** [OmniDB/OmniDB#315]
The replication monitoring scripts for master and slave still used the old functions:
pg_whatever_**xlog**_whatever

instead of

pg_whatever_**wal**_whatever

Also, change all occurrences of **location** to **lsn** in those functions.

But that is pretty neat how I can go in there and modify the scripting to get past any errors.

**Comment by wind39** [comment]
Hi @MichaelDBA ,

Thanks for your feedback. We will create separate versions of the monitors. Just for the record, all default monitors are open source in this repository [1].

Also, for more information about the Monitoring Dashboard, please take a look at the documentation [2]. Any further feedback is very welcome :)

[1] https://github.com/OmniDB/monitors
[2] https://omnidb.org/en/documentation-en/14-monitoring-dashboard-en

**Comment by MichaelDBA** [comment]
Great!  Thanks!
