### ISSUE TITLE
2.4 Mac - Scram authentication

### ISSUE THREAD

**Issue by alasdairdc** [OmniDB/OmniDB#316]
Using the `dmg` for Mac from the website.  Attempting to connect to a PG10 instance that uses `scram` as authentication, plugging in the correct details and clicking `test connection` OmniDB responds with:

    authentication method 10 not supported

**Comment by barthisrael** [comment]
Hello @alasdairdc ,

We have tested it using OmniDB 3.0 which was recently released as a beta version and it has worked with `scram` authentication. Please test it and see how it goes.

Regards.
