### ISSUE TITLE
Shortcut editor

### ISSUE THREAD

**Issue by patschwork** [OmniDB/OmniDB#34]
Hi, 

first - thank you for the great tool, keep up the really good work :-)

It would be nice, to edit the shortcuts in a GUI.
F.e.: On Linux (Linux Mint, Firefox) CTRL+Q closes firefox/tab. 

Bye
Patrick

**Comment by rafaelthca** [comment]
@patschwork, thank you for your feedback!

I've created config parameters to change these shortcuts. There is a file called web.config with the following lines:

<add key="OmniDB.Keybind.Execute.Win" value="Ctrl-Q" />
<add key="OmniDB.Keybind.Execute.Mac" value="Command-Q" />
<add key="OmniDB.Keybind.Replace.Win" value="Ctrl-G" />
<add key="OmniDB.Keybind.Replace.Mac" value="Command-G" />

The first two control shortcut to execute the query and the others to open the new Replace Text interface.

It is a great idea to add a GUI to edit these and other shortcuts, we will do that in the near future.
