### ISSUE TITLE
psql macros?

### ISSUE THREAD

**Issue by stellr** [OmniDB/OmniDB#340]
Is there a way to get the psql macros to work in OmniDB query pane?

template1=# \l
********* QUERY **********
SELECT d.datname as "Name",
       pg_catalog.pg_get_userbyid(d.datdba) as "Owner",
       pg_catalog.pg_encoding_to_char(d.encoding) as "Encoding",
       d.datcollate as "Collate",
       d.datctype as "Ctype",
       pg_catalog.array_to_string(d.datacl, E'\n') AS "Access privileges"
FROM pg_catalog.pg_database d
ORDER BY 1;
**************************

**Comment by wind39** [comment]
Hi @stellr ,

Thanks for getting in touch. Currently there is no way, but we already started implementing a new feature supporting the most used psql macros. It will be published in the next release or the another. Stay tuned!

Regards,
William Ivanski

**Comment by wind39** [comment]
Hi @stellr ,

Today we released 2.6.0 with a new feature called "Console Tab", which allows you to execute several commands like `psql`:

![image](https://user-images.githubusercontent.com/7719686/37476281-7de7f10c-2853-11e8-8f18-8c1992e43e59.png)

We'd love to get your valuable feedback on this, please, so I'm keeping this issue open for now.

Regards,
William Ivanski

**Comment by wind39** [comment]
Hi,

It's been a while, so we are closing this issue now. Feel free to comment here or open a new issue anytime!

Thanks and regards,
William Ivanski
