### ISSUE TITLE
Allow export query results to CSV from query editor

### ISSUE THREAD

**Issue by palmerj** [OmniDB/OmniDB#375]
Should allow for configuration of:

* CSV field separator.
* CSV quote character
* CSV quoting (none or strings, or all)

**Comment by wind39** [comment]
Hi @palmerj ,

Thanks for your input. This feature is a must, hands down. It is in the roadmap already, we will implement it in the near future.

**Comment by stompro** [comment]
HeidiSQL handles data export fantastically.  I would recommend taking a look at how they handle it when deciding how OmniDB is going to handle it.  https://www.heidisql.com/screenshots.php?which=export_textfile  - this screenshot is missing features.  I use the export to HTML table daily to quickly send data to various people via email.

**Comment by wind39** [comment]
Thanks for the suggestion, @stompro , indeed a good user interface :+1:

**Comment by rafaelthca** [comment]
This will be implemented in the next release, 2.6.0

**Comment by wind39** [comment]
Hi @palmerj ,

We implemented a basic Export feature in version 2.6.0. It allows you to export to XLSX and CSV. It doesn't have a configuration interface yet. Can you please try?

Thanks and regards,
William Ivanski

**Comment by praja76** [comment]
Hi @wind39 ,

i'm verry happy with feature export in version 2.6.0. thanks a lot and good job

Iman

**Comment by erdusa** [comment]
Hi, maybe should this be closed?

**Comment by wind39** [comment]
Hi @erdusa ,

Yes, you are right. Closing this now, thanks.
