### ISSUE TITLE
Move runtime files to a separate directory

### ISSUE THREAD

**Issue by randombk** [OmniDB/OmniDB#378]
Move configuration and log files (`omnidb.log`, `omnidb.db`, etc.) to a separate directory that docker can mount so persistent state can be moved to a separate volume for long-term storage.

**Comment by rafaelthca** [comment]
Hi randombk,

Yes, this has been requested before. The feature will probably be included in version 2.6.0.

2.5.0 is coming out next monday. As you may have noticed releases come out very often (every 4 weeks), so this should be included soon.

Thank you for reporting this.

Rafael.

**Comment by wind39** [comment]
Hi @randombk ,

We implemented argument `-d` for the `omnidb-server`, which allows you to specify a home directory, where such files will be stored.

It is released along with 2.6.0 we just published. Can you please try? We'd love to hear your feedback on this, please, so I'm keeping this issue open for now.

Thanks and regards,
William Ivanski

**Comment by randombk** [comment]
Hi @wind39,

I can confirm that this seems to work well with both Docker volumes as well as dropping container permissions to the `nobody` user.

Thanks!
David
