### ISSUE TITLE
mac os x ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

### ISSUE THREAD

**Issue by deem0n** [OmniDB/OmniDB#385]
I've installed instantclient_12_2 64 bit, but can not connect to the Oracle using SID.

**Comment by wind39** [comment]
Hi @deem0n ,

Thanks for your interest. OmniDB requires that you provide every field in the connection grid: host, port, service and user.

How are you trying to connect?

**Comment by deem0n** [comment]
Everything is filled in except `Title`

Is there any logs I can check and/or send here ?

**Comment by rafaelthca** [comment]
Can you check if the Database field corresponds to a service name specified in tnsnames.ora used by the Oracle listener?

**Comment by deem0n** [comment]
Based on this: https://stackoverflow.com/questions/24149138/cx-oracle-doesnt-connect-when-using-sid-instead-of-service-name-on-connection-s I assume that it is better to differentiate SID from SERVICE_NAME, so user will avoid bothering with `tnsnames.ora`

Seems, I am unable to supply `tnsnames.ora`. Even though I created `~lib/network/admin/TNSNames.ora`

```
DBTST01 =
(DESCRIPTION =
 (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.103.19)(PORT = 1521)
  )
 (CONNECT_DATA =
  (SID = DBTST01)
  )
 )
```
Seems the file is not used by OmniDB.

For now, I see that the problem might be with how `Spartacus` generates connect string for Oracle.
https://github.com/wind39/spartacus/blob/master/Spartacus/Database.py#L2049
Probably this would fix the problem, but we need some hint in UI if user supplied SID or Service name:

FOR SID:
```python
class Oracle(Generic):
    def __init__(self, p_host, p_port, p_service, p_user, p_password):
        if 'Oracle' in v_supported_rdbms:
            self.v_host = p_host
            if p_port is None or p_port == '':
                self.v_port = 1521
            else:
                self.v_port = p_port
            if p_service is None or p_service == '':
                self.v_service = 'xe'
            else:
                self.v_service = p_service
            self.v_user = p_user
            self.v_password = p_password
            self.v_con = None
            self.v_cur = None
        else:
            raise Spartacus.Database.Exception("Oracle is not supported. Please install it with 'pip install Spartacus[oracle]'.")
    def GetConnectionString(self):
        return cx_Oracle.makedsn(self.v_host, self.v_port, sid=self.v_service)
    def Open(self, p_autocommit=True):
        try:
            self.v_con = cx_Oracle.connect(user=self.v_user, password=self.v_password, dsn=self.GetConnectionString())
            self.v_cur = self.v_con.cursor()
            self.v_start = True
        except cx_Oracle.Error as exc:
            raise Spartacus.Database.Exception(str(exc))
        except Exception as exc:
            raise Spartacus.Database.Exception(str(exc))
```
for service_name
```python
class Oracle(Generic):
    def __init__(self, p_host, p_port, p_service, p_user, p_password):
        if 'Oracle' in v_supported_rdbms:
            self.v_host = p_host
            if p_port is None or p_port == '':
                self.v_port = 1521
            else:
                self.v_port = p_port
            if p_service is None or p_service == '':
                self.v_service = 'xe'
            else:
                self.v_service = p_service
            self.v_user = p_user
            self.v_password = p_password
            self.v_con = None
            self.v_cur = None
        else:
            raise Spartacus.Database.Exception("Oracle is not supported. Please install it with 'pip install Spartacus[oracle]'.")
    def GetConnectionString(self):
        return cx_Oracle.makedsn(self.v_host, self.v_port, service_name=self.v_service)
    def Open(self, p_autocommit=True):
        try:
            self.v_con = cx_Oracle.connect(user=self.v_user, password=self.v_password, dsn=self.GetConnectionString())
            self.v_cur = self.v_con.cursor()
            self.v_start = True
        except cx_Oracle.Error as exc:
            raise Spartacus.Database.Exception(str(exc))
        except Exception as exc:
            raise Spartacus.Database.Exception(str(exc))
```

**Comment by deem0n** [comment]
Also, quite strange, but based on Wireshark packet analyzer I see wrong user name.
![image](https://user-images.githubusercontent.com/871385/36303982-1b3251ea-131f-11e8-8da7-bb09d57fdb61.png)

but packet which sent to Oracle contains:
```lisp
(DESCRIPTION=(CONNECT_DATA=(SERVICE_NAME=dima)(CID=(PROGRAM=omnidb-app)(HOST=MacBook-Pro-3.local)(USER=macosuser)))(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.103.19)(PORT=1521)))
```
macosuser is the OS user I am logged in, not `BI_LOADER`

**Comment by deem0n** [comment]
putting `tnsnames.ora` to ~/instantclient_12_2/network/admin as suggested here http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html#ic_osx_inst did not help

**Comment by wind39** [comment]
Hi @deem0n ,

OmniDB does not work with SID, only SERVICE_NAME. At the moment it will always try to connect in the form `user/pwd@host:port/dbname`. In the future we can implement a new connection field to allow the user specify SID or SERVICE_NAME, and then we will use `cx_Oracle.makedsn`. Thanks for your analysis and suggestion.

We will keep this open for this implementation.

**Comment by deem0n** [comment]
Thanks for the positive resolution! Greatly appreciated.

**Comment by wind39** [comment]
Hi @deem0n ,

I've been talking through e-mail to another OmniDB user who got to the bottom of this, discovering that in `cx_Oracle`, it is possible to connect using `tnsnames.ora` and `sqlnet.ora` files if you use a connection string like this: `user/pwd@service`.

For example, if you have a wallet configured to allow TCPS connections through certificates in `tnsnames.ora` and `sqlnet.ora`, using this connection string, OmniDB will be able to connect to Oracle using TCPS instead of default TCP.

So I just pushed [a commit](https://github.com/OmniDB/OmniDB/pull/482/commits/0cc9877cee7a78e2a29c09ba4a41dcf14aa36860) which handles the situation for the future release. The idea is that if the user omits host and port, OmniDB will try to connect using the connection string `user/pwd@service`.

This fix will be packaged in OmniDB 2.8, coming out in next 17th May.

**Comment by wind39** [comment]
Hi @deem0n ,

Can you please test it and provide your valuable feedback? Thanks very much in advance!

Regards,
William Ivanski

**Comment by wind39** [comment]
I'm closing this now.
