### ISSUE TITLE
json type field string values are wrapped in apostrophes (') instead of quotation marks (")

### ISSUE THREAD

**Issue by FOOTCRAB** [OmniDB/OmniDB#387]
this results in invalid json both when displaying and copying the content of the field

**Comment by rafaelthca** [comment]
You mean when querying JSON columns the output in the grid is incorrect?

**Comment by FOOTCRAB** [comment]
yes, for example this is sample JSON column output copied from OmniDB:
`{'key': 'value'}`

which is not a valid json. the same column copied from pgadmin or adminer output grid looks like this:
`{"key":"value"}`

**Comment by rafaelthca** [comment]
Thank you. I already fixed this, it is a special property that was disabled in the python library that connects to PostgreSQL (psycopg2).

This will be included in the next release (which is coming out in around 3 weeks).

Rafael.

**Comment by FOOTCRAB** [comment]
perfect, thanks!
