### ISSUE TITLE
Connection to Apache Drill?

### ISSUE THREAD

**Issue by saurabhmahapatra94** [OmniDB/OmniDB#388]
Hi all, 

It is very impressive to see what you are trying to accomplish. 

I came across your project while browsing for open source SQL editor tools and was wondering if you do have plans for supporting connectivity to Drill. There is a big demand from our user community for such tools and we would like to promote more open source tools that are trying to do the same. 

Our project is listed here:
https://drill.apache.org/

If you subscribe to our user list, I can introduce you to the community and you can get more users. The user/dev list is here:
https://drill.apache.org/mailinglists/

Thanks,
Saurabh
https://www.linkedin.com/in/saurabhmahapatra/

**Comment by wind39** [comment]
Hi @saurabhmahapatra94 ,

Thanks for reaching out. Unfortunately we don't have any plans to implement support to Apache Drill in the foreseeable future.

We may revisit this in the future, but for now I'm closing this issue.

Best regards,

William
