### ISSUE TITLE
omnidb_plugin binary for Windows

### ISSUE THREAD

**Issue by MahatmaFatalError** [OmniDB/OmniDB#393]
Is it possible to debug stored procedures on a Windows Server? Can't find the omnidb_plugin for Windows.

**Comment by MahatmaFatalError** [comment]
@wind39 Thx for the reply, I am referring to the latter one (PG Server on Windows)

**Comment by rafaelthca** [comment]
Hi @MahatmaFatalError,

The plugin will be available for Windows in the next release, which should be coming out in around 3 weeks.

**Comment by wind39** [comment]
Hi @MahatmaFatalError ,

We just released 2.7.0. There is a version of `omnidb_plugin` for Windows. Can you please try it? We are keeping this open for a while, any feedback is welcome!

Thanks and regards,
William Ivanski

**Comment by wind39** [comment]
Hi @MahatmaFatalError ,

Thanks for your feedback. I'm closing this issue now.
