### ISSUE TITLE
OmniDB does not show the total rows updated

### ISSUE THREAD

**Issue by erdusa** [OmniDB/OmniDB#395]
When I run a script to update some rows, OmniDB only shows the word "Done" but I don't know how many rows were updated

**Comment by wind39** [comment]
Hi @erdusa ,

Thanks for your suggestion. I invite you to try the new Console Tab feature we just released in version 2.6.0. It behaves very similarly to psql. For example, to execute a sequence of updates:

![image](https://user-images.githubusercontent.com/7719686/37475525-aecafa50-2851-11e8-8c4a-a0a86f855b66.png)

You get the same feedback as you do in psql:

![image](https://user-images.githubusercontent.com/7719686/37475594-d210bc16-2851-11e8-84ea-e66a7ade52a4.png)

We'd like to hear your feedback on this, please, so I'm keeping this issue open for now.

Regards,
William Ivanski

**Comment by erdusa** [comment]
Hi @wind39 

The console is very good, congratulations, I have a question, is it possible to have the same behaviour in query tab? and I take this opportunity for asking how do I use the command "describe" in the console tab? thanks in advance

**Comment by wind39** [comment]
Hi @erdusa ,

Thanks for your valuable feedback. Currently it is not possible to have the same behaviour in Query Tab, as it was designed to work differently:

- **Query Tab**: It is the standard approach. You can run several commands separated by `;` and run queries that return several rows taking advantage of features like `Fetch More` and `Fetch All`. The data grid is much more easily to navigate, and you can copy/paste data into a spreadsheet. With the new `Export` feature, you can export grid data into CSV/XLSX files. In PostgreSQL, you also have `Explain` and `Explain Analyze` features.

- **Console Tab**: It is designed to provide `psql` facilities and behavior. For PostgreSQL, there are handy commands such as `\l`, `\dt`, etc. Similarly to `psql`, you can have more details about the commands you execute, and also handle transactions manually with `BEGIN;` and `COMMIT;` | `ROLLBACK;`.

I can see you are having trouble with the `DESCRIBE` and `\d+` commands, as you opened issue #424 . We can handle it there, so I'm closing this one.

Thanks and regards,
William Ivanski
