### ISSUE TITLE
Small collection of smaller things

### ISSUE THREAD

**Issue by cschwaderer** [OmniDB/OmniDB#403]
Dear all,

I have just some smaller remarks on how OmniDB 2.5.0 could be improved:

- Double click on a function in the list should open "edit function". Double click on tables should, in my opinion, show the table definition as query.
- When adding a new query (+ symbol), the input field should be focused (it's not right now, so you need an extra click)
- While running a query which takes some time: display the time elapsed so far, so that you can keep track on how long it's already running (and kill it if you feel like it)
- For displaying JSON as query results, I'd rather have " than ' as delimiters.

**Comment by rafaelthca** [comment]
Hi cschwaderer,

Thank you for the suggestions, these are all good points. Small details that are much easier to implement than the major features we are working on at the moment, but extremely important to the end user.

> For displaying JSON as query results, I'd rather have " than ' as delimiters.

This was already fixed, the fix will come in the next release (next week).

> When adding a new query (+ symbol), the input field should be focused (it's not right now, so you need an extra click)

Good point, will implement that for the next release.

> While running a query which takes some time: display the time elapsed so far, so that you can keep track on how long it's already running (and kill it if you feel like it)

> While running a query which takes some time: display the time elapsed so far, so that you can keep track on how long it's already running (and kill it if you feel like it)

I'm worried about the resource consumption of this implementation, interface would have to be constantly updated for each running query, that is why we decided to add the start time instead of updated elapsed time. I will include this issue and test it.

> Double click on a function in the list should open "edit function". Double click on tables should, in my opinion, show the table definition as query.

Will discuss internally with the team to see what can be improved on this part.

Rafael.

**Comment by rightaway** [comment]
> Double click on a function in the list should open "edit function". Double click on tables should, in my opinion, show the table definition as query.

Agree with double click on function, but I think double click on table should open a preview of the table contents (`Data Actions` -> `Query Data`) as this is how pretty much all other DB GUIs behave and therefore the most expected behavior.

**Comment by cschwaderer** [comment]
Just two additional tiny things for which it is not worth opening a new issue:

- it would be nice if "messages" would be copy&pasteable. I need that sometimes

- The height of query windows should be saved. I personally like to have the query part of the window very big and the results very small. I have to re-do that after each OmniDB start.

**Comment by wind39** [comment]
Hi @rafaelthca ,

Please consider @cschwaderer 's suggestions when handling the changes to the web interface.

Thanks and regards,

William

**Comment by barthisrael** [comment]
1:18 PM



Hi @cschwaderer ,

> it would be nice if "messages" would be copy&pasteable. I need that sometimes

It's already implemented in OmniDB 3.0. Please give it a try.

> The height of query windows should be saved. I personally like to have the query part of the window very big and the results very small. I have to re-do that after each OmniDB start.

This is in our roadmap (see issue #1187 ). We thought of implementing some way of specifying the default custom layout per user. If the user doesn't have any, then OmniDB would apply its default.

Regards.
