### ISSUE TITLE
Be able to identify the database in each query or console tab

### ISSUE THREAD

**Issue by erdusa** [OmniDB/OmniDB#422]
When I have 2 databases, for instance test and production, I need to identify in each query or console tab to which database belongs each one, I'd like that this was possible, thanks

**Comment by rafaelthca** [comment]
Hi erdusa,

Each connection tab refers to a specific connection string, which are configured in the connections interface.

You can create 2 connections (one for production and other for test), use the title column to name each connection tab and use them in parallel. Does that suit your needs?

![titles](https://user-images.githubusercontent.com/9335851/37532121-81f50f98-2914-11e8-8ac3-7c320a7dcbf2.png)

Rafael.

**Comment by erdusa** [comment]
Yes, you are right, I had not realized that that was the solution, thank you very much, and I'm sorry :(

**Comment by wind39** [comment]
@erdusa , no problem at all! Thank you very much for your valuable feedback so far :+1: 

I'm closing this issue now, please feel free to open a new one whenever you need.

**Comment by erdusa** [comment]
Hi, I identified a problem with conection tab, because when I select a conection from the combo box , OmniDB doesn´t create a new tab, It only changes the title from the active tab, you can see this in this picture

![image](https://user-images.githubusercontent.com/36895220/37773682-3a9ccf86-2dac-11e8-8e7d-1504cdf7920b.png)

I have 2 tabs for the table tipodocumento, but the first is from the production database and the second is from test database, in this case I can't identify from which database is each table
