### ISSUE TITLE
Error in console tab with the DESCRIBE command

### ISSUE THREAD

**Issue by erdusa** [OmniDB/OmniDB#424]
The DESCRIBE command only works with some tables, here is the output:
>> describe persona
not enough arguments for format string
>> describe valorminimo
not enough arguments for format string
>> describe xmltemporal
+----------------+-----------------------+-----------+
|     Column     |          Type         | Modifiers |
+----------------+-----------------------+-----------+
| xmltemusuario | character varying(30) |  not null |
|   xmltemkey    |     character(20)     |  not null |
|  xmltemvalue   |          text         |  not null |
+----------------+-----------------------+-----------+
Indexes:
    "xmltemporal_pkey" PRIMARY KEY, btree (xmltemusuario, xmltemkey)

**Comment by wind39** [comment]
Hi @erdusa ,

Thanks for reporting this. Does the `\d+` command works for tables `persona` or `valorminimo`?

Also, can you please send more information about these tables so we can simulate the error here?

Thanks and regards,
William Ivanski

**Comment by erdusa** [comment]
Hi @wind39 

the \d+ command doesn't work, look:

>> \d+ xmltemporal
+----------------+-----------------------+-----------+----------+--------------+------------------------------------+
|     Column     |          Type         | Modifiers | Storage  | Stats target |            Description             |
+----------------+-----------------------+-----------+----------+--------------+------------------------------------+
| xmltemusuanick | character varying(30) |  not null | extended |     None     | Usuario que ingresa la información |
|   xmltemkey    |     character(20)     |  not null | extended |     None     |                Key                 |
|  xmltemvalue   |          text         |  not null | extended |     None     |               Value                |
+----------------+-----------------------+-----------+----------+--------------+------------------------------------+
Indexes:
    "xmltemporal_pkey" PRIMARY KEY, btree (xmltemusuanick, xmltemkey)
Has OIDs: no

>> \d+ valorminimo
not enough arguments for format string
>> describe tipodocumento
not enough arguments for format string

this is the ddl

CREATE TABLE valorminimo (
    valminid smallint NOT NULL,
    valminnombre character varying(100) NOT NULL,
    valminvalor numeric(17,6) NOT NULL
);

COMMENT ON COLUMN public.valorminimo.valminid IS 'Identificador del Valor Minimo';
COMMENT ON COLUMN public.valorminimo.valminnombre IS 'Nombre del Valor Minimo';
COMMENT ON COLUMN public.valorminimo.valminvalor IS 'Valor del Valor Minimo';

ALTER TABLE valorminimo ADD CONSTRAINT valorminimo_pkey
  PRIMARY KEY (valminid);

CREATE TABLE tipodocumento (
    tipdocid smallint NOT NULL,
    tipdocnombre character varying(50) NOT NULL,
    tipdocabreviatura character varying(5) NOT NULL,
    tipdoctipopersona character(1) NOT NULL
);

COMMENT ON COLUMN public.tipodocumento.tipdocid IS 'Identificador de Tipo Documento';
COMMENT ON COLUMN public.tipodocumento.tipdocnombre IS 'Nombre de Tipo Documento ';
COMMENT ON COLUMN public.tipodocumento.tipdocabreviatura IS 'Abreviatura de Tipo Documento';
COMMENT ON COLUMN public.tipodocumento.tipdoctipopersona IS 'Tipo de Persona';

ALTER TABLE tipodocumento ADD CONSTRAINT tipodocumento_pkey
  PRIMARY KEY (tipdocid);

**Comment by wind39** [comment]
Hi @erdusa ,

Thanks for providing detailed information. Unfortunately I could not simulate the bug here:

![image](https://user-images.githubusercontent.com/7719686/37725026-c1016614-2d10-11e8-8e5a-56c8f40f14e2.png)

At the moment I don't know what further information I can ask to help me debug this. I'll try to dig it some more and try to think about why it happens for you, then I'll get back to you.

Regards,
William Ivanski

**Comment by erdusa** [comment]
Ok, thank you, I don't know if it is important but my database is postgresql 9.5 and 9.6, and this is the psql output

![image](https://user-images.githubusercontent.com/36895220/37774254-b97de442-2dad-11e8-8dbc-1981d1902c19.png)
 this is a screenshot of the error
![image](https://user-images.githubusercontent.com/36895220/37774525-6f827172-2dae-11e8-83f6-fd852fac87e3.png)

**Comment by wind39** [comment]
Hi @erdusa ,

I managed to simulate this, it is a bug in `pgspecial` library:

```python
Python 3.5.2 (default, Aug 16 2017, 23:55:51) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Spartacus.Database
>>> d = Spartacus.Database.PostgreSQL('127.0.0.1', '5402', 'planner', 'planner', 'plaserv')
>>> d.Open()
>>> x = d.Special('\d+ planning.cfop')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/administrator/.pyenv/versions/3.5.2/lib/python3.5/site-packages/Spartacus/Database.py", line 1236, in Special
    for r in self.v_special.execute(self.v_cur, p_sql):
  File "/home/administrator/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pgspecial/main.py", line 89, in execute
    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)
  File "/home/administrator/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pgspecial/dbcommands.py", line 589, in describe_table_details
    results.append(describe_one_table_details(cur, nspname, relname, oid, verbose))
  File "/home/administrator/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pgspecial/dbcommands.py", line 1086, in describe_one_table_details
    status.append("    \"%s\" %s\n" % row)
TypeError: not enough arguments for format string
```

I'll investigate this further and probably we will need to suggest a fix in `pgspecial`.

**Comment by wind39** [comment]
Hi @erdusa ,

I managed to implement a fix for `pgspecial`. Proposed PR is [58](https://github.com/dbcli/pgspecial/pull/58) in `pgspecial` repository.

Regards,
William Ivanski

**Comment by erdusa** [comment]
Hi @wind39 

I appreciate that you have implemented the fix, will this solution be released in OmniDB 2.7?

Sincerely,
Eudis Rene Duarte

**Comment by wind39** [comment]
Hi @erdusa ,

Yes, the fix will be released in OmniDB 2.7 next week.

Regards,
William Ivanski

**Comment by wind39** [comment]
Hi @erdusa ,

We just released 2.7.0 with a fix for this. Can you please try it? We are keeping this open for a while, any feedback is welcome!

Thanks and regards,
William Ivanski

**Comment by erdusa** [comment]
Hi @wind39 

This fix solves the problem, now I can use the DESCRIBE command :) , thank you very much

**Comment by wind39** [comment]
Thanks for your feedback, I'm closing this now :)
