### ISSUE TITLE
OmniDB doesn´t create a new connection tab, It changes the title of the current tab

### ISSUE THREAD

**Issue by erdusa** [OmniDB/OmniDB#429]
Hi, I identified a problem with conection tab, because when I select a connection from the combo box , OmniDB doesn´t create a new tab, It only changes the title from the active tab, you can see this in this picture

![image](https://user-images.githubusercontent.com/36895220/37775013-bde48da4-2daf-11e8-9e1c-c573214adc27.png)

I have 2 tabs for the table tipodocumento, but the first is from the production database and the second is from test database, in this case I can't identify from which database is each table

**Comment by wind39** [comment]
Hi @erdusa ,

We just released 2.7.0. In this version, databases are 2nd-level containers inside the same connection. You don't need different connections to handle multiple databases in the same instance anymore.

Also, now there is the concept ot "Active Database". When you try to handle an object belonging for a different database, OmniDB will ask if you want to change the active database. In this case, special inner tabs such as Monitoring and Edit Data will need to be closed. So there will be no mixed table management for different databases anymore.

Can you please try 2.7.0 and provide your valuable feedback? Thanks in advance!

Thanks and regards,
William Ivanski

**Comment by erdusa** [comment]
Hi @wind39 

Great, I congratulate everyone for this change, this new approach was very necessary.

Thanks, fantastic

**Comment by wind39** [comment]
Thanks for your feedback, I'm closing this now :)
