### ISSUE TITLE
Letter color is not visible with dark themes

### ISSUE THREAD

**Issue by erdusa** [OmniDB/OmniDB#430]
When I have a dark theme configured in OmniDB, the letter is little visible in some cases, example

![image](https://user-images.githubusercontent.com/36895220/37779145-ab957d84-2db9-11e8-890c-92c4a15c777b.png)

**Comment by rafaelthca** [comment]
Hi @erdusa,

Yeah, we haven't been giving the dark themes the proper attentions, this will be fixed in the next release.

**Comment by rafaelthca** [comment]
Fixed, included in 2.7.0
