### ISSUE TITLE
Messages/elogs are ignored if statement ends in an error

### ISSUE THREAD

**Issue by cschwaderer** [OmniDB/OmniDB#431]
If I run this anonymous code block in OmniDB 2.6.0 everything works as expected:
```
DO $$
 plv8.elog(INFO,"This is just an info");
$$ LANGUAGE plv8

```
However, if I add a line which results in an error

```
DO $$
 plv8.elog(INFO,"This is just an info");
 plv8.elog(ERROR,"This is an error!");
$$ LANGUAGE plv8

```
Then I just get `Error: This is an error!` and the log `This is just an info` gets lost.
That's different in pgAdmin 3. There I get as expected:

> INFO:  This is just an info
> ERROR:  Error: This is an error!

This is really a dealbreaker for debugging! Since adding logs in an plv8-Function which eventually throws an error is actually the only way to get to know whats happening before the error occurs.

**Comment by rafaelthca** [comment]
@cschwaderer,

Noted, thanks for reporting. Will investigate

**Comment by cschwaderer** [comment]
Any news on this? It's really important to me because, in the end, it prevents our team from updating to Postgres 10 (pgAdmin 3 doesn't work on Postgres 10, OmniDB is supposed to replace it, but as long as OmniDB is not really suitable for debugging due to this bug, we cannot fully replace pgAdmin with OmniDB).

BTW here is an example in pure plpsql in case you don't use plv8:

```
DO $$
 BEGIN
    RAISE NOTICE 'I am just a notice';
    RAISE EXCEPTION 'I am an error';
 END$$;
```

Behaviour is the same: in psql and pgAdmin, I get as expected:

> NOTICE:  I am just a notice
> ERROR: I am an error
> CONTEXT:  PL/pgSQL function inline_code_block line 1 at RAISE

while in OmniDB App 2.10, I'll get just

> I am an error
CONTEXT:  PL/pgSQL function inline_code_block line 1 at RAISE

**Comment by wind39** [comment]
Hi @cschwaderer ,

Thanks for providing more details and for testing 2.10. We will definitely tackle this issue for the next version, 2.11. We will keep you updated.

Regards,
William
