### ISSUE TITLE
Export to different encoding on windows client

### ISSUE THREAD

**Issue by ChrisForsythe** [OmniDB/OmniDB#434]
Hi,

Omnidb is great, thanks for making it. :)

When exporting to csv on windows, the general usage I have would be to double click to open the csv in excel. Due to the encoding excel adds rows between each record. So it looks like this:

Row 1 - Data
Row 2 - Empty Data
Row 3 - Data
Row 4 - Empty Data.

This isn't so much a problem with Omni as a problem with Excel. However I can see this being a typical usage on windows so I wanted to file this in order to open a discussion around it.

Thanks for looking at it.

In order to import the data correctly you have to follow these steps, which can become tedious (from https://www.techrepublic.com/blog/microsoft-office/a-quick-way-to-delete-blank-rows-in-excel/):

Start Microsoft Excel
In Excel, click the Data tab, and in the Get External Data ribbon/panel, click From Text .
 

In the Import Text File dialog box, in the lower-right corner (to the right of the File name box), select Text Files (*.prn;*.txt;*.csv) as the file type, browse to the location where you exported/downloaded the CSV file, and then click Open (or Import).
 

In the Text Import Wizard - Step 1 of 3 dialog box, select Delimited, and from the File origin drop-down list, select 65001: Unicode (UTF-8) (or the appropriate language character identifier for your particular environment). 
In the Preview box, make sure that your unicode text displays properly, and then click Next.
 

In the Text Import Wizard - Step 2 of 3 dialog box, in the Delimiters section, make sure that only Comma is checked, and then click Finish.
 

In the Import Data dialog box, select New worksheet (or Existing worksheet if you have one), and then click OK.

**Comment by rafaelthca** [comment]
Hi @ChrisForsythe,

Thank you for reporting this. We will investigate.

**Comment by wind39** [comment]
Hi @ChrisForsythe ,

We just released 2.7.0 with a fix for this. Can you please try it? We are keeping this open for a while, any feedback is welcome!

Thanks and regards,
William Ivanski

**Comment by ChrisForsythe** [comment]
So good news is the alternating rows of blank rows is gone, so that's great.

However now instead of being comma separated it's ; separated from what I can tell. Which means all fields go into the first column of every row.

**Comment by wind39** [comment]
Hi @ChrisForsythe ,

I'm sorry to hear this is not fixed to you yet. During my tests, using `,` as a delimiter caused that all fields go into the first column. That's why I changed it to be `;`.

I guess a Export Options form is necessary for CSV, for example allowing the user to set encoding, delimiter and quote characters, and also if all fields should be quoted or not.

We have this in our roadmap, as soon as it is implemented, we will let you know.

Regards,
William Ivanski

**Comment by ChrisForsythe** [comment]
I don't think adding options for exporting is necessarily the approach to take. We added more options to Perian back in the day and it just increased confusion. I doubt with the user base you have there's as much of that but still I'm not one to say "hey fix it with an option.".

Omni is not my app to design, I just have my opinions here. Honestly for me it's not that big of a deal to import things I more just wanted it to be simpler.

I will say with this change I do have a slightly easier change given the drop down to pick the encoding is harder than simply selecting the delimiter. 

If you want to try exporting a test in a few different formats I'm happy to give them all a try to narrow it down, if you'd prefer that instead.

**Comment by wind39** [comment]
Thanks for your collaboration, @ChrisForsythe :)

I'll dig into it some more and will get back to you soon.

**Comment by wind39** [comment]
Hi @ChrisForsythe ,

We just released OmniDB 2.12.0. Under User Options, you will see some CSV export options:

![image](https://user-images.githubusercontent.com/7719686/47368588-4e40db80-d6b8-11e8-9cb8-5ab3668cdeb1.png)

I hope it does fit your needs. Would you please test it and provide feedback? Thanks in advance!

Regards,

William

**Comment by wind39** [comment]
Closing this now.

**Comment by ChrisForsythe** [comment]
Hey sorry about not responding, I didn't see the other email come in. This looks good to me. The only other thing I can think of to cause less confusion and/or problem reports is to (on windows) default to the encoding office would expect, and/or string replace the string in the drop down to say "$Encoding Format (Microsoft Office Compatible)" or something like that.

Either way this looks fantastic and would solve the problem for me if I hadn't switched to dbeaver. :)
