### ISSUE TITLE
OmniDB doesn't show inherited tables

### ISSUE THREAD

**Issue by erdusa** [OmniDB/OmniDB#437]
I have a scheme with only inherited tables but I don't see any tables in the tree, you can see that in this picture
![image](https://user-images.githubusercontent.com/36895220/37911061-b0273ce8-30d4-11e8-9601-2c68450d7dbe.png)

and so it looks in pgAdmin III
![image](https://user-images.githubusercontent.com/36895220/37911203-012b5354-30d5-11e8-9714-93e37a894b43.png)

**Comment by wind39** [comment]
Hi @erdusa ,

Thanks for reporting this. This is a known issue, the fix is already implemented and will be published for 2.7.0 (to be released in 2 weeks).

Regards,
William Ivanski

**Comment by wind39** [comment]
Hi @erdusa ,

We just released 2.7.0 with a fix for this. Can you please try it? We are keeping this open for a while, any feedback is welcome!

Thanks and regards,
William Ivanski

**Comment by erdusa** [comment]
Hi @wind39 

Thanks, this fix works well

**Comment by wind39** [comment]
Thanks for your feedback, closing it now :)
