### ISSUE TITLE
Loading icon doesn't disappear 

### ISSUE THREAD

**Issue by erdusa** [OmniDB/OmniDB#441]
In some cases the loading icon doesn't disappear, you can see that in this picture
![image](https://user-images.githubusercontent.com/36895220/37999194-5e62754e-31e7-11e8-8f00-34b3cde74248.png)

**Comment by rafaelthca** [comment]
hi @erdusa, can you confirm what part of the interface triggers to change mouse cursor to this loading? This is an old implementation and shouldn't be there anymore.

**Comment by erdusa** [comment]
Hi @rafaelthca, I don't remember, at this moment, how this happens, I will try to generate it again and to communicate it to you

Sincerely,
Eudis Rene Duarte

**Comment by erdusa** [comment]
Hi @rafaelthca at this time I have the problem, I have a query tab with a long sql that has a table with alias "col" when I pressed ctrl + space bar icon appears, but I can continue working

**Comment by rafaelthca** [comment]
Thanks @erdusa, I found that yesterday. The column autocomplete changes the mouse icon. Will fix that.

**Comment by erdusa** [comment]
No problem

**Comment by erdusa** [comment]
Hello @wind39 I have not had problems with this again, I think this problem has been solved, thank you, I close it.
