### ISSUE TITLE
Has the 2.6 release been re-packed

### ISSUE THREAD

**Issue by madflow** [OmniDB/OmniDB#442]
Hi!

I package omnidb for arch linux.

* https://aur.archlinux.org/packages/omnidb-app/
* https://aur.archlinux.org/packages/omnidb-server/

After packaging on March 15 - users commented, that the checksums of the downloaded .deb files have changed. I kept the old files - and this seems to be correct.

So my question: Where the .deb files re-packed and released again with the same release version and date?

This can easily be an error on my end...

**Comment by wind39** [comment]
Hi @madflow ,

First of all, thank you so much for maintaining OmniDB packages in Arch Linux.

We've been optimizing packaging process and removing unnecessary stuff. I re-created all building and testing virtual machines from scratch. Indeed I rebuilt packages for Linux in the new stack, completely unaware it would cause checksum issues in your end.

Sorry for the inconvenient it caused. It won't happen again.

Regards,
William Ivanski

**Comment by madflow** [comment]
Thanks for the info! My concern was not so much that any inconvenience was caused. I wanted to make sure that you guys changed the files and not any international spook or The First Order... Closing...
