### ISSUE TITLE
Additional line breaks in csv files exported

### ISSUE THREAD

**Issue by erdusa** [OmniDB/OmniDB#445]
When the results are exported to a csv file, OmniDB generates additional line breaks, as you can see in this image:
![image](https://user-images.githubusercontent.com/36895220/38198315-e133c57c-3651-11e8-9031-368df3e15558.png)

**Comment by wind39** [comment]
Hi @erdusa ,

Thanks for reporting this. Are you on Windows? There is a similar issue: #434 .

Regards,
William Ivanski

**Comment by erdusa** [comment]
Yes, I am in Windows 10

Thanks

**Comment by wind39** [comment]
Hi @erdusa ,

We just released 2.7.0 with a fix for this. Can you please try it? We are keeping this open for a while, any feedback is welcome!

Thanks and regards,
William Ivanski

**Comment by erdusa** [comment]
Hi @wind39 

Excellent, it proved and approved :)

Thanks

**Comment by wind39** [comment]
Thanks for your feedback, closing it now :)
