### ISSUE TITLE
oracle connection

### ISSUE THREAD

**Issue by mjanota** [OmniDB/OmniDB#469]
After upgrade to 2.6 version. Oracle connections stop working.
Program couldn't find libclntsh.so

Ubuntu 17.10 64bit

Thanks

**Comment by wind39** [comment]
Hi @mjanota ,

Thanks for reaching out. Please get Oracle Instant Client from [here](http://www.oracle.com/technetwork/topics/linuxsoft-082809.html) and extract it into `/opt/omnidb-server` or `/opt/omnidb-app` folder (depending on whether you are using app or server).

Regards,
William Ivanski

**Comment by wind39** [comment]
Hi @mjanota ,

Thanks for your reply. I'm closing this issue, then.

Regards,
William Ivanski
