### ISSUE TITLE
help...

### ISSUE THREAD

**Issue by usri1306** [OmniDB/OmniDB#473]
Error while trying to retrieve text for error ORA-01804 (ubuntu 14.04)

**Comment by wind39** [comment]
Hi @usri1306 ,

We need some more information in order to understand better the issue. Can you please answer the questions below?

- What is the OmniDB version you are using? Is it app or server?
- What is the Oracle version you are using?
- When does this error happen? What were you doing in OmniDB when you first saw this?
- Can you paste a screenshot of this error?

Thanks in advance.

Regards,
William Ivanski

**Comment by usri1306** [comment]
![ommni server 2 6](https://user-images.githubusercontent.com/38283391/38653125-5801c4fe-3e33-11e8-8ba7-19f385b58bde.jpg)

--> omnidb-server_2.6.0-debian-amd64.deb

**Comment by pgaro** [comment]
I just updated and got a similar issue. Where does omnidb read the library paths from? I noticed that $ORACLE_HOME and $LD_LIBRARY_PATH do not suffice anymore.
I get
"DPI-1047: 64-bit Oracle Client library cannot be loaded: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help"
unless I start the app where the libary is located (as basedir) in which case I get "Error while trying to retrieve text for error ORA-01804". It looks to me like the client isn't fully loaded in that case as well.

Regards
pgaro

**Comment by rafaelthca** [comment]
@pgaro,

We changed the way OmnIDB is started because of other issues, LD_LIBRARY_PATH is not being used. Please extract OIC in OmniDB's folder, as explained in the docs:

https://omnidb.org/en/documentation-en/installation (OmniDB with Oracle)

**Comment by pgaro** [comment]
@rafaelthca Thank you! I probably misunderstood the part of "If you already have an Oracle Instant Client installed and loaded into your lib path, then OmniDB will be able to use it, and you will not need to download it and extract it into a specific folder again."
You probably should either fix my flawed way of thinking or the documentation. ;)

**Comment by rafaelthca** [comment]
It is actually an error in the documentation, you didn't misunderstand it. I am fixing it now, thank you for pointing that out.

Rafael.

**Comment by wind39** [comment]
Hi @usri1306 ,

Kindly checking if, with latest release, you are still facing the same issue.

Regards,
William Ivanski

**Comment by wind39** [comment]
I'm closing this issue now.

**Comment by mohammadva** [comment]
I have a same issue:

OS: CentOS 7.6
DB: Oracle 18c XE
OMNIDB: 2.17.0

[root@myserver opt]# cp /opt/oracle/product/18c/dbhomeXE/lib/libclntsh.so* /opt/omnidb-server/

[root@myserver opt]# echo $LD_LIBRARY_PATH  
/opt/oracle/product/18c/dbhomeXE/lib:/lib:/usr/lib

![image](https://user-images.githubusercontent.com/19368703/76711566-8f5ee300-6726-11ea-9a64-10687fb6e87e.png)
