### ISSUE TITLE
Postgresql 10 partitioned tables not visible in browser or \dt

### ISSUE THREAD

**Issue by henriavelabarbe** [OmniDB/OmniDB#477]
Hi,
Omnidb (2.6 and 2.7) doesn't list the Postgresql 10 partitioned tables on my environment.

Neither in the object browser or the console using \dt.

Here is the output from psql :

```
XXXX:[local]:5433 priv@priv=> \dt rw_colo*
             List of relations
 Schema |       Name       | Type  | Owner
--------+------------------+-------+-------
 priv   | rw_colonne       | table | priv
 priv   | rw_colonne_p1998 | table | priv
 priv   | rw_colonne_p1999 | table | priv
 priv   | rw_colonne_p2000 | table | priv
 priv   | rw_colonne_p2001 | table | priv
 priv   | rw_colonne_p2002 | table | priv
 priv   | rw_colonne_p2003 | table | priv
 priv   | rw_colonne_p2004 | table | priv
 priv   | rw_colonne_p2005 | table | priv
 priv   | rw_colonne_p2006 | table | priv
 priv   | rw_colonne_p2007 | table | priv
 priv   | rw_colonne_p2008 | table | priv
 priv   | rw_colonne_p2009 | table | priv
 priv   | rw_colonne_p2010 | table | priv
 priv   | rw_colonne_p2011 | table | priv
 priv   | rw_colonne_p2012 | table | priv
 priv   | rw_colonne_p2013 | table | priv
 priv   | rw_colonne_p2014 | table | priv
 priv   | rw_colonne_p2015 | table | priv
 priv   | rw_colonne_p2016 | table | priv
 priv   | rw_colonne_p2017 | table | priv
 priv   | rw_colonne_p2018 | table | priv
 priv   | rw_colonne_p2019 | table | priv
 priv   | rw_colonne_p2020 | table | priv
 priv   | rw_colonne_p2021 | table | priv
 priv   | rw_colonne_p2022 | table | priv
(26 rows)
```

And from omnidb console :

```
>> \dt rw_colo*
+--------+------------------+-------+-------+
| Schema | Name             | Type  | Owner |
+--------+------------------+-------+-------+
| priv   | rw_colonne_p1998 | table | priv  |
| priv   | rw_colonne_p1999 | table | priv  |
| priv   | rw_colonne_p2000 | table | priv  |
| priv   | rw_colonne_p2001 | table | priv  |
| priv   | rw_colonne_p2002 | table | priv  |
| priv   | rw_colonne_p2003 | table | priv  |
| priv   | rw_colonne_p2004 | table | priv  |
| priv   | rw_colonne_p2005 | table | priv  |
| priv   | rw_colonne_p2006 | table | priv  |
| priv   | rw_colonne_p2007 | table | priv  |
| priv   | rw_colonne_p2008 | table | priv  |
| priv   | rw_colonne_p2009 | table | priv  |
| priv   | rw_colonne_p2010 | table | priv  |
| priv   | rw_colonne_p2011 | table | priv  |
| priv   | rw_colonne_p2012 | table | priv  |
| priv   | rw_colonne_p2013 | table | priv  |
| priv   | rw_colonne_p2014 | table | priv  |
| priv   | rw_colonne_p2015 | table | priv  |
| priv   | rw_colonne_p2016 | table | priv  |
| priv   | rw_colonne_p2017 | table | priv  |
| priv   | rw_colonne_p2018 | table | priv  |
| priv   | rw_colonne_p2019 | table | priv  |
| priv   | rw_colonne_p2020 | table | priv  |
| priv   | rw_colonne_p2021 | table | priv  |
| priv   | rw_colonne_p2022 | table | priv  |
+--------+------------------+-------+-------+
SELECT 25
```

I think part of the issue is in PostgreSQL.py and dbcommands.py :

```
    def QueryTables(self, p_all_schemas=False, p_schema=None):
        v_filter = ''
        if not p_all_schemas:
            if p_schema:
                v_filter = "and quote_ident(t.table_schema) = '{0}' ".format(p_schema)
            else:
                v_filter = "and quote_ident(t.table_schema) = '{0}' ".format(self.v_schema)
        else:
            v_filter = "and quote_ident(t.table_schema) not in ('information_schema','pg_catalog') "
        if int(self.v_connection.ExecuteScalar('show server_version_num')) < 100000:
            return self.v_connection.Query('''
                select quote_ident(t.table_name) as table_name,
                       quote_ident(t.table_schema) as table_schema
                from information_schema.tables t
                where t.table_type = 'BASE TABLE'
                {0}
                order by 2, 1
            '''.format(v_filter), True)
        else:
            return self.v_connection.Query('''
                select quote_ident(t.table_name) as table_name,
                       quote_ident(t.table_schema) as table_schema
                from information_schema.tables t
                inner join pg_class c
                on c.relname = t.table_name
                inner join pg_namespace n
                on n.oid = c.relnamespace
                and n.nspname = t.table_schema
                where t.table_type = 'BASE TABLE'
                  and not c.relispartition
                  and c.relkind = 'r'
                {0}
                order by 2, 1
            '''.format(v_filter), True)
```

Query from psql is :

```
SELECT n.nspname as "Schema",
  c.relname as "Name",
  CASE c.relkind WHEN 'r' THEN 'table' WHEN 'v' THEN 'view' WHEN 'm' THEN 'materialized view' WHEN 'i' THEN 'index' WHEN 'S' THEN 'sequence' WHEN 's' THEN 'special' WHEN 'f' THEN 'foreign table' WHEN 'p' THEN 'table' END as "Type",
  pg_catalog.pg_get_userbyid(c.relowner) as "Owner"
FROM pg_catalog.pg_class c
     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind IN ('r','p','s','')
      AND n.nspname !~ '^pg_toast'
  AND c.relname ~ '^(rw_colo.*)$'
  AND pg_catalog.pg_table_is_visible(c.oid)
ORDER BY 1,2;
```

I tought it could be fixed by changing PostgreSQL.py :
```
    def QueryTables(self, p_all_schemas=False, p_schema=None):
        v_filter = ''
        if not p_all_schemas:
            if p_schema:
                v_filter = "and quote_ident(t.table_schema) = '{0}' ".format(p_schema)
            else:
                v_filter = "and quote_ident(t.table_schema) = '{0}' ".format(self.v_schema)
        else:
            v_filter = "and quote_ident(t.table_schema) not in ('information_schema','pg_catalog') "
        if int(self.v_connection.ExecuteScalar('show server_version_num')) < 100000:
            return self.v_connection.Query('''
                select quote_ident(t.table_name) as table_name,
                       quote_ident(t.table_schema) as table_schema
                from information_schema.tables t
                where t.table_type = 'BASE TABLE'
                {0}
                order by 2, 1
            '''.format(v_filter), True)
        else:
            return self.v_connection.Query('''
                select quote_ident(t.table_name) as table_name,
                       quote_ident(t.table_schema) as table_schema
                from information_schema.tables t
                inner join pg_class c
                on c.relname = t.table_name
                inner join pg_namespace n
                on n.oid = c.relnamespace
                and n.nspname = t.table_schema
                where t.table_type = 'BASE TABLE'
                  and not c.relispartition
                  and c.relkind in ('r', 'p')
                {0}
                order by 2, 1
            '''.format(v_filter), True)
```

The sql result seems fine, but the app still doesn't display the top partitioned table.

For the console, I also tried to fix by adjusting some class types and sql queries but couldn't get the right result.

Ok, it seems editing the python file in the application directory is not enough as even with syntax errors the application is still able to run.

Could you tell me if it is possible to test python code changes in the bundled app ?

Regards,
Henri

**Comment by kxjhlele** [comment]
me too

**Comment by henriavelabarbe** [comment]
Some update: 
The browser issue solved by using the source code from git repo and modifying
```
                  and c.relkind in ('r', 'p')
```
in the function mentioned eralier.

There is also a missing dependencies from click python module coming from spartacus.

**Comment by wind39** [comment]
Hi @henriavelabarbe ,

Thanks for reporting this in details and also thank you for your contribution, I already accepted your PR. But it has some problems I'll explain below:

1) You committed `and c.relkind = ('r', 'p')` and it should be `and c.relkind in ('r', 'p')`. I fixed it in your PR :)

2) I removed `and not c.relispartition` from the PR (it was this way before), otherwise partitions would not be shown in the table list.

3) You did a PR for the `master` branch, but we develop in `dev` branch. On the day of the release, we copy dev to master. Of course you didn't know that because we didn't write a Contributing Guidelines document yet, we are working on it :)

On the dev branch, I just started a much wider implementation to support declarative partitioning for PostgreSQL 10 (you can see [the commit](https://github.com/OmniDB/OmniDB/pull/479/commits/4262272163f60e937373866e24cceca74e944446)). The idea is that PG10 supports partitioning by inherited tables (as in older versions), but also supports a new declarative approach. So if PG version is 10 or higher, OmniDB will show 2 nodes, as you can see in the image below.

![image](https://user-images.githubusercontent.com/7719686/38744704-e1980eea-3f18-11e8-960b-a42fa564eeaf.png)

This implementation is still a WIP, for example it still lacks unit tests. It will be published with the next release, 2.8, which will be out in a month (May, 17th). Please feel free to provide any feedback :)

Thanks and regards,
William Ivanski

**Comment by henriavelabarbe** [comment]
Hi thanks for the explanation, sorry I wrongly modified the code, my first contribution was not very efficient..
Anyway, thanks for your software, I'll try to contribute again.

Just one question : why not only display the base table in the table browser as there is already a partition subnode?
We have a DB with 30 partitions per table for a set of 5 tables and it makes the table list quite long.

Regards,
Henri

⁣Envoyé par BlueMail ​

Le 13 avr. 2018 à 17:57, à 17:57, William Ivanski <notifications@github.com> a écrit:

**Comment by wind39** [comment]
Hi @henriavelabarbe ,

Thanks for your response. There are 2 reasons for displaying all tables (including inherited tables and partitions) in the full table list:

1) You can only see and manage PKs, FKs, indexes, etc of a inherited table or partition if it is in the regular table list of the treeview.

2) In PG10, you can have partitions and subpartitions, and this recursive approach is not yet implemented in the treeview.

Removing limitations 1) and 2) is foreseen for next versions and we should implement it very soon. I'll let you know about it :)

Regards,
William Ivanski

**Comment by l-we** [comment]
OmniDB 2.10.0
not 2）

**Comment by wind39** [comment]
Hi @l-we ,

Thanks for your feedback. We are currently on OmniDB 2.11.0 and we were not able to implement the recursive approach yet. We will try and tackle this soon, I'll keep you informed in this thread.

Regards,

William Ivanski

**Comment by wind39** [comment]
The main issue here was already solved, partitioned tables can be seen in the treeview and also in `\dt`. The implementation of showing the partitioned tables recursively in the treeview is being handled in issue #842 .
