### ISSUE TITLE
version 2.7 font problems with fedora 28

### ISSUE THREAD

**Issue by volkmarbuehringer** [OmniDB/OmniDB#481]
starting omnidb-app with fedora 28 delivers some fontconfig -errors

afterwards it works correctly but the fonts are odd

**Comment by wind39** [comment]
Hi @volkmarbuehringer ,

We improved the app version and many issues were fixed, including font issues for newer Linux versions, such as Fedora 28 and Ubuntu 18.04.

The improved app version will be released in 2.8, which will come out in May, 17th. Please stay tuned!

Regards,
William

**Comment by wind39** [comment]
As we didn't receive any feedback, I'm closing this issue now.
