### ISSUE TITLE
Browsing MySQL 5.7.20 tree gives error

### ISSUE THREAD

**Issue by codepope** [OmniDB/OmniDB#485]
Browsing a MySQL 5.7.20 instance (on compose.com) we can connect and descend the tree this far...

![image](https://user-images.githubusercontent.com/72684/39240609-3784ef82-487c-11e8-9e6f-207ee6067669.png)

but no deeper. On attempting to expand a table node we get:

![image](https://user-images.githubusercontent.com/72684/39240638-4fa1685c-487c-11e8-9c81-6788c4582e90.png)

"(3065, "Expression #2 of ORDER BY clause is not in SELECT list, references column 'information_schema.c.ORDINAL_POSITION' which is not in SELECT list; this is incompatible with DISTINCT")"

Unsure what the actual error is, but would suggest making error messages wrap anyway.

**Comment by rafaelthca** [comment]
Hi @codepope,

I was able to reproduce the issue. It happens in some specific situations for version 5.7. The fix will come in the next release, on May 17.

Feel free to suggest features you would like to see in terms of MySQL management.

**Comment by wind39** [comment]
Hi @codepope ,

We fixed this in 2.8, which we just published. Can you please try? We will keep this issue open for a few more days in case you want to give us your valuable feedback.

Thanks and regards,
William Ivanski

**Comment by kpion** [comment]
Hi, I just want to confirm that there was the bug, and now there isn't :) I.e. the 2.9 version works fine.

Thanks for the app! Seems pretty cool.

**Comment by wind39** [comment]
Hi @kpion ,

Thanks very much for your feedback! I'm closing this issue now.

Regards,
William Ivanski
