### ISSUE TITLE
ORA-12170

### ISSUE THREAD

**Issue by pgaro** [OmniDB/OmniDB#513]
When connecting to a specific oracle database I get

> ORA-12170: TNS:Connect timeout occurred 

while other databases works fine. However this appears to be an omni-db specific problem since my other applications connect to that database without hassle.

Regards
pgaro

**Comment by wind39** [comment]
Hi @pgaro ,

Thanks for reaching out. Please let us know more details so we can better understand the issue.

1) At the moment OmniDB connects to Oracle by using the notation `user/pwd@host:port/service`. For the release 2.8 we will improve this by also allowing the notation `user/pwd@service` if the user leaves host and port empty. This notation will allow users to connect to Oracle using client-side `tnsnames.ora` and `sqlnet.ora` files. So, how do other applications connect to that database?

2) For this specific database, by any chance do you have in `sqlnet.ora`, server side, specific values for `SQLNET.INBOUND_CONNECT_TIMEOUT`, `SQLNET.SEND_TIMEOUT` and/or `SQLNET.RECV_TIMEOUT`?

Regards,
William Ivanski

**Comment by pgaro** [comment]
I always connect with user, host, port and ssid (and pwd ofc, while I type that into omnidb when I connect). I don't have client side tnsnames.ora and sqlnet.ora files on the specific machine.
The specific database has "SQLNET.INBOUND_CONNECT_TIMEOUT =180" set in the sqlnet.ora, while that should be plenty in normal circumstances, shouldn't it? This is the first application that seems to be bothered.

Regards
pgaro

**Comment by pgaro** [comment]
@wind39: I copied the connection data to the server version and the issue doesn't seem to persist.
As you can guess, it's not a serious issue anymore. It's non the less surprising.

Regards
pgaro

**Comment by wind39** [comment]
Hi @pgaro ,

Thanks for your response. Interesting, I will dig into it some more and I will let you know about my findings here.

Regards,
William Ivanski

**Comment by pgaro** [comment]
@wind39: I just installed the app again on a different machine for testing purposes and it works fine there. So it does seem to be tied to that specific installation rather than the app/server difference. I'll let you know if I'm able to dig up anything meaningful. I'm closing this in the meantime.

Regards
pgaro

**Comment by amolrn** [comment]
Hello 

I am having issues connecting OMNIDB via tnsnames.ora file

My omniDB version is 2.14, i have a 12.2 instant client have have placed the tnsnames and sqlnet under network/admin folder

when i don't give the host and port and just give Database field as the connect descriptor i get an error like
ORA-12154: TNS:could not resolve the connect identifier specified

Any help is highly appreciated.
