### ISSUE TITLE
Server version rpm

### ISSUE THREAD

**Issue by pgaro** [OmniDB/OmniDB#522]
I tried to install the server version of omnidb (admittedly not on Fedora/centos).
Rpm returned
error: unpacking of archive failed on file /opt/omnidb-server/libbz2.so.1;5aeb168a: cpio: Digest mismatch
error: omnidb-server-2.7.0-0.x86_64: install failed

Why is there bzip2 included? libbz2.so.1is something my system ofc has anyways.

Regards
pgaro

**Comment by wind39** [comment]
Hi @pgaro ,

Thanks for reporting this. This is a known issue. I've improved deployment for 2.8, so it won't happen anymore.

For now, please try installing like this, for example:

```
rpm -ivU --nofiledigest omnidb-server_2.7.0-centos-amd64.rpm
```

Or:

```
rpm -ivU --nofiledigest omnidb-server_2.7.0-fedora-amd64.rpm
```

Regards,
William Ivanski

**Comment by wind39** [comment]
Hi @pmpetit ,

Thanks for reporting this. Yes, it didn't work as I expected so for 2.8 you still need to use the `--nofiledigest` to install `omnidb-server`.

Problem is that server is built using CentOS 6 and we still want to allow users to install omnidb-server on CentOS 6. For 2.9, I will also build omnidb-server on CentOS 7 too. So there will be 2 versions of the server package: one with suffix `-centos6` and another with suffix `-centos7`. Then in your case, if you use the new `-centos7` version, the `Digest mismatch` erros won't appear.

We are open to feedback on this workaround and also for other ideas on how to handle this. Thanks!

Regards,
William Ivanski

**Comment by wind39** [comment]
Hi @pmpetit ,

Starting from release 2.9, there are different packages for CentOS 6 and CentOS 7. Can you please try again to see if the error still persists?

Thanks in advance,
William Ivanski

**Comment by pmpetit** [comment]
Hello,
thanks for that.

It is ok  now, you can close.

**Comment by wind39** [comment]
Hi @pmpetit , @pgaro ,

Thanks for your response. I'm closing this case now.

Regards,
William Ivanski
