### ISSUE TITLE
Cannot edit JSONB

### ISSUE THREAD

**Issue by cschwaderer** [OmniDB/OmniDB#523]
Right click on a table with some JSONB column -> "Edit data"
Change something in the JSONB column
Save
-> Error:

> Command: update public.my_table set my_column = [{"foo":"dahoo"}] where id = 2323324
> 
> Message:
> syntax error at or near "["
> LINE 1: ... public.my_table set my_column = [{"foo":"..

I think, there is a ' missing. It should be:
`update public.my_table set my_column = '[{"foo":"dahoo"}]' where id = 2323324`

**Comment by rafaelthca** [comment]
Fixed this. Coming out with 2.8 next week.

**Comment by wind39** [comment]
Hi @cschwaderer ,

We fixed this in 2.8, which we just published. Can you please try? We will keep this open for a few more days in case you want to give us your valuable feedback.

Thanks and regards,
William Ivanski

**Comment by cschwaderer** [comment]
Works! Thanks!
