### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by pgaro** [OmniDB/OmniDB#524]
I can't get auto completion to work in any scenario. Neither in console mode nor in query mode.
![pgaro_screenshot](https://user-images.githubusercontent.com/38760999/39699461-9989d82e-51f9-11e8-8e8c-c319a6f2b8ba.jpg)
What am I doing wrong?

Is there a way to print tabulators instead of spaces?

**Comment by wind39** [comment]
Hi @pgaro ,

Thanks for reaching out. A couple of questions:

1) Is `pgaro` a table?
2) How are you issuing autocompletion keyboard shortcut, which is Ctrl-Space. You need to type this beside a table alias, like the picture below:

![image](https://user-images.githubusercontent.com/7719686/39701137-4ff53c3a-51d6-11e8-8535-b588a0641200.png)

Regards,
William Ivanski

**Comment by wind39** [comment]
Hi @pgaro ,

This part of documentation is outdated, we are working on improving this.

Short term plans will allow table name autocompletion if the user types a schema (like in PostgreSQL) or user name (like in Oracle) before typing `Ctrl-Space`. Also if the user types `Ctrl-Space` in a blank space, it will show all schemas in PostgreSQL. But this is not implemented yet, we should implement it soon.

Longer term plans include implementation of SQL autocompletion, like the one we have in `psql`, as you suggested.

Regards,
William Ivanski

**Comment by pgaro** [comment]
Thank you for the quick reply, I'm happy to hear about this - thank you for your work!

Regards
pgaro
