### ISSUE TITLE
feature: create connection for multiple users

### ISSUE THREAD

**Issue by pgaro** [OmniDB/OmniDB#525]
Adding a database connection to every user in the system can be very complicated, if every user need to add the connections himself/herself.
It would be helpful if superusers could also add connections to multiple users at once.

Is there a way to make the connection pop-up taller to see more connections at once?

Regards pgaro

**Comment by rafaelthca** [comment]
> It would be helpful if superusers could also add connections to multiple users at once.

Great idea. Adding it to our roadmap.

> Is there a way to make the connection pop-up taller to see more connections at once?

Yes, this will be improved in the next release.

Thanks @pgaro

**Comment by luolenny** [comment]
May I know where is the roadmap?

**Comment by wind39** [comment]
Hi @lennyluosz ,

The roadmap can be found here: https://github.com/orgs/OmniDB/projects/3

Regards,

William

**Comment by lennyluosz** [comment]
Thanks a lot

**Comment by felipebiox** [comment]
Hello,

This feature has been implemented and is now available on OmniDB 3.

I'm now closing this ticket.

Best regards
