### ISSUE TITLE
Shortcut for Copy in sql editor not wroking nor Right Click

### ISSUE THREAD

**Issue by heejit** [OmniDB/OmniDB#547]
In Sql editor shortcut for copy (Ctrl+c) and right click pop menu not working 

I am running omnidb as desktop application in ubuntu 16.04 64bit

I dont know is this a bug or some configuration issue

**Comment by wind39** [comment]
Hi @heejit ,

You are right that on the app version the right click inside the editor is disabled. We will include this for the next version. On the server version, you are able to use the right click menu provided by the browser.

I tested the app version here in an Ubuntu 16.04 LTS 64-bit virtual machine and I found no problems using Ctrl-C, Ctrl-X and Ctrl-V:

![image](https://user-images.githubusercontent.com/7719686/40242613-784eaa6a-5a94-11e8-90fa-1981a2425d8f.png)

OmniDB allows you to configure shortcuts. Do you have a shortcut set for Ctrl-C?

![image](https://user-images.githubusercontent.com/7719686/40242712-b83c95ce-5a94-11e8-9605-8bb24523f772.png)

Regards,
William Ivanski

**Comment by heejit** [comment]
no shortcut with ctrl+c

**Comment by rafaelthca** [comment]
That is very strange. Can you do some tests for us?

1- Can you confirm that ctrl-c / ctrl-x / ctrl-v is working outside of OmniDB?
2- Can you try to paste (Ctrl-v) in OmniDB's editor something that was copied from another app? Firefox, chrome, anything.
3- Can you try to paste in another editor something that was copied (that you tried to copy with Ctrl-c) from OmniDB's interface?

Rafael.

**Comment by heejit** [comment]
1- Can you confirm that ctrl-c / ctrl-x / ctrl-v is working outside of OmniDB?
Yes

2- Can you try to paste (Ctrl-v) in OmniDB's editor something that was copied from another app? Firefox, chrome, anything.
Ctrl + v is working

3- Can you try to paste in another editor something that was copied (that you tried to copy with Ctrl-c) from OmniDB's interface?
Pressing Ctrl+c not copying anything

**Comment by wind39** [comment]
Hi @heejit ,

Does Ctrl-x work on OmniDB?

Also, what is the graphical environment you use on Ubuntu?

**Comment by heejit** [comment]
Ctrl+x work as expected

graphical env - Xfce

**Comment by heejit** [comment]
till ctrl+c added ctrl+x will be helpfull

**Comment by wind39** [comment]
Hi @heejit ,

We were not able to simulate your issue. However, since we last spoke, many improvements were made to the interface. Can you please try again to see if all shortcuts work as expected?

Best regards,

William

**Comment by heejit** [comment]
shortcut are working fine  thanks

**Comment by wind39** [comment]
Thanks for your feedback. Closing this.
