### ISSUE TITLE
Error when using psql commands in a console tab in PostgreSQL 9.5

### ISSUE THREAD

**Issue by erdusa** [OmniDB/OmniDB#550]
Hi, when I try to do the \d command or another command in a console tab I get the next error:

![image](https://user-images.githubusercontent.com/36895220/40308484-0f3d7d78-5ccc-11e8-9823-cfbf05ca5f2b.png)

**Comment by erdusa** [comment]
Hi @wind39, no problem, the PostgreSQL version is 9.5

**Comment by erdusa** [comment]
Hi @wind39, now I saw that the problema is not with a standby servers, the problem is in 9.5 because I have PostgreSQL 10 in other server and it works well

**Comment by wind39** [comment]
Thank you, @erdusa ,

I was able to simulate the issue here. Indeed it works on PG 10 only. I fixed this bug, the fix will be released in the next version (2.9) in June, 14th.

Regards,
William Ivanski

**Comment by erdusa** [comment]
Hi @wind39, I can see this problem was solved in 2.9.0, thanks
