### ISSUE TITLE
Query Server is not Response after cancel Long Query

### ISSUE THREAD

**Issue by vinhduy11** [OmniDB/OmniDB#556]
When using OmniDB, I faced issue about Query Server is not reponse. When I checked it, I found it shutdown unexpected. I tried to find out what happen but can't find anything to troubleshoot.

How can I troubleshoot when Query Server is not responsive?

Thank you

**Comment by rafaelthca** [comment]
Hi @vinhduy11,

Are you using latest version (2.8)? Server or app? What OS?

Another question, the query server stopped working after you tried to cancel that specific query? Was it a long query in terms of duration or in terms of the amount of data being returned?

Rafael.

**Comment by vinhduy11** [comment]
Thank you for your reply.

> Are you using latest version (2.8)
Yes

> Server or app
Server

> What OS?
CentOS release 6.9 (Final) x86_64

> Another question, the query server stopped working after you tried to cancel that specific query?
I faced two issue:
- One, the query server automatically closes whether or not to cancel the query
- Two, when I uses long query and want to cancel. The query server stopped without any error log.

>Was it a long query in terms of duration or in terms of the amount of data being returned?
Both of case.

>How do you know that the query server shutdown unexpectedly?
I checked by telnet to server port and process.

Thank for help.
Duy Dinh

**Comment by rafaelthca** [comment]
Thanks.

That is very odd. Can you replicate this? I mean, does it stop working all the time?

Is there a specific query that crashes it? Also, were you using omnidb-server alone or were there more people connected to it?

OmniDB contains 2 servers, one serves the page/ajax requests (uses port 8000 by default) and the other, the query server, serves websocket requests (uses port 25482 by default). Can you confirm that it is the websocket server that crashes? Notice that there is only one process for both servers, the websocket server is started in a parallel thread and should be crash safe. You can use netstat to check if the websocket port is active or not.

If you confirm that the websocket server is really crashing, can you please check the logs in `~/.omnidb/omnidb-server/omnidb.log` to see if there any reported error? If not, I will ask you to try to stop omnidb-server and start it in the foreground, so you can see the messages being showed in the console, and then try to replicate the issue again.

Thank you again for reporting, if we indeed find a bug there (which would be a critical bug) I will work on a fix for the next release that will come out in around 2 weeks.

Rafael.

**Comment by vinhduy11** [comment]
Yed it does. Same one query, when I use oracle client, it shows me the result after some minutes but Omni can't. I checked it with telnet and curl and found the query server is stopped unexpectedly.

>Also, were you using omnidb-server alone or were there more people connected to it?

Yes there were more people connect to it with their seperate account.


The webserver was fine but the query server stopped.

The logs only show about query history and startup history log. I couldn't find any log about python 's exceptions or os crash. That's weird.

I still try find to anything else for helping investigate the bug.

Thanks you very much
Duy

**Comment by wind39** [comment]
Hi @vinhduy11 ,

We have provided some improvements in version 2.9. Can you please try it and provide your valuable feedback? Thanks very much in advance!

Regards,
William Ivanski

**Comment by rafaelthca** [comment]
Hi again @vinhduy11, sorry for taking too long to respond, busy with development.

I am concerned with the issue you described, I've never seen tornado crashing without generating an exception. You mentioned you are able to reproduce the issue, can you do the following:

1- start omnidb-server in the foreground (and keep the terminal running to see everything that is printed there.
2- check if ports for webserver and query server are being used with `netstat -tulpn`
3- perform the steps to reproduce the issue and check if an exception is printed in the terminal. (I am looking for an unhandled exception that is not being logged.
4- check again the ports with `netstat -tulpn`

Thanks.

Rafael.

**Comment by vinhduy11** [comment]
Hi all,

Thank for your recommend. I found some error when started Omni in foreground.

The error code is: 96048 Segmentation fault. But I couldn't find anything log about the error happened.

Thanks
Duy

**Comment by rafaelthca** [comment]
Can you share the full console output? Also, what was the sequence of steps on the interface to reproduce that?

Thanks.

**Comment by rafaelthca** [comment]
The asynchronous websocket server sends query output in chunks to avoid being unresponsive to other requests.

I'm closing this issue @vinhduy11. Feel free to open it once you are able to reproduce the segmentation fault again.

Rafael.
