### ISSUE TITLE
Error starting omnidb-server on SLES12sp3

### ISSUE THREAD

**Issue by LucianoMittmann** [OmniDB/OmniDB#558]
Trying to start Omni Server but having following message:
------------------------------------------------------------------------------------------------------------------------------
root@75138:/usr/src/OmniDB/OmniDB# python omnidb-server.py 
  File "omnidb-server.py", line 59
    print("Home directory does not exist. Please specify a directory that exists.",flush=True)
                                                                                        ^
SyntaxError: invalid syntax
------------------------------------------------------------------------------------------------------------------------------
Requirements installation:
root@75138:/usr/src/OmniDB# pip install -r requirements.txt
Requirement already satisfied: Django>=1.10 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (1.11.13)
Requirement already satisfied: cherrypy in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 2)) (15.0.0)
Requirement already satisfied: tornado==4.5.1 in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 3)) (4.5.1)
Requirement already satisfied: click in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 4)) (6.7)
Requirement already satisfied: sqlparse>=0.2.3 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 5)) (0.2.4)
Requirement already satisfied: psycopg2-binary in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 6)) (2.7.4)
Requirement already satisfied: pyscrypt in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 7)) (1.6.2)
Requirement already satisfied: pyaes in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 8)) (1.6.1)
Requirement already satisfied: openpyxl in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 9)) (2.5.3)
Requirement already satisfied: RestrictedPython>=4.0b2 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 10)) (4.0b4)
Requirement already satisfied: cx_Oracle>=6.1 in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 11)) (6.3.1)
Requirement already satisfied: pymysql in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 12)) (0.8.1)
Requirement already satisfied: sshtunnel in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 13)) (0.1.3)
Requirement already satisfied: pytz in /usr/lib/python2.7/site-packages (from Django>=1.10->-r requirements.txt (line 1)) (2018.4)
Requirement already satisfied: six>=1.11.0 in /usr/lib/python2.7/site-packages (from cherrypy->-r requirements.txt (line 2)) (1.11.0)
Requirement already satisfied: cheroot>=6.2.4 in /usr/lib/python2.7/site-packages (from cherrypy->-r requirements.txt (line 2)) (6.3.1)
Requirement already satisfied: portend>=2.1.1 in /usr/lib/python2.7/site-packages (from cherrypy->-r requirements.txt (line 2)) (2.2)
Requirement already satisfied: certifi in /usr/lib/python2.7/site-packages (from tornado==4.5.1->-r requirements.txt (line 3)) (2018.4.16)
Requirement already satisfied: singledispatch in /usr/lib/python2.7/site-packages (from tornado==4.5.1->-r requirements.txt (line 3)) (3.4.0.3)
Requirement already satisfied: backports-abc>=0.4 in /usr/lib/python2.7/site-packages (from tornado==4.5.1->-r requirements.txt (line 3)) (0.5)
Requirement already satisfied: jdcal in /usr/lib/python2.7/site-packages (from openpyxl->-r requirements.txt (line 9)) (1.4)
Requirement already satisfied: et-xmlfile in /usr/lib/python2.7/site-packages (from openpyxl->-r requirements.txt (line 9)) (1.0.1)
Requirement already satisfied: setuptools in /usr/lib/python2.7/site-packages (from RestrictedPython>=4.0b2->-r requirements.txt (line 10)) (18.0.1)
Requirement already satisfied: paramiko>=1.15.2 in /usr/lib/python2.7/site-packages (from sshtunnel->-r requirements.txt (line 13)) (2.4.1)
Requirement already satisfied: backports.functools-lru-cache in /usr/lib/python2.7/site-packages (from cheroot>=6.2.4->cherrypy->-r requirements.txt (line 2)) (1.5)
Requirement already satisfied: more-itertools>=2.6 in /usr/lib/python2.7/site-packages (from cheroot>=6.2.4->cherrypy->-r requirements.txt (line 2)) (4.2.0)
Requirement already satisfied: tempora>=1.8 in /usr/lib/python2.7/site-packages (from portend>=2.1.1->cherrypy->-r requirements.txt (line 2)) (1.11)
Requirement already satisfied: cryptography>=1.5 in /usr/lib64/python2.7/site-packages (from paramiko>=1.15.2->sshtunnel->-r requirements.txt (line 13)) (2.2.2)
Requirement already satisfied: pynacl>=1.0.1 in /usr/lib64/python2.7/site-packages (from paramiko>=1.15.2->sshtunnel->-r requirements.txt (line 13)) (1.2.1)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/lib/python2.7/site-packages (from paramiko>=1.15.2->sshtunnel->-r requirements.txt (line 13)) (0.1.9)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/lib64/python2.7/site-packages (from paramiko>=1.15.2->sshtunnel->-r requirements.txt (line 13)) (3.1.4)
Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in /usr/lib64/python2.7/site-packages (from cryptography>=1.5->paramiko>=1.15.2->sshtunnel->-r requirements.txt (line 13)) (1.11.5)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/lib/python2.7/site-packages (from cryptography>=1.5->paramiko>=1.15.2->sshtunnel->-r requirements.txt (line 13)) (0.24.0)
Requirement already satisfied: enum34; python_version < "3" in /usr/lib/python2.7/site-packages (from cryptography>=1.5->paramiko>=1.15.2->sshtunnel->-r requirements.txt (line 13)) (1.1.3)
Requirement already satisfied: idna>=2.1 in /usr/lib/python2.7/site-packages (from cryptography>=1.5->paramiko>=1.15.2->sshtunnel->-r requirements.txt (line 13)) (2.6)
Requirement already satisfied: ipaddress; python_version < "3" in /usr/lib/python2.7/site-packages (from cryptography>=1.5->paramiko>=1.15.2->sshtunnel->-r requirements.txt (line 13)) (1.0.14)
Requirement already satisfied: pycparser in /usr/lib/python2.7/site-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.5->paramiko>=1.15.2->sshtunnel->-r requirements.txt (line 13)) (2.10)

Thanks for any help.

**Comment by rafaelthca** [comment]
Hi @LucianoMittmann,

Are you using Python 3? Please use Python 3.4 or greater.

**Comment by LucianoMittmann** [comment]
Thank you @rafaelthca, works fine with  Python 3.4.
