### ISSUE TITLE
Saving dashboard

### ISSUE THREAD

**Issue by pmpetit** [OmniDB/OmniDB#559]
Hello, is there a way to save my own dashboard ?
or do i have to rebuild the whole dashboard each time i open omnidb ?

thanks

**Comment by wind39** [comment]
Hi @pmpetit ,

Thanks for reaching out. Currently the charts you add to the dashboard are not saved. We have this in our roadmap, we should implement this soon. I'll let you know once it is implemented and published.

Regards,
William Ivanski

**Comment by rafaelthca** [comment]
Closing this. Dashboard is saved per connection.

**Comment by pmpetit** [comment]
Great ! 

Thanks a lot....
