### ISSUE TITLE
Add autobuild Docker image to dockerhub

### ISSUE THREAD

**Issue by jalberto** [OmniDB/OmniDB#56]
Will be great ot have an official docker mage in docker hub for easy deployment & development

**Comment by pwelter34** [comment]
docker is the easiest way to install.  please create an official docker image.

**Comment by barthisrael** [comment]
Hi,

We have finally pushed an official image to DockerHub. Find instruction in the below link:

https://hub.docker.com/r/omnidbteam/omnidb

Regards.
