### ISSUE TITLE
Another collection of various suggestions

### ISSUE THREAD

**Issue by gabrielgisoldo** [OmniDB/OmniDB#566]
Dear all! 

I quite liked the omniDB, liked it to the point of being the maintainer for the installation code of it on Linux Slackware, and I am trying to use this as replacement of PGAdmin3.
But, yeah, nothing is perfect and i have some suggestion to, maybe, make it a bit better.

- Saving the query used on the query tab to a file. This is quite useful. At the moment I have to copy-paste the query back and forth between my text editor and omniDB to do this.

- Auto complete is not working on Slackware (but maybe it's the system fault, not the application, but it would be superb if it worked).

- Navigation on the table tree by typing the name of the table.
e.g To get to a table named tests I could just type "t" and it would scroll down to tables with names starting with "t".

- "Year out of range" exception. Sometimes I get this when there's a date like this on the table "0001-01-01 BC". On PGAdmin3 I get exactly this, but on omniDB I simply get "year out of range" and it doesn't show any of the results.
The only way I can get to see and find which row is the one causing the error is using other application (PGAdmin3).

Well, that's it from me.
And thanks for the attention!

**Comment by wind39** [comment]
Hi @gabrielgisoldo ,

Thank you very much for your feedback. It is exciting that you are willing to maintain OmniDB on Slackware. I'm not familiar with Slackware, but please let me know how can I help you on this task. For example, I can get some time to try to run OmniDB on Slackware and help you scripting and testing.

Thanks for your suggestions, they are invaluable. I'll try to reply about each of them.

> Saving the query used on the query tab to a file. This is quite useful. At the moment I have to copy-paste the query back and forth between my text editor and omniDB to do this.

I included this in our roadmap, expanding for an ability to also open a `.sql` file inside a Query Tab.

> Auto complete is not working on Slackware (but maybe it's the system fault, not the application, but it would be superb if it worked).

Can you please provide more details about this? Does it show some error message? Can you get it to work on a different environment?

I will also try to run it on Slackware, but I can't promise you I'll do this before our next release (next 14th of June).

> Navigation on the table tree by typing the name of the table.
e.g To get to a table named tests I could just type "t" and it would scroll down to tables with names starting with "t".

That's a great idea. We have a Filter feature for tree view elements in our roadmap, planned to be implemented soon.

> "Year out of range" exception. Sometimes I get this when there's a date like this on the table "0001-01-01 BC". On PGAdmin3 I get exactly this, but on omniDB I simply get "year out of range" and it doesn't show any of the results.
> The only way I can get to see and find which row is the one causing the error is using other application (PGAdmin3).

I have already seen this, but what I do to see the value of such fields is to explicitly cast it to text with `::text`, for example. I'll try to dig into it and I'll let you know.

Regards,
William Ivanski

**Comment by gabrielgisoldo** [comment]
Hi @wind39 ,

> Can you please provide more details about this? Does it show some error message? Can you get it to work on a different environment?
I will also try to run it on Slackware, but I can't promise you I'll do this before our next release (next 14th of June).

Reading other issues open a found why it wasn't working. The problem was in the documentation on the site.
There, it's written you just need to type the alias and the dot character to open the auto-complete, but on the other issue your answer solved my problem too.

> I have already seen this, but what I do to see the value of such fields is to explicitly cast it to text with ::text, for example. I'll try to dig into it and I'll let you know.

Thanks for this tip, I'll be using this from now on too.

Best Regards,
Gabriel

**Comment by wind39** [comment]
Hi @gabrielgisoldo ,

It is been a while, but I'm here just to inform you that I fixed the issue with the dates:

![image](https://user-images.githubusercontent.com/7719686/53176841-a4be1800-35cd-11e9-9266-ffd6232274d7.png)

It will be released in OmniDB 2.15, going out in April this year.

As per your list of requests, the only remaining item is to save a query to a `.sql` file, which is being handled in issue #480 .

Best regards,

William

**Comment by wind39** [comment]
Hi @gabrielgisoldo ,

We just released OmniDB 2.15, containing most of your requests in this ticket. The ability to save a query to a `.sql` file is being handled in #480 .

Can you please download 2.15 and try it? Your valuable feedback will be much appreciated, as always.

Regards,

William

**Comment by gabrielgisoldo** [comment]
Hi @wind39 ,

Just installed here and everything is working properly.

Thanks for all the help.

Best ragards,
Gabriel

**Comment by wind39** [comment]
Hi @gabrielgisoldo ,

Thanks for your feedback, closing this now.

Best regards,

William
