### ISSUE TITLE
PostgreSQL is not supported. Please install it with 'pip install Spartacus[postgresql]'.

### ISSUE THREAD

**Issue by gabrielgisoldo** [OmniDB/OmniDB#590]
I updated my omnidb-app to the new version and, even though i have Spartacus installed (V. 2.59), I'm getting this error when starting the application.

This is the traceback:

Environment:

Request Method: GET
Request URL: http://localhost:8000/login/?user=admin&pwd=admin&token=mg6t15bilzfyw73ymzi3cdi9ih4kkc94l8pv21aa9jsgrdadle

Django Version: 2.0.6
Python Version: 3.5.2
Installed Applications:
['OmniDB_app.apps.OmnidbAppConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "site-packages/django/core/handlers/exception.py" in inner
  35. <source code not available>

File "site-packages/django/core/handlers/base.py" in _get_response
  128. <source code not available>

File "site-packages/django/core/handlers/base.py" in _get_response
  126. <source code not available>

File "OmniDB_app/views/login.py" in index
  31. <source code not available>

File "OmniDB_app/views/login.py" in sign_in_automatic
  132. <source code not available>

File "OmniDB_app/include/Session.py" in __init__
  52. <source code not available>

File "OmniDB_app/include/Session.py" in RefreshDatabaseList
  232. <source code not available>

File "OmniDB_app/include/OmniDatabase/__init__.py" in InstantiateDatabase
  51. <source code not available>

File "OmniDB_app/include/OmniDatabase/PostgreSQL.py" in __init__
  71. <source code not available>

File "OmniDB_app/include/Spartacus/Database.py" in __init__
  1092. <source code not available>

Exception Type: Exception at /login/
Exception Value: PostgreSQL is not supported. Please install it with 'pip install Spartacus[postgresql]'.

**Comment by gabrielgisoldo** [comment]
Just to add some information, I tried execution the code "pip install Spartacus[postgresql]" and the output I received is:
Requirement already satisfied: Spartacus[postgresql] in /usr/lib64/python2.7/site-packages (2.59)
Requirement already satisfied: pyscrypt in /usr/lib64/python2.7/site-packages (from Spartacus[postgresql]) (1.6.2)
Requirement already satisfied: pyaes in /usr/lib64/python2.7/site-packages (from Spartacus[postgresql]) (1.6.1)
Requirement already satisfied: openpyxl in /usr/lib64/python2.7/site-packages (from Spartacus[postgresql]) (2.5.4)
Requirement already satisfied: click in /usr/lib64/python2.7/site-packages (from Spartacus[postgresql]) (6.7)
Requirement already satisfied: sqlparse in /usr/lib64/python2.7/site-packages (from Spartacus[postgresql]) (0.2.4)
Requirement already satisfied: psycopg2-binary in /usr/lib64/python2.7/site-packages (from Spartacus[postgresql]) (2.7.5)
Requirement already satisfied: jdcal in /usr/lib64/python2.7/site-packages (from openpyxl->Spartacus[postgresql]) (1.4)
Requirement already satisfied: et_xmlfile in /usr/lib64/python2.7/site-packages (from openpyxl->Spartacus[postgresql]) (1.0.1)

**Comment by rafaelthca** [comment]
Hi @gabrielgisoldo,

What OS?

**Comment by rafaelthca** [comment]
Right, how are you starting OmniDB?

Because if you are starting with ```omnidb-app``` in the console it is using the python environment bundled with the installer. I can confirm that you are using 3.5, because of the traceback you shared:

```
Django Version: 2.0.6
Python Version: 3.5.2
```

Could you please tell me which installer did you use from website? I will try to reproduce the error here.

**Comment by gabrielgisoldo** [comment]
I'm starting it through terminal or Desktop shortcut, but both ways ends up with the same error.

I used this one -> https://omnidb.org/dist/2.9.0/omnidb-app_2.9.0-debian-amd64.deb

**Comment by rafaelthca** [comment]
Thanks. I'll try to reproduce the issue. Can you confirm that 2.8.0 installed with:

https://omnidb.org/dist/2.8.0/omnidb-app_2.8.0-debian-amd64.deb

Was working fine?

**Comment by gabrielgisoldo** [comment]
Yes it was.

But I found  what was causing the error.
It's just a problem with the upgrade of the package on Slackware.

I uninstalled and installed again (made a new installation not an upgrade) and everything worked fine with 2.9.0.

Thanks for the help!

**Comment by gabrielgisoldo** [comment]
Actually, making one correction.

I got it to work when a run it as root or sudo

**Comment by rafaelthca** [comment]
Interesting. Installing Slackware here to investigate.

**Comment by gabrielgisoldo** [comment]
Hey @rafaelthca,
Now i really found the problem kkk

The problem is within the installation script for Slackware.

I'm the maintainer and the script on my PS was installing everything great (including 2.9.0 just tested it and everything is working), but when a submitted it to Slackbuilds, they made some changes to keep it on their pattern and that's why it's not working properly.

I'll try to contact them and see if they can keep my scripts without changes, otherwise it's not gonna work.

Thanks for your help! o/

**Comment by wind39** [comment]
Hi @gabrielgisoldo ,

Thanks for your hard work maintaining OmniDB scripts within Slackware. Did they reverted the changes they made to your script?

Regards,
William Ivanski

**Comment by wind39** [comment]
Hi @gabrielgisoldo ,

Thanks again for maintaining OmniDB in Slackware. What is the current situation on this, please?

Regards,

William Ivanski

**Comment by gabrielgisoldo** [comment]
Hi @wind39, sorry for the late response o/
They reverted the the changes and everything is working perfectly.
Later I'll submit the update to the new version so we get to use 2.11.0

Best regards,
Gabriel

**Comment by wind39** [comment]
Hi @gabrielgisoldo ,

I can see you are keeping the repository always up-to-date, thanks for that!

I'm closing this issue now. Please reach us out if you need any assistance.

Regards,

William
