### ISSUE TITLE
Suggestion : bypass confirm dialog box when changing db

### ISSUE THREAD

**Issue by pmpetit** [OmniDB/OmniDB#592]
Hello,
Maybe we could bypass the confirmation dialog box while changing database node....

Thanks

**Comment by rafaelthca** [comment]
hi @pmpetit,

Thanks for the suggestion. People already suggested that, but the main issue is that changing database requires to change the connection object and there may be tabs performing operations in the current  database.

An idea is to bypass confirm dialog box if there aren't any troublesome tabs. Do you have a better suggestion?

At the moment you can manage multiple databases with the same connection by using multiple connection tabs.

Rafael.

**Comment by wind39** [comment]
Hi @pmpetit ,

We have improved on this area. Now OmniDB detects if there are any troublesome tabs, for example Edit Data and Monitoring Dashboard and informs the user before connecting to a different database.

We released OmniDB 2.14 last week. Would you please try? Your feedback would be much appreciated.

Regards,

William

**Comment by wind39** [comment]
Closing this.
