### ISSUE TITLE
Starting with connection as parameter

### ISSUE THREAD

**Issue by cschwaderer** [OmniDB/OmniDB#597]
Hi there,

when starting OmniDB from the command line (being on Ubuntu 16.04) with the command `omnidb-app`, I'd like to pass the connection to be used as a parameter. Just to clarify: I mean not the "name" of the connection, but the whole info OmniDB needs: host, port, username, password etc.
If this is already possible, I cannot find out how (didn't find anything about command line parameters at all in the documentation).

The "normal" stored connections shouldn't be touched (changed in the config) but should be invisible when starting OmniDB with a connection parameter.

That would be quite useful to me.

Background: We run a remote PostgreSQL cluster. The policy is that the passwords both for the machine itself and the Postgres DB running on it are nowhere to be stored except a password manager file. The passwords are also changed quite often. So, it would be quite inconvenient each time copy&pasting the password.

So, what I'd like to do is, create a shell script which asks for the password of the password manager file, fetches the passwords from there, creates an SSH tunnel - and then opens OmniDB app with the credentials of the remote connection as a parameter.
I got that to work with pgAdmin III with a very dirty hack. But since I'd like to replace pgAdmin with OmniDB, I'm hoping for a cleaner solution now.

**Comment by barthisrael** [comment]
Hi @cschwaderer ,

We have written below helper bash script that might do what you want using our docker image:

```bash
#!/bin/bash

################################################################################################################################################
# Start OmniDB with a single connection                                                                                                        #
# Call: omnidb_single_connection.sh <container_name> <omnidb_user> <omnidb_password> <pg_host> <pg_port> <pg_database> <pg_user> <pg_password> #
# Parameters:                                                                                                                                  #
#     * container_name: name of the container that will be created                                                                             #
#     * omnidb_user: username of the OmniDB super user that will be created                                                                    #
#     * omnidb_password: password of the OmniDB super user that will be created                                                                #
#     * pg_host: host of the postgres connection                                                                                               #
#     * pg_port: port of the postgres connection                                                                                               #
#     * pg_database: database of the postgres connection                                                                                       #
#     * pg_user: user of the postgres connection                                                                                               #
#     * pg_password: password of the postgres connection                                                                                       #
################################################################################################################################################

# check script call arguments
if [ "$#" -ne 8 ]; then
  echo "Usage: $0 <container_name> <omnidb_user> <omnidb_password> <pg_host> <pg_port> <pg_database> <pg_user> <pg_password>" >&2
  exit 1
fi

# get arguments
CONTAINER_NAME=$1
OMNIDB_USERNAME=$2
OMNIDB_PASSWORD=$3
PG_HOST=$4
PG_PORT=$5
PG_DATABASE=$6
PG_USER=$7
PG_PASSWORD=$8

# create omnidb container
docker run -d --rm --name $CONTAINER_NAME --publish 8000:8000 omnidbteam/omnidb:latest

# create super user of OmniDB
docker exec -it $CONTAINER_NAME python omnidb-server.py --createsuperuser=$OMNIDB_USERNAME $OMNIDB_PASSWORD

# create connection
docker exec -it $CONTAINER_NAME python omnidb-server.py --createconnection=$OMNIDB_USERNAME postgresql single_connection $PG_HOST $PG_PORT $PG_DATABASE $PG_USER

# store password in .pgpass of container
docker exec -it $CONTAINER_NAME touch /home/omnidb/.pgpass
docker exec -it $CONTAINER_NAME chmod 600 /home/omnidb/.pgpass
docker exec -it $CONTAINER_NAME chown omnidb:omnidb /home/omnidb/.pgpass
docker exec -it $CONTAINER_NAME bash -c "echo '$PG_HOST:$PG_PORT:$PG_DATABASE:$PG_USER:$PG_PASSWORD' > /home/omnidb/.pgpass"

# start OmniDB
docker exec -it $CONTAINER_NAME python omnidb-server.py

```

To use it you should execute it with required arguments as you can see in the top of it. Then you should access the address `http://127.0.0.1:8000` of your machine and use credentials passed to the script to login to OmniDB.

After doing everything you want, just stop the container with a command similar to:

```bash
docker stop <container_name>
```

Let us know your thoughts on that.

Regards.
