### ISSUE TITLE
Export grid data to XLSX, CSV or DBF

### ISSUE THREAD

**Issue by wind39** [OmniDB/OmniDB#6]
Spartacus already can save a DataTable into a XLSX or CSV file (DBF support coming soon).
Maybe a button below SQL editor, next to the data grid?

**Comment by wind39** [comment]
@rafaelthca Spartacus is now able to export data to CSV, XLSX or DBF. Export is done by method TransferToFile, in blocks and consuming minimum RAM, like Transfer does.

DBF export has two limitations: field names need to be 11 character length or less, and field content need to be 254 character length or less.

A remarkable feature is that XLSX export doesn't require Microsoft Excel or any piece of software installed on the host machine. Also, the host OS doesn't need to be MS Windows, it'll work on any supported OS.

Could you please put this feature on MainDB page? Thanks.

**Comment by rafaelthca** [comment]
Done.

Now it is possible to export data from a query to CSV, XLSX and DBF.

![screen shot 2016-06-13 at 9 33 05 pm](https://cloud.githubusercontent.com/assets/9335851/16027661/a304486a-318c-11e6-8f72-cb6020e6420c.png)
