### ISSUE TITLE
Error while exporting file

### ISSUE THREAD

**Issue by pgaro** [OmniDB/OmniDB#604]
When I try to export a file from oracle I get the error:
```
Traceback (most recent call last):
File "OmniDB/ws_core.py", line 213, in thread_dispatcher
KeyError: 'conn_tabs_tab4'
```

I have to restart the session to get rid of the error once it occurred. It's reproduceable.

All the best
pgaro

**Comment by wind39** [comment]
Hi @pgaro ,

Thanks for reaching out. Can you please provide the following:

- OmniDB version and flavor (server or app)
- Operating system and version
- Does it happen only for this specific RDBMS and query, or it happens for every RDBMS / query ?

Regards,
William Ivanski

**Comment by pgaro** [comment]
Thanks for the response. This occurs on every query on the 2.7 Omnidb server. It's running on a Xenial (ubuntu).

I fiddled a little bit and noticed it only occurs with xlsx format selected. While the csv format seems broken as well, it doesn't cause the session to crash.

Since you asked about the rdbms: I just installed a local postgres instance and noticed it crashes exactly the same way.

Regards
pgaro

**Comment by wind39** [comment]
Hi @pgaro ,

Please refer to #519 , we have pushed a fix in latest version, can you please test version 2.9.0 ?

Thanks in advance,
William Ivanski

**Comment by pgaro** [comment]
Thank for the link after the update the error message changes (and don't cause the whole session to crash anymore). It homogenizes between the two formats. W/ pg it's something like 
```
syntax error at or near "select"
LINE 2: select * from pg_stat_activity;
```
while oracle yields 

`ORA-00933: SQL command not properly ended`

both querys work individually (without export) as expected.

Thanks for the reply
pgaro

**Comment by pgaro** [comment]
I like the save button. Works great!

**Comment by jdelramirez** [comment]
when trying to export a result and more than one  query in the console, the export cant export the data,

ORA-00933: SQL command not properly ended

I think omnidb is launching again the query but it detects two and make an error, why didnt export the actual result when you launch a query??

Thanks
