### ISSUE TITLE
Unsupported "regnamespace" type (9.4)

### ISSUE THREAD

**Issue by everneret** [OmniDB/OmniDB#605]
Hi,

I am testing out OmniDB on my 9.4 server and got the following error while browsing my databases and schemas : 

"type 'regnamespace' doesn't exist [...] LINE 50: where n.oid = 'public'::regnamespace"

I see that regnamespace [was indeed introduced in PostgreSQL 9.5](https://www.postgresql.org/docs/9.5/static/datatype-oid.html).

I downloaded the OmniDB master branch and saw that in `Omnidb_app/include/OmniDatabase/PostgreSQL.py:4708` a cast to `regnamespace` is explicitly made. I guess that's where my trouble is coming from.

Looks like this was introduced in OmniDB 2.9 with the addition of privileges in Schema DDL information. Maybe using `quote_ident(n.nspname)` (like in other sections) instead of `n.oid ` would do the trick.

**Comment by wind39** [comment]
Hi @everneret ,

Thank you for reporting this, and for all the detailed information we provided.

You are right, it was introduced in OmniDB 2.9. I have already fixed it the way you suggested. The fix will be available in the next release, 2.10, which is coming out next week.

Regards,
William Ivanski

**Comment by everneret** [comment]
Hi William, 

Thanks for letting me know.

Looking forward to the  2.10 release then ;)

**Comment by everneret** [comment]
Thanks! Will check it out as soon as I get back from vacation.

Le ven. 27 juil. 2018 à 14:24, William Ivanski <notifications@github.com> a
écrit :

**Comment by wind39** [comment]
Hi @everneret ,

Thank you very much for your feedback! I'm closing this issue now.

Regards,
William Ivanski
