### ISSUE TITLE
Microsoft Edge

### ISSUE THREAD

**Issue by pgaro** [OmniDB/OmniDB#609]
While it has low priority for me, a coworker of mine noticed that the scrolling in the data field is broken for Microsoft Edge - the scroll wheel scrolls in the wrong direction under certain conditions.

All the best
pgaro

**Comment by wind39** [comment]
Hi @pgaro ,

Just to let you know that your request was not forgotten :)

While we don't use Windows to work, I just managed to simulate some weird behavior with scrolls in Edge. For grids, the vertical scroll wheel indeed is inverted, while for some components the horizontal scroll does not work at all, even if dragging with the mouse.

We plan to better support Microsoft Edge in the next few releases. In the meanwhile, your coworker could use OmniDB app version on Windows, and perhaps connect to the database using a SSH tunnel.

Will let you know once we have any news on this.

Best regards,

William

**Comment by pgaro** [comment]
My coworker switched to firefox for OmniDB by now.

Regards
pgaro

**Comment by pgaro** [comment]
While I don't want to question your reasoning, I'm also not sure whether it's reasonable to invest into Edge now. There are rumors that Microsoft is working on a Chromium-based replacement internally (even though they didn't do a press report).

That being said, if you have very important customers using it...well, it's your decision.

Regards
pgaro

**Comment by wind39** [comment]
Hi @pgaro ,

We don't have any particular reason to try to add support for Microsoft Edge. Your rationale is great, as Microsoft is planning to release a Chromium-based version soon, we will simply not worry about Microsoft Edge for now.

We still consider Google Chrome and Firefox first-class citizens, though.

Thanks and regards,

William
