### ISSUE TITLE
Oracle query data option

### ISSUE THREAD

**Issue by pgaro** [OmniDB/OmniDB#611]
When using the query data option with oracle databases I get the error "[object Object]". this is reproducible with different oracle databases (pg works fine as well as writing the query myself).

pgaro

**Comment by wind39** [comment]
Hi @pgaro ,

Thanks for reporting this. I just fixed this, the fix will come to the release 2.10 next week.

Regards,
William Ivanski

**Comment by wind39** [comment]
Hi @pgaro ,

Can you please test 2.10 we released yesterday and provide your valuable feedback, as always?

Thanks in advance!
William Ivanski

**Comment by pgaro** [comment]
Works as expected now, thank you!

All the best
pgaro
