### ISSUE TITLE
postgres renaming of schema qualified tables with the GUI

### ISSUE THREAD

**Issue by pgaro** [OmniDB/OmniDB#622]
Simple bug:
If the table is schema qualified the GUI breaks while renaming, since the schema name is inserted again after rename.

Regards
pgaro

**Comment by rafaelthca** [comment]
Thanks @pgaro. Will fix that for 2.10, coming this Thursday.

**Comment by wind39** [comment]
Hi @pgaro ,

We have fixed this, can you please try again and provide your valuable feedback (as always)?

Thanks very much in advance.

Best regards,

William Ivanski

**Comment by pgaro** [comment]
Works perfectly fine now, thanks!

Regards
pgaro
