### ISSUE TITLE
The Postgresql 10 cannot start due to could not access file "bdr" for OmniDB 2.9.0 configuration

### ISSUE THREAD

**Issue by Sroeurnsuon** [OmniDB/OmniDB#625]
Dear All,
After I change the "postgresql.conf" for shared_preload_libraries = 'bdr', then the postgresql 10 cannot start the services as below error:
![2018-07-25_9-15-04](https://user-images.githubusercontent.com/25451156/43175879-6f33282a-8feb-11e8-8899-d86749420f33.jpg)
Kindly help me!
Best regards,
Sroeurn Suon

**Comment by wind39** [comment]
Hi @Sroeurnsuon ,

Thanks for reaching out. I'm afraid this is not an OmniDB issue, but rather you need to properly install BDR into your system.

Please find more details about the BDR project here: https://github.com/2ndQuadrant/bdr

Regards,

William Ivanski

**Comment by Sroeurnsuon** [comment]
Dear Mr. William,

Thank you very much for your reply! 

Please note that your installation instruction for PostgreSQL 9.4 and my problem is for PostgreSQL 10.
Kindly let me know the installation instruction for PostgreSQL 10 for BDR 3.0.

Best regards,
Sroeurn Suon
