### ISSUE TITLE
MySQL doesn't render simple or complete graph

### ISSUE THREAD

**Issue by ccampo55** [OmniDB/OmniDB#628]
I installed and successfully connected to my local mysql db.  I'm able to query the data.  The graphs do not render.

I was able to render the graphs for the information_schema database.

**Comment by wind39** [comment]
Hi @ccampo55 ,

Thanks for reaching out. Can you please provide versions for OmniDB, MySQL and operating system? Also, are you seeing an error message?

Regards,

William Ivanski

**Comment by wind39** [comment]
Hi @ccampo55 ,

We were not able to simulate your issue. Since OmniDB receive improvements in MySQL support since we last spoke, can you please try last version? We released 2.14 last week.

Best regards,

William

**Comment by wind39** [comment]
Closing this.
