### ISSUE TITLE
User password storing is not secure

### ISSUE THREAD

**Issue by raamets** [OmniDB/OmniDB#635]
Currently the user password are stored in databases in crypted format. It's pretty easy to decrypt them. It would be nice if only password hashes would be saved in database.

**Comment by wind39** [comment]
Hi @raamets ,

Thanks for reaching out. We will hopefully tackle this for next release, 2.12.0.

Regards,

William Ivanski

**Comment by eazrael** [comment]
Just installed OmniDB for the first time and wondered how safe passwords are. I hoped not to find a ticket like this :( 
Just skipped over the commit messages. Am I right that this was not fixed in 2.12?

**Comment by brylie** [comment]
When I connect to a Postgres DB, OmniDB asks for the password each time. Which password do you mean?

**Comment by eazrael** [comment]
omnidb user password.

**Comment by wind39** [comment]
Closing this issue now.
