### ISSUE TITLE
Zombie tab

### ISSUE THREAD

**Issue by pgaro** [OmniDB/OmniDB#636]
There is an issue that occurs sporadically when clicking on a tab that the tab becomes grayed out. Clicking it yields no results while the shortcut for the next/last tab just skips it.
![zombie_tab](https://user-images.githubusercontent.com/38760999/43405819-06afe94e-941b-11e8-8cb8-5b5c614c50fa.jpg)

Regards
pgaro

**Comment by barthisrael** [comment]
Hello,

Can you reproduce the error or have you noticed some kind of pattern?

Regards,
Israel.

**Comment by pgaro** [comment]
It happens from time to time seemingly at random, but not every day - more like once every 20 hours of using omnidb. We are mainly using the web version (so we had this issue only there). After logging in again the tab vanishes fully. So if that happens, the queries in the tab are lost. Sadly I can't make up a pattern.

Regards
pgaro

**Comment by barthisrael** [comment]
Hi,

I've tried to reproduce such problem a lot of times last weekend but no failures while doing it. Could you inform your OS, browser and OmniDB version, please?

Regards,
Israel.

**Comment by pgaro** [comment]
This happens on linux as well on windows with firefox 60.1.0 as well as 61.0.1 and with Omnidb 2.10 as well as 2.9.

Even for me it's not proper reproducible, it just happens from time to time.

Regards
pgaro

**Comment by barthisrael** [comment]
I see. I'll try it in a environment like yours. Maybe that helps.

Thanks,
Israel.

**Comment by wind39** [comment]
Hi, @pgaro , @barthisrael ,

Did you guys have any chance to reproduce this?

Thanks in advance,

William Ivanski

**Comment by pgaro** [comment]
It happens now and then, but I don't see any pattern. It doesn't happen every day, so it isn't the most pressing thing for me. When I find a reproducible way to get to this state, I'll let you know.

**Comment by barthisrael** [comment]
Unfortunately not. I've tried a couple of times without success. It just did not happen once while using OmniDB. If someone face it and find a pattern, I'll work in a fix.

Regards,
Israel.

**Comment by pgaro** [comment]
I didn't encounter this with 2.12 and 2.13 anymore, so I'm closing this.

Regards
pgaro
