### ISSUE TITLE
Alter table GUI

### ISSUE THREAD

**Issue by pgaro** [OmniDB/OmniDB#637]
The alter table GUI doesn't support changing the NULL values properly - it just gives "request error". Are you set you want to support that menu on the long term?

If you would add a way to look at the internally issued commands, I'd gladly help to debug different menus further.

All the best
pgaro

**Comment by barthisrael** [comment]
Hi pgaro,

Fixed that. Coming in the next version.

Thanks,
Israel.

**Comment by pgaro** [comment]
Works perfectly fine, thank you!

All the best
pgaro
