### ISSUE TITLE
external_websocket_port not working correctly

### ISSUE THREAD

**Issue by atmaniak** [OmniDB/OmniDB#641]
If i add an external_websocket_port (443) and use nginx as a reverse proxy to contact OmniDB, the app have a very strange behavior and websockets are not working correctly since the web app alternates between 
websocket_port (not working) & external_websocket_port (working)

![omnidb_bug](https://user-images.githubusercontent.com/800433/43510913-64294702-9577-11e8-89ee-d189b40316b8.png)

**Comment by wind39** [comment]
Hi @atmaniak ,

Thanks for reaching out. It seems duplicate to #682 . We will try and dig into this and get back to you.

Regards,

William Ivanski

**Comment by wind39** [comment]
Also duplicate as #652

**Comment by wind39** [comment]
Being handled in #652
