### ISSUE TITLE
Watching Functions in PostgreSQL 11

### ISSUE THREAD

**Issue by jeasoft** [OmniDB/OmniDB#642]
Hi there! I was trying to test PostgreSQL 11 in @OmniDB, but I found this error when I try to see the functions:

```
column p.proisagg does not exist
LINE 8:             where not p.proisagg
                              ^
HINT:  Perhaps you meant to reference the column "p.prolang".
```

Searching in the PostgreSQL documentation I found a breaking change in the system catalog table `pg_proc`, at least that's what I think. There's not `proisagg` anymore. There's a new field named `prokind` who enumerated this: "*f for a normal function, p for a procedure, a for an aggregate function, or w for a window function*". I see this [here](https://www.postgresql.org/docs/11/static/catalog-pg-proc.html).

I think this new change reduce a lot of code for developing new tools, but at the same time this will affect not only this project, but A LOT OF PostgreSQL admin tools will be affected with this.

**Comment by wind39** [comment]
Hi @jeasoft ,

Can you please try OmniDB 2.11 and provide your valuable feedback?

Thank you very much in advance.

Regards,

William Ivanski

**Comment by jeasoft** [comment]
Hi @wind39. 

I will do it on the weekend and let you know. Thanks for your great work guys!

**Comment by jeasoft** [comment]
GREAT! @wind39!

**Comment by jeasoft** [comment]
Thank you for your excellent work guys!
