### ISSUE TITLE
make connections list sortable

### ISSUE THREAD

**Issue by raamets** [OmniDB/OmniDB#645]
We have tens of different databases with same dbt_st_name and currently the Connections list is for us almost unusable. The databases are listed in some weird default order and there are no options to group or order them. Looking at the code, it seems that default order could be by conn_id, but for us the result is not ordered by this field.

BTW. Our devs say that 30 minutes is a bit fast for connections timeout. So if PWD_TIMEOUT_TOTAL is the parameter that controls this, then maybe add PWD_TIMEOUT_TOTAL to omnidb.conf with a small description.

**Comment by barthisrael** [comment]
Hello @raamets , thanks for the suggestions. Coming in the next version.

Regards,
Israel.

**Comment by raamets** [comment]
Thanks Isreal, the sorting looks nice. But looks like the  PWD_TIMEOUT_TOTAL conf change does not have any effect. Maybe I should created a separated ticket for it.

**Comment by barthisrael** [comment]
Hi @raamets , thanks for the response. 

I think I know what is going on. Which omnidb.conf file have you changed the parameter? Unlike the OmniDB database, our deploy script does not have a migration system to the configuration file. It creates a omnidb.conf in your home path if there is not one yet, using the default omnidb.conf. If the file already exists in your home, it won't do nothing in order not to change your custom settings. 

Maybe you changed the base omnidb.conf, but not the one used by OmniDB when it is running. If so, could you include the new configuration parameters from our default file to it and test again, please?

We're sorry about that if it's the problem. Hope it helps.

PS: OmniDB creates a hidden directory called omnidb in you home, where you omnidb database and omnidb.conf are hosted.

Best,
Israel.

**Comment by raamets** [comment]
Hi @barthisrael , yes the config tip did help and looks like now the increased time value is working. Thank you. So I think this issue can be closed
