### ISSUE TITLE
Debugger plugin for PostgreSQL

### ISSUE THREAD

**Issue by ormenese** [OmniDB/OmniDB#646]
Conforme conversa na PGConf 2018, tentei instalar o plugin de debug no FreeBSD mas o pacote de instalação do Debian e do CentOS não foram aceitos.

Existe a possibilidade de compilação e disponibilização deste plugin para o FreeBSD?

**Comment by rafaelthca** [comment]
Bom dia @ormenese.

Vamos trabalhar nisso e te manter informado por aqui.

Rafael.

**Comment by ormenese** [comment]
Ok.... perfeito !!!

Muito obrigado !!!

**Comment by wind39** [comment]
Olá, @ormenese , tudo bem?

Compilei o OmniDB debugger para FreeBSD 64 bits. Você pode baixá-lo diretamente pelo link [https://omnidb.org/dist/2.10.0/omnidb-plugin_2.10.0-freebsd-amd64.tar.gz](https://omnidb.org/dist/2.10.0/omnidb-plugin_2.10.0-freebsd-amd64.tar.gz) ou pelo site do OmniDB:

![image](https://user-images.githubusercontent.com/7719686/43853642-1fdb2b24-9b17-11e8-9344-d15227425188.png)

O debugger foi compilado no FreeBSD 10.4 (estável mais antigo suportado) para o PostgreSQL 9.3, 9.4, 9.5, 9.6 e 10. É com muita satisfação que eu informo que, a partir de agora, a cada nova release do OmniDB, vamos compilar o debugger no FreeBSD e disponibilizar para download.

Note que ainda não há instaladores do OmniDB (app ou server) para o FreeBSD. Pretendemos trabalhar nisso no futuro próximo, mas como a próxima release do OmniDB (2.11) sai nos próximos dias, fica muito em cima para investirmos tempo nisso agora.

Então, para poder usar o OmniDB debugger, você precisa:

- Instalar o OmniDB app ou server em um computador Linux, OSX ou Windows;
- Instalar o OmniDB debugger no FreeBSD onde está o PostgreSQL. Note que será necessário reiniciar o PostgreSQL.

O resultado é que a interface do OmniDB se comunica com o debugger:

![image](https://user-images.githubusercontent.com/7719686/43853446-852b3682-9b16-11e8-8949-8874ecea170a.png)

Se você quiser saber mais detalhes sobre os passos que eu utilizei para compilar o debugger no FreeBSD, por favor leia [este documento](https://github.com/OmniDB/OmniDB/blob/dev/OmniDB/deploy/plugin_freebsd_amd64/compile_instructions.txt). Se você quiser ver os passos utilizados para instalar o debugger no FreeBSD, por favor leia [este outro documento](https://github.com/OmniDB/OmniDB/blob/dev/OmniDB/deploy/plugin_freebsd_amd64/test_instructions.txt).

Novamente muito obrigado por ter entrado em contato conosco no PgConf Brasil 2018, foi um prazer conhecê-lo pessoalmente! Aguardamos seu feedback sobre o debugger, será muito importante para nós.

Abraço,
William Ivanski

**Comment by ormenese** [comment]
Ok William !!

Vou fazer a instalação e testar. Em breve dou um retorno.

Obrigado pela disponibilidade em liberar de forma tão rápida.

Abraço
André Ormenese

**Comment by ormenese** [comment]
William, infelizmente não consegui subir o banco com a biblioteca de debugger.

Copiei a bliblioteca omnidb_plugin_10.so* para $libdir/postgresql/omnidb_plugin.so.

Coloquei no postgresql.conf : shared_preload_libraries = 'omnidb_plugin'

E obtenho o seguinte erro : waiting for server to start....2018-08-08 16:43:23 -03 [67455]: [1-1] user=,db=,app=,client= FATAL:  could not load library "/dados/bancos/pg_hemo/10.4/lib/postgresql/omnidb_plugin.so": dlopen (/dados/bancos/pg_hemo/10.4/lib/postgresql/omnidb_plugin.so) failed: Shared object "libpq.so.5" not found, required by "omnidb_plugin.so"

A libpq.so.5 está em $libdir.

O que eu acho estranho é que tenho algumas contribs instaladas neste banco e todas as bibliotecas estão nesta mesma pasta $libdir/postgresql.

Tem alguma sugestão ?

**Comment by wind39** [comment]
Olá, @ormenese ,

Agradeço pela pronta resposta. Você tem o client do PostgreSQL instalado?

```bash
pkg install postgresql10-client-10.4
```

Não sou nem um pouco export em FreeBSD, mas existe a possibilidade de você mudar o library path para o PostgreSQL? A ideia seria incluir o caminho `/dados/bancos/pg_hemo/10.4/lib/` no library path. No Linux tem o arquivo `/etc/environment`, não sei como funciona no FreeBSD.

**Comment by ormenese** [comment]
@wind39 ,
consegui resolver o problema da biblioteca. Meu SO estava com um link errado em /usr/lib para a libpq.so.5
Agora estou conseguindo debugar !!!
Vcs aceitam sugestões para o OmniDB ? Onde posso enviar ? 

Muito obrigado pela atenção.

**Comment by wind39** [comment]
Olá, @ormenese ,

Que legal, ficamos muito felizes que está funcionando no FreeBSD :+1: 

Vou encerrar essa issue aqui então. Sugestões, report de bugs e feedback é muito bem-vindo, mas se possível por favor abrir issues separadas, pois usamos elas pra construir o roadmap do que é desenvolvido em cada versão.

Muito obrigado!

William Ivanski
