### ISSUE TITLE
Add SSL support

### ISSUE THREAD

**Issue by vadius8998** [OmniDB/OmniDB#648]
Hello,

In the connection tab, could you add SSL support ? The SSH tunnel is not always appropriate for users.

Thanks,

**Comment by wind39** [comment]
Hi @vadius8998 ,

We released OmniDB 2.14.0 last week with support to URI connection strings. You can pass SSL specific arguments upon connection this way. Please check more details in the [PostgreSQL documentation](https://www.postgresql.org/docs/9.3/libpq-connect.html#LIBPQ-CONNSTRING).

Best regards,

William

**Comment by wind39** [comment]
Closing this.
