### ISSUE TITLE
Cannot transfer 'geometry' values

### ISSUE THREAD

**Issue by stanom** [OmniDB/OmniDB#65]
Hello,
Thanks for excellent tool for migration data between databases.
What's about data transfer with "geometry" type?
I try to migrate the spatial table from MSSQL to PostgreQSL (Postgis).
The result: In the migrated table - in geometry field - are non-geometry values: 'System.Byte[]' geometry value has been loss. GEOMETRY type column from MSSQL was migrated to PostgreSQL as TEXT type.

The proposals:
 - by the 'Conversion' definition will be possible to define raw SQL -> geometry can be imported as text - WKT - [source.geometry].STAsText()

Best regards 
Stano

**Comment by wind39** [comment]
Thank you for providing valuable information to help improving OmniDB.
Unfortunately OmniDB still doesn't support spatial data. At this moment, any unknown types are default to TEXT (or equivalent) on the target RDBMS system.
We will investigate to implement spatial data support in OmniDB and I'll let you know of any progress we have.
Thanks again.

**Comment by deyvsonti** [comment]
Please, do it

![please](https://user-images.githubusercontent.com/20284175/41310879-295d3ab0-6e59-11e8-9ca1-0df395d21c55.jpg)

**Comment by wind39** [comment]
Unfortunately the C# OmniConvert is not supported anymore. We plan to implement that into the OmniDB Python version. Closing this for now.
