### ISSUE TITLE
Websocket request intermittently directed to internal port when behind nginx

### ISSUE THREAD

**Issue by kpaludan** [OmniDB/OmniDB#652]
- Running OmniDB server, Centos7 64 bits behind nginx as follows **omnidb-server -H 127.0.0.1 -p 9000 -w 25482 -e 443**
- Some wss requests correctly go to port 443, but occasionally the request is send to the internal port 25482, and an error pops up (see screenshot)
![websocket error](https://user-images.githubusercontent.com/5792685/44138899-554892d2-a06d-11e8-9db2-1db4dc4ac11f.png)

**Comment by kpaludan** [comment]
Should add that this us using Chrome for Mac Version 68.0.3440.106

**Comment by kpaludan** [comment]
Hi @rafaelthca , 
thanks, that is helpful - the first request immediate gets a 101 immediately, but then sits "pending" for about a minute before the second request to the internal port gets fired
 (and immediately fails).

I'm behind my organisations customised nginx image; suspect the problem is in the configuration of that rather than OmniDB.

![screen shot 2018-08-15 at 14 01 45](https://user-images.githubusercontent.com/5792685/44149792-36dde34c-a095-11e8-911d-ac80d01b1416.png)

**Comment by wind39** [comment]
Duplicate as #682 and #641 .

**Comment by unwasted** [comment]
Hi!

https://github.com/OmniDB/OmniDB/blob/94079e7357917346f40f45e7e5097d9a726d13f2/OmniDB/OmniDB_app/static/OmniDB_app/js/QueryClient.js#L213

Here is the problem.
v_query_port is wrong

But 7 rows down it will make the connection without parameter.
So if i took L213 parameter v_query_port out - everything seems to be working fine :)

**Comment by philbeiler** [comment]
@unwasted Thanks. Worked perfectly. Loosing the connection ever few minutes was very painful!

**Comment by rafaelthca** [comment]
Thanks @unwasted. This is a corner case that needs to be fixed. Line 213 is actually necessary so OmniDB tries to connect with internal port if external one doesn't work. But the code needs to be improved.

I'll do that for next release.

**Comment by rafaelthca** [comment]
Hi @philbeiler, @kpaludan.

I believe this is fixed in 2.15. OmniDB now retries to connect to the same websocket port, after being
disconnected. If it can't, it tries the other one. If neither port work, it will raise the message.

Note that this fix was to make OmniDB "smarter" when handling disconnections. What needs to be investigated is why the client is getting disconnected all the time, are you still experiencing that?

**Comment by wind39** [comment]
Closing this now.
