### ISSUE TITLE
Show active server and database in tab caption

### ISSUE THREAD

**Issue by kattunga** [OmniDB/OmniDB#655]
Please add a caption to tabs that show selected server and database.
When you are working with many server at the same time is difficult to find the tab.

![image](https://user-images.githubusercontent.com/2139720/44203782-a4c4f300-a126-11e8-88cf-e4eccc792880.png)

**Comment by wind39** [comment]
Hi @kattunga ,

Thanks for reaching us out. In the Connections grid there is a "Title" field. Whatever you fill in this field for each connection you be shown as a tab name alongside the technology icon.

Regards,
William Ivanski

**Comment by kattunga** [comment]
In my case I open several times the same connection for work in different databases, I have about 100 databases in one server.
So if I set a title I will see the same title in each tab.
May be the caption could be automatically set as server+database when title is not defined for the connection.

**Comment by rafaelthca** [comment]
That makes sense. When the title column was implemented OmniDB didn't have the ability to manage databases other than the one specified in the connection grid.

I liked your suggestion, my main concern is the size of the tab, server string tends to be large sometimes.

**Comment by raamets** [comment]
My 2 cents - we have multiple databases with same name and at first look adding the database name when title is present is kinda ugly. Not a big problem though, I can change the title generation logic or probably just remove this change from .js file locally.

**Comment by kattunga** [comment]
I checked version 2.11, nice, thank you.

**Comment by rafaelthca** [comment]
@raamets,

can you check if the current implementation in 2.11 works for you? If title is present OmniDB fills tab title with Tile - DATABASE. If there is no title OmniDB uses only the database.

Rafael

**Comment by raamets** [comment]
@rafaelthca 
The Title + Database name looks a bit ugly for us. Currently I have no idea what the Title should look, so that our devs would like the solution. So I just changed a bit in our server the .js files and think about this later. No need to remove the DB name because of me.

**Comment by wind39** [comment]
Hi @raamets ,

This is actually good feedback, thanks. We want OmniDB to be usable for everyone's needs. We will think about the feasibility of adding a configuration option to either show/hide the database name in the tab title.

We will keep this open until we have some news about it.

Regards,

William Ivanski

**Comment by wind39** [comment]
Hi,

We decide to keep database name in tab title. Closing this now.

Regards,

William
