### ISSUE TITLE
Question: Where does OmniDB app store its connections?

### ISSUE THREAD

**Issue by cschwaderer** [OmniDB/OmniDB#673]
As long as https://github.com/OmniDB/OmniDB/issues/597 is not done yet, I have to deal with my special requirement in a hacky way, I guess. I.e. creating a bash script which does the following:
* Copy all OmniDB connections to a backup file
* Delete all OmniDB connections
* Set a new OmniDB connection
* Start OmniDB app
* Wait till OmniDB app is closed
* Revert the changes to the OmniDB connections

My question is now: Where does OmniDB app store its connections (including passwords)? And how can I manipulate them with a script? I couldn't find them anywhere on the filesystem.

(Working on Ubuntu 18.04 LTS with OmniDB app 2.11.)

**Comment by wind39** [comment]
Hi @cschwaderer ,

Thanks for reaching out. I understand your needs and I will try and produce a script to help you achieve that.

Regards,

William Ivanski

**Comment by cschwaderer** [comment]
Hi @wind39,

thanks for your reply! Any news on this so far?

Best,
Christian

**Comment by wind39** [comment]
Hi @cschwaderer ,

Please download the file [script.zip](https://github.com/OmniDB/OmniDB/files/2607971/script.zip), which contails the following:

- `omnidb_app_singleconn.sh`, a Bash script that receives the technology (`postgresql`, for example), the host address, the port, the database name and the user name as arguments. It performs all the steps you required.

- `create_connection.py`, a Python script that creates a connection into the OmniDB user database in your home folder. This script is called by `omnidb_app_singleconn.sh`.

Please note that the connection creation is handled by Python, and you need to have the Spartacus library installed by `pip`, for example:

```
pip install Spartacus[postgresql]
```

Please let me know if you have any further questions.

Best regards,
William

**Comment by cschwaderer** [comment]
@wind39 Thank you so much for providing that script! That could make my current work-around a lot better (just for info: My current work-around is using omnidb-app in day-to-day work for the "normal" connections and using omnidb-server for connecting to the "special" DB).

However, in my opinion, it is not the perfect solution, to be honest. Like I hinted at in https://github.com/OmniDB/OmniDB/issues/597 I'd prefer a solution which accepts a connection parameter to omnidb-app itself with omnidb keeping that connection in-memory without tampering with the stored connections.

- It would be possible to normally continue working with omnidb-app with all the normal connections while having at the same time another instance of omnidb open which connects to a "special" remote DB. 

- With any solution which manipualtes the stored connections on omnidb's internal connection DB risks problems in case of a system crash. If the system crashes while having connections changed it needs manual work to re-set them to the previous state.

Additonally I'd prefer to also pass the password to omnidb as a parameter. Right now, I still have to manipulate `.pgpass` - which I'd like to avoid. (In my case, user name is the same for all my Postgres clusters, passwords are different, though)

And finally the icing of the cake would be: Being able the pass an Editor theme as a parameter. Thus, the "parameterized" omnidb could look&feel totally different from the "normal" one, reducing the risk to mixing them up by accident.

Just my thoughts. Thanks anyway!

**Comment by wind39** [comment]
Hi @cschwaderer ,

Thanks for providing more details about your setup and your needs. They definitely make sense and we plan to implement such parameters soon.

Yeah, I agree the script is not the best solution. It is just a temporary solution to maybe provide you some help while we work on #597 .

We will keep you informed.

Best regards,

William

**Comment by cschwaderer** [comment]
@wind39 Yeah, thanks! As I said the script definitely an improvement compared the my current solution (with omnidb-server)!

**Comment by wind39** [comment]
Hi @cschwaderer ,

We are releasing OmniDB 2.13.0. Unfortunately I don't have any news yet about the #597 , but I plan to implement that soon. Will keep you informed.

Please try 2.13.0 anyway :)

Best regards,

William

**Comment by wind39** [comment]
Hi @cschwaderer ,

Work on #597 is still on our roadmap. As you are able to use the script I provided, I'm closing this issue now. Feel free to open a new one if you have any questions.

Best regards,

William
