### ISSUE TITLE
If possible add more robust memory control options for OmniDB server

### ISSUE THREAD

**Issue by raamets** [OmniDB/OmniDB#678]
Hi

It looks like if you try to "Fetch All" data that is over few GB's, then OmniDB server process uses up all our server memory and OOM kills OmniDB server. 
The problem is that we have lots of big tables and multiple Devs who use same OmniDB server. So even if we increase the server memory, there is a high chance that some Devs will accidentally ask to see too big table or do some cartesian/cross join and so shut down OmniDB server for everybody.
It would be nice if there would be some configurable fetch size or too big results would use temp files instead of pure in-memory solution.
I'm sorry if the solution is already documented somewhere, I did not find it.
Omnidb 2.11, Ubuntu 16.04

**Comment by rafaelthca** [comment]
Hi @raamets,

We've been discussing this for a long time, OmniDB urges for a solution to prevent a user to trigger a OOM scenario. We are looking for solutions that don't alter the query provided by the user, like adding a LIMIT or something like that.

The idea of using temporary files is interesting, it would reduce speed of queries that return a very large set of rows but it would definitely the tool more robust.

We will tackle this issue for the next release.

Rafael.

**Comment by rafaelthca** [comment]
We are going to implement a fix for that in the next release, using server side cursors.

Rafael.

**Comment by wind39** [comment]
Hi @raamets ,

Previously, OmniDB used a client-side cursor to fetch data from PostgreSQL. This means that PostgreSQL would receive the query, process that, gather data, send ALL data to the client-side cursor and only then OmniDB would start to fetch data from the cursor.

For 2.12.0, we implemented in Query Tab and Console Tab the ability to use server-side cursors whenever possible. When this happens, PostgreSQL keeps a cursor by itself, and only sends data to the application when the application requests more data. This drastically reduces application memory usage for large queries and also reduce response time for first data chunk.

We would appreciate if you could download 2.12.0 (we just released it), test it and provide us your valuable feedback. Thanks in advance!

Regards,

William

**Comment by wind39** [comment]
Closing this now.
