### ISSUE TITLE
storing passwords for connections?

### ISSUE THREAD

**Issue by ccurvey** [OmniDB/OmniDB#679]
Is there a way to get OmniDB to store passwords for a connection?  Heroku assigns giant random strings for database passwords, and it's a PITA to have to go look it up every time.

I've tried adding the information to a .pgpass file, but it does not seem to work.

**Comment by ccurvey** [comment]
ahhh...it does work, if you set the permissions on .pgpass to 600. 

(note to future readers -- if using the .pgpass file is not working in OmniDB, make sure it works with `psql`)

**Comment by rafaelthca** [comment]
Hi @ccurvey,

You need to set up .pgpass file in the home of the user that is starting OmniDB. If using omnidb-server as a service the root home should be used, and with the proper permissions.

Rafael.

**Comment by l-we** [comment]
Add support PGPASSWORD ?
