### ISSUE TITLE
Django error

### ISSUE THREAD

**Issue by CSVKRAO** [OmniDB/OmniDB#680]
Hi, 

I have cloned Omni Db data through pycharm and tried to execute, it was showing lots of errors. can you tell me the steps to execute this.

**Comment by jielun-chen** [comment]
你这个是编译的吗，

**Comment by jielun-chen** [comment]
OmniDB有没有中文版的？能否再编译？他的python pip包在哪里？python pip安装包叫什么名字

**Comment by wind39** [comment]
Hi @CSVKRAO ,

Please use an OmniDB package from the Downloads page, to install it for your specific architecture.

Regards,

William
