### ISSUE TITLE
process killed on large operations

### ISSUE THREAD

**Issue by ziodave** [OmniDB/OmniDB#683]
Hello,

I am using omnidb-server 2.11.0.

I am trying to query a table with 7+ millions rows. In the middle of the operation the omnidb-server process exits with the following error:
`omnidb.service: Main process exited, code=killed, status=9/KILL`

Is there a way to fix this?

**Comment by pgaro** [comment]
Can you provide additional information about your query? Are you just trying to query that table or are you returning 7+ million rows?

Regards
pgaro

**Comment by ziodave** [comment]
It’s a ‘select *’ query on a table with 7+ mln records.

In Postgres directly the query works.

Do you mean it might be a memory issue in omnidb-server?

**Comment by pgaro** [comment]
That would be my guess (even though it depends on the data of the rows). Does the server crash during execution or after you do some fetching?

**Comment by ziodave** [comment]
During execution. If I ‘limit’ the query (I tried 10-100-1000) it works.

BR

**Comment by rafaelthca** [comment]
This is a duplicate of https://github.com/OmniDB/OmniDB/issues/678, we will implement a fix for the next version. More details in the other issue.

Closing this.
