### ISSUE TITLE
Autocompletion pgsql / fedora 28

### ISSUE THREAD

**Issue by pmpetit** [OmniDB/OmniDB#684]
Hello,
autocompletion is not ok on fedora28 pgsql ?
ctrl-space shows nothing.....

Thanks

**Comment by wind39** [comment]
Hi @pmpetit ,

Since you opened this issue, OmniDB received a lot of improvements. Last week we released version 2.14. Would you please give it a go? Your feedback will be much appreciated.

Best regards,

William

**Comment by pmpetit** [comment]
ok i'm having a look....

**Comment by wind39** [comment]
Hi @pmpetit ,

Just checking if you were able to try latest OmniDB version.

Thanks in advance,

William

**Comment by wind39** [comment]
Closing this now...
