### ISSUE TITLE
lost records oracle connection

### ISSUE THREAD

**Issue by CRSoq** [OmniDB/OmniDB#685]
Hi,
In my Oracle connection there are records that are lost in the table (usually the first of the following fetch). When downloading the associated CSV file they are present so I think it is a problem of cache or data visualization.
In the image the employee 150 (HR sample database Oracle is absent) .
Omnidb is an excellent tool, I hope this issue can be solved ...

    Ricardo 
![captura de pantalla de 2018-08-31 19 43 15](https://user-images.githubusercontent.com/34549689/44938699-c6dd8880-ad56-11e8-959d-08f6fcca37dd.png)

**Comment by Fenex** [comment]
Same problem with connection via SSH to mysql.

**Comment by rafaelthca** [comment]
Thanks for opening the ticket. Will fix that for next release.

**Comment by rafaelthca** [comment]
This doesn't happen with PostgreSQL, only oracle and mysql

**Comment by CRSoq** [comment]
ok, i hope this is solved in next version.

**Comment by wind39** [comment]
Hi @CRSoq ,

I pushed a fix to the dev branch. It will be published in the next release.

Regards,

William Ivanski

**Comment by wind39** [comment]
Hi @CRSoq , @Fenex ,

We just published OmniDB 2.12.0 with the fix. Would you be kind to download it, test it and give us feedback? Thanks in advance!

Regards,

William

**Comment by wind39** [comment]
Closing this now.
