### ISSUE TITLE
Is there a silent install option for the omnidb application?

### ISSUE THREAD

**Issue by monemihir** [OmniDB/OmniDB#697]
I have just downloaded the application and would like to check if we can include it in our SOE.

For that to work we need a silent install option.

Sorry, if this is a duplicate but can someone point me in the right direction?

**Comment by wind39** [comment]
Hi @monemihir ,

Thanks for reaching out. Can you please provide more details about your need? What is the operating system you are using?

Regards,

William

**Comment by wind39** [comment]
Closing this because unfortunately we don't have enough information about the platform.
