### ISSUE TITLE
clicking on index with where clause

### ISSUE THREAD

**Issue by pgaro** [OmniDB/OmniDB#704]
Clicking on index with where clause gives the error "more than one row returned by a subquery used as an expression".

Regards
pgaro

**Comment by wind39** [comment]
Hi @pgaro ,

Thanks for reporting this. It is fixed now, will be published in next release.

Regards,

William

**Comment by wind39** [comment]
Hi @pgaro ,

Thanks for helping making OmniDB better. This is fixed in OmniDB 2.13.0, which we are releasing today.

I'll keep this issue open in case you want to provide your valuable feedback, as always.

Best regards,

William

**Comment by pgaro** [comment]
Works like a charm, thank you!
