### ISSUE TITLE
'infinity' dates

### ISSUE THREAD

**Issue by cschwaderer** [OmniDB/OmniDB#708]
I have noticed that OmniDB app 2.11 renders in Postgres 9.6 the query `SELECT 'infinity'::date;` as `9999-12-31` whereas psql and pgAdmin 3 correctly put out `infinity`.

Even more problematic seems that OmniDB cannot cope with dates with more than 4 digit years. For `SELECT '12000-12-12'::date;`, pgAdmin 3 and psql give the correct output `12000-12-12`, while OmniDB returns `9999-12-31`.

So, when programming a science fiction game taking place in the far future and having too deal with five digit years - then OmniDB is not your preferred choice  ;)

**Comment by wind39** [comment]
Hi @cschwaderer ,

It's been a while, but I managed to fix this:

![image](https://user-images.githubusercontent.com/7719686/53177143-40e81f00-35ce-11e9-90a7-364a182b2a4a.png)

The fix is going out on next release, 2.15, which will be published on April this year.

Regards,

William

**Comment by wind39** [comment]
Hi @cschwaderer and @pgaro ,

We just released OmniDB 2.15 with a fix for this issue.

This ticket will remain open for a few more days in case you want to provide some feedback, which will be much appreciated.

Thanks and regards,

William

**Comment by cschwaderer** [comment]
Thanks for the fix! Works for me now!
