### ISSUE TITLE
pg_trgm settings don't seem to "take"

### ISSUE THREAD

**Issue by ccurvey** [OmniDB/OmniDB#711]
Consider this script:

```
create extension pg_trgm;
create table foobar(entry varchar(100));
insert into foobar (entry) values ('Larry Stooge');
insert into foobar (entry) values ('Curly Stooge');
insert into foobar (entry) values ('Sneezy Dwarf');
```

Now let's run a query using the similarity function:

```
select entry, similarity(entry, 'Larry Stooge') from foobar;
```

> Larry Stooge	1.0
> Curly Stooge	0.368421
> Sneezy Dwarf	0.04

Now let's limit ourselves based on the similarity function:

```
select entry, similarity(entry, 'Larry Stooge')
from foobar
where similarity(entry, 'Larry Stooge') > 0.5;
```
> Larry Stooge	1.0

Now let's try using the "%" operator in conjunction with `set  pg_trgm.similarity_threshold`;

```
set pg_trgm.similarity_threshold = 0.5;
```

```
select entry, similarity(entry, 'Larry Stooge')
from foobar
where entry % 'Larry Stooge';
```

> Larry Stooge	1.0
> Curly Stooge	0.368421

(oops, I only expected 1 row)

Now let's see what the value of pg_trgm.similarity_threshold is:

```
show pg_trgm.similarity_threshold;
```

> unrecognized configuration parameter "pg_trgm.similarity_threshold"

Now it gets interesting....if I highlight BOTH of the following statements and execute them at the same time, I get what I expect!

```
set pg_trgm.similarity_threshold = 0.5;
select entry, similarity(entry, 'Larry Stooge')
from foobar
where entry % 'Larry Stooge';
```

> Larry Stooge	1.0

Just for completeness:

     select version()

> PostgreSQL 10.5 (Ubuntu 10.5-0ubuntu0.18.04) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0, 64-bit

**Comment by rafaelthca** [comment]
Hi @ccurvey,

Yes, current version of OmniDB recreates the database connection every time a query is executed in the Query Tab, that is why your SET is going away. Console tab keeps connection open and you should be able to execute what you want.

This is the main change in the next release. Query tab is being improved to allow disable autocommit and keep connections open in the Query tab.

Regards,

Rafael.

**Comment by ccurvey** [comment]
Makes sense.  thanks for the explanation

**Comment by wind39** [comment]
Hi @ccurvey ,

We have implemented several improvements for Console Tab and Query Tab in 2.12.0, we just released it. Would you please test it and provide us your valuable feedback? Thanks in advance!

Regards,

William

**Comment by wind39** [comment]
Closing this now.
