### ISSUE TITLE
Feature: Show trigger function after expanding trigger.

### ISSUE THREAD

**Issue by kobaz** [OmniDB/OmniDB#717]
pgadmin3 has this feature as shown in the attachments.  This would be a great additional to omni as most of my work is with triggers and I need to go back to pgadmin to do those things since it's much more efficient.

![screen shot 2018-10-01 at 5 08 23 pm](https://user-images.githubusercontent.com/1695852/46315924-b2322180-c59c-11e8-9e07-52caab1e6529.png)

![screen shot 2018-10-01 at 5 08 31 pm](https://user-images.githubusercontent.com/1695852/46315910-a8a8b980-c59c-11e8-81b5-f63d102701e9.png)

**Comment by wind39** [comment]
Hi @kobaz ,

This is partially implemented in 2.12.0. Trigger function is shown under trigger, but to see Properties and DDL about the trigger function, you should find it under "Trigger Functions" tree node.

Please let us know if this helps for now. We plan to implement full support for this as you requested in next release.

Regards,

William

**Comment by kobaz** [comment]
Hi,

Thanks for the add.... it is minimally helpful.  It basically shows the same information that's already in the DDL for the trigger itself. 

The specific wish-list item for this, is to actually be able to load up and show the function itself in the code/query error when expanding and then clicking on the function that the trigger utilizes.

**Comment by wind39** [comment]
Hi @kobaz ,

OmniDB 2.13.0 is being released today. Inside every trigger node in the tree view, there is a complete trigger function node, with same functionality as the nodes under the "Trigger Functions" node.

I hope that helps you now :)

Best regards,

William

**Comment by wind39** [comment]
Closing this issue now.
