### ISSUE TITLE
Improvement: Edit data takes an extremely long time to load for an empty table

### ISSUE THREAD

**Issue by kobaz** [OmniDB/OmniDB#718]
It seems like this is occurring for all tables, not just empty ones.

See screen cap:
https://imgur.com/a/3SLddTW

**Comment by kobaz** [comment]
Looks like this may be solved in 2.12 ?

I haven't run into this issue with 2.12 yet... were there any fixes to specifically target this?

**Comment by wind39** [comment]
Hi @kobaz ,

This is fixed, closing this now.

Regards,

William
