### ISSUE TITLE
Does Omnidb works in Redhat linux flavour?

### ISSUE THREAD

**Issue by pilayar76** [OmniDB/OmniDB#719]
Hi All,

Can anyone help me in letting know whether omnidb centos7 distribution works with Redhat 7 and Oracle Linux 7 flavour?

I am able to install but while logging in not getting any other functionality except adding users. Not even able to sign out.

Please help

**Comment by wind39** [comment]
Hi,

We are performing some usability tests on RedHat 7.

Regards,

William

**Comment by wind39** [comment]
Hi @pilayar76 ,

We have performed tests of OmniDB 2.17 (to be released tomorrow) against RedHat 7, CentOS 7 and Fedora 30/31. It runs fine. You can see in the screenshot below OmniDB app 2.17 running on RedHat 7:

![image](https://user-images.githubusercontent.com/7719686/70177366-fe08bb00-16b8-11ea-9f54-5e1ff7c496ca.png)

Please try downloading OmniDB 2.17 tomorrow after the release, and please let me know if you find any issues.

Thanks and regards,

William

**Comment by pilayar76** [comment]
Thank you
