### ISSUE TITLE
Feature: Server Groups

### ISSUE THREAD

**Issue by kobaz** [OmniDB/OmniDB#731]
It would be great to be able to group servers in the connections list.

We have servers we connect to on a regular basis for development work, another set for testing work, and then another set for live production systems and organizing these all in the connections list is a little cumbersome at the moment.

**Comment by rafaelthca** [comment]
Good idea. Any suggestions on how this should be implemented? We have connections at the moment, these are opened in connection tabs.

One idea is to be able to select Connection Groups in the dropdown selector, and the connections belonging to that group would appear in the tree.

**Comment by francoisoger** [comment]
Hi, just to give a big +1 to this feature! And I think that your proposal is good @rafaelthca!

Hope to see this in a future realease 👍

**Comment by wind39** [comment]
@kobaz , @azbok and @francoisoger ,

OmniDB 2.13.0 is being released today containg this new feature. We will keep this issue open for a while to receive any feedback from you.

Regards,

William

**Comment by wind39** [comment]
Closing this issue now.
