### ISSUE TITLE
Copy text with right-click in SQL results table

### ISSUE THREAD

**Issue by brylie** [OmniDB/OmniDB#734]
When viewing SQL results, it is often desirable to copy a single row, column, or cell value. Currently, the user has to right click, then click view, then select the text, then hit ctrl-C.

# Feature request
Add a feature to right-click menu, allowing user to copy cell value.

Right click -> copy

**Comment by wind39** [comment]
Hi @brylie ,

We just released 2.12.0 with this feature you requested. Would you be kind to test it and provide your feedback? Thanks in advance!

Regards,

William

**Comment by wind39** [comment]
Closing this now.
