### ISSUE TITLE
History Icon missing in 2.12.0 -  Can't get to SQL history anymore

### ISSUE THREAD

**Issue by hunsakerbn** [OmniDB/OmniDB#754]
After upgrading to version 2.12 server on RHEL 6.2, there does not seem to be any way to get to the SQL history, as there is no longer an Icon for it, and there doesn't seem to be a shortcut key to do this.

**Comment by wind39** [comment]
Hi @hunsakerbn ,

Thanks for reaching out. Command history was moved into the Query Tab:

![image](https://user-images.githubusercontent.com/7719686/47379781-3f672280-d6d2-11e8-8ade-b3cda3d1ba65.png)

Please let us know if it works for you.

Regards,

William

**Comment by hunsakerbn** [comment]
Thanks.  I found it.  I guess the documentation about the command history still needs to be brought up to date.

**Comment by wind39** [comment]
Hi @hunsakerbn ,

Yes, it does. We are working on that. Full documentation should be updated very soon.

I'm closing this issue, then.

Regards,

William

**Comment by rafaelthca** [comment]
Command history in now per connection. Before 2.12 you could see queries from MySQL and PG in the same grid, nasty!

**Comment by hunsakerbn** [comment]
Yes. I like the per connection history much better!
