### ISSUE TITLE
always starts in a maximized window

### ISSUE THREAD

**Issue by ccurvey** [OmniDB/OmniDB#755]
2.12.0

Whenever I start the app, it starts in a full-screen window, even if I quit the app in a non-full screen window.

It also does not remember which tabs I had open

**Comment by wind39** [comment]
Hi @ccurvey ,

OmniDB 2.12.0 now remembers the names and contents of the tabs that were open. As implementation changed, it won't remember the tabs that you have opened on previous releases.

Please try opening some tabs in 2.12, renaming them, execute them (they need to contain a valid SQL to be remembered) then restart OmniDB to see if they are there.

As for the full-screen window: previously it started on a windowed 800x600 window, and most people simply had to maximize it. Now we decided to always open full-screen. OmniDB still does not remember window size or position of when it was closed, we plan to implement that feature for next releases.

Regards,

William

**Comment by wind39** [comment]
Hi,

Closing this one, as the window will always be open maximized.

Regards,

William
