### ISSUE TITLE
request:  execute query after prompting for password

### ISSUE THREAD

**Issue by ccurvey** [OmniDB/OmniDB#757]
2.12.0

1) open app, go to query tab.  System will be disconnected
2) Highlight SQL, press "execute" button
3) System prompts for password (good!)
4) User enters correct password.

At this point, the existing system just stops.  It would be great if the system could actually execute the highlighted SQL.  (Yeah, I can push the "execute" button again, but I'm lazy.)

**Comment by wind39** [comment]
Hi @ccurvey ,

Thanks for the request. We tried to implement exactly what you mention, but couldn't. In the next release we hope to tackle this issue. In the meantime, I'm going to keep this issue open.

Regards,

William

**Comment by wind39** [comment]
Hi @ccurvey ,

This was implemented in OmniDB 2.13.0 that we are releasing today. Please try it and provide feedback on this issue. Thanks in advance :)

Regards,

William
