### ISSUE TITLE
error in \d command

### ISSUE THREAD

**Issue by erdusa** [OmniDB/OmniDB#760]
Now, again, in the new version 2.12.0  does not work the \d command

![image](https://user-images.githubusercontent.com/36895220/47514201-68f48b00-d845-11e8-897c-1b5b4c6cee4f.png)

**Comment by wind39** [comment]
Hi @erdusa ,

Thanks for reporting. It will be fixed in 2.12.1.

Regards,

William

**Comment by wind39** [comment]
Hi @erdusa ,

I was investigating this. It seems like a re-occurrence of issue #424 . However, `pgspecial` package has accepted my [commit](https://github.com/dbcli/pgspecial/pull/58/commits/6b270530ef99c67df892414c9e6f4e4580c691b3).

Please provide some more details:

- Operating system version;
- PostgreSQL version;
- OmniDB flavor (app or server).

Thanks in advance.

William

**Comment by erdusa** [comment]
Hi @wind39 

Operating system version= windows 10
PostgreSQL version=10.5
OmniDB flavor= app

**Comment by wind39** [comment]
Hi @erdusa ,

This was a packaging issue in Windows packages. It will be fixed in 2.12.1 very soon.

Regards,

William

**Comment by wind39** [comment]
Hi @erdusa ,

New packages for OmniDB 2.13.0 for Windows now consider the up-to-date component. Can you please try and give us your valuable feedback? Thanks in advance!

Best regards,

William

**Comment by erdusa** [comment]
Hi @wind39 

This fix works well

Thank you
