### ISSUE TITLE
Monitoring tab - Backends Pie chart - colours re-assigned on refresh

### ISSUE THREAD

**Issue by stevenwinfield** [OmniDB/OmniDB#762]
OmniDB 2.11.0, Windows

Every time the "Backends" widget refreshes it chooses new colours for each of the dbs in the cluster.
It also re-animates drawing the pie chart.

Both features are somewhat annoying :-)

**Comment by wind39** [comment]
Hi @stevenwinfield ,

Last week we released OmniDB 2.14 with a fix for this issue. We will keep this open for a few more days in case you want to provide us with your feedback.

Thanks in advance,

William

**Comment by stevenwinfield** [comment]
Works perfectly. Thanks!
