### ISSUE TITLE
Monitoring - CPU Usage chart - poorly rendered when #CPUs is high

### ISSUE THREAD

**Issue by stevenwinfield** [OmniDB/OmniDB#763]
OmniDB 2.11.0, Windows

The CPU Usage chart is pretty much unreadable when there are a few 10s of CPUs:

![image](https://user-images.githubusercontent.com/1327493/47571211-edbbd380-d92f-11e8-982c-ded33b349b20.png)

**Comment by wind39** [comment]
Hi @stevenwinfield ,

Last week we released OmniDB 2.14 with a fix for this issue. Now charts are rendered with a vertical scroll bar if needed.

Can you please try it? Your feedback will be much appreciated.

Regards,

William

**Comment by stevenwinfield** [comment]
Much better, thanks!
