### ISSUE TITLE
Monitoring - Column widths are not adjusted when the monitoring tab doesn't have focus

### ISSUE THREAD

**Issue by stevenwinfield** [OmniDB/OmniDB#764]
OmniDB 2.11.0, Windows.

If a monitoring widget's values are updated while the monitoring tab is not visible then the grid's columns are not auto-resized until the next refresh, so clicking on the monitoring tab shows you something like this until then:

![image](https://user-images.githubusercontent.com/1327493/47579463-f1595580-d943-11e8-979f-e20218fef705.png)

**Comment by wind39** [comment]
Hi @stevenwinfield ,

We are releasing OmniDB 2.13.0 today, with a fix for this issue.

I'll keep this issue open in case you want to give us your feedback, for which I thank you in advance :)

Best regards,

William

**Comment by stevenwinfield** [comment]
Confirmed working as expected. Thanks!
