### ISSUE TITLE
Query results

### ISSUE THREAD

**Issue by anothergituser** [OmniDB/OmniDB#766]
Using latest version 2.12.0 the data window does not show new records when running the query again. Opening a new query tab and running the same query will display the updated result set but the old tab still displays the incomplete results.

**Comment by wind39** [comment]
Hi @anothergituser ,

Please provide more details on how we can simulate this. Is autocommit disabled?

Regards,

William

**Comment by anothergituser** [comment]
Fedora 28, Firefox 64.0b4 (64-bit), Python 3.6.6 (same thing in chrome) and omnidb 2.12.0
Autocommit is on by default in mysql and mariadb and i don't have this issue with other tools, does OmniDB have a separate setting for autocommit?
Run a query like select * from some table
Using another tool add a new record to the same table and in omnidb in the same query tab rerun the query, in my case the new row does not show up after execution.
Also it does not show up in the console tab.
If you open a new query tab and run the same query the new record does show up.
Also if you run an update command on the table using omnidb it says done but the row is not changed.
It does look like an autocommit issue but like i said , other tools don't have this problem.
Thanks

**Comment by rafaelthca** [comment]
@anothergituser 

I was able to simulate it. In 2.12 OmniDB doesn't close and reopens connections in every query request, like we used to do in previous versions. The connection library we are using has autocommit disabled by default. So if you have a query tab that already executed a query, this tab is inside a transaction and won't see changes done after the transaction was opened. You will have to manually commit.

Annoying bug. Will have to provide a fix for that. We'll release a minor 2.12.1 with several fixes. Thanks for opening the issue.

Rafael.

**Comment by rafaelthca** [comment]
Does that happen when you perform a specific action in the interface? Is that when performing queries?

**Comment by anothergituser** [comment]
Can't really say, it can happen on any action after some time, did not check how much.
This is the message
<div class="div_alert_text">Session object was destroyed, click <a href="Login.aspx">here</a> to be redirected to login screen or finish what you were doing and reload the page.</div>

**Comment by rafaelthca** [comment]
Fixed both issues.

1- Autocommit is true in mysql connections now. In the future the query tabs will allow to change this, like postgresql tabs.
2- Default token names changed. Both sessionid and csrftoken have new names.

Thanks @anothergituser.

**Comment by wind39** [comment]
Hi @anothergituser ,

We are releasing OmniDB 2.13.0 today, with a fix for this issue.

I'll keep this issue open in case you want to give us your feedback, for which I thank you in advance :)

Best regards,

William

**Comment by wind39** [comment]
Closing this issue now.
