### ISSUE TITLE
Error closing error window

### ISSUE THREAD

**Issue by erdusa** [OmniDB/OmniDB#767]
When OmniDB shows error window, I can't close it, I click on the red X and it doesn't close

![image](https://user-images.githubusercontent.com/36895220/47755916-1ca6b200-dc6e-11e8-93d1-b382d0000edd.png)

**Comment by wind39** [comment]
Hi @erdusa ,

Thanks for reporting this, it will be fixed for 2.12.1.

Regards,

William

**Comment by wind39** [comment]
Hi @erdusa ,

We are releasing OmniDB 2.13.0 today, with a fix for this issue.

I'll keep this issue open in case you want to give us your valuable feedback, as always.

Best regards,

William

**Comment by erdusa** [comment]
Hi @wind39 

This fixed the problem

Thank you
