### ISSUE TITLE
OmniDB doesn't export all rows

### ISSUE THREAD

**Issue by erdusa** [OmniDB/OmniDB#769]
OmniDB exports less rows than it shows in grid. Here is 2 screen shot:

In grid

![image](https://user-images.githubusercontent.com/36895220/47934579-a12f4580-dea5-11e8-8e2e-586e10c91014.png)

Csv opens with Excel

![image](https://user-images.githubusercontent.com/36895220/47934540-7c3ad280-dea5-11e8-91a4-829230bf95a7.png)

**Comment by ccurvey** [comment]
confirmed.  I had 1062 rows in my result set, but only 1000 were exported.

**Comment by wind39** [comment]
Hi @erdusa and @ccurvey ,

Thanks for reporting. I just fixed it, the fix is coming in 2.12.1 soon.

Regards,

William

**Comment by ziodave** [comment]
In my case I see up to 2.000 rows in the export (I have ~2.700 in the grid).

**Comment by wind39** [comment]
Hi @erdusa , @ccurvey and @ziodave ,

We are releasing OmniDB 2.13.0 today, with a fix for this issue.

I'll keep this issue open in case you want to give us your feedback, for which I thank you in advance :)

Best regards,

William

**Comment by ccurvey** [comment]
I can confirm that this is fixed in 2.13.  thanks!

**Comment by erdusa** [comment]
Hi, I exported 1.000.000 of rows and it worked, thank you
