### ISSUE TITLE
Support running via WSGI on path other than /

### ISSUE THREAD

**Issue by df7cb** [OmniDB/OmniDB#776]
Hi,

I would like to run OmniDB as a WSGI application from apache2 in the /omidb location. Unfortunately, it seems to insist running in /, especially for the Ajax calls. Could that be made configurable? (#687 seems to be a similar issue.)

Thanks.

**Comment by rafaelthca** [comment]
Hi @ChristophBerg,

Will implement an option to allow specifying a custom path in the config file.

Rafael.

**Comment by RabbidDog** [comment]
+1 
This feature would be highly appreciated

**Comment by rafaelthca** [comment]
Implemented. Coming out with 2.16.0

**Comment by wind39** [comment]
Hi @df7cb , @RabbidDog ,

We released 2.16.0 with this implementation. Keeping this issue open for a few more days, any feedback will be much appreciated.

Regards,

William

**Comment by RabbidDog** [comment]
Feedback on the bug:
Works as expected. Tested with K8s and ingress-nginx .

**Comment by wind39** [comment]
hi @RabbidDog ,

Thanks for your feedback. Closing this issue now.

Regards,

William
