### ISSUE TITLE
Feature: Add user defined types in the object browser

### ISSUE THREAD

**Issue by francoisoger** [OmniDB/OmniDB#782]
Hi,

coming from PgAdmin and found OmniDB very good. The thing I'm missing is the display of user defined types in the left menu.

I used this in some DBs and it would be very useful to show these.

Is it a possible enhancement?

**Comment by wind39** [comment]
Hi @francoisoger ,

Thanks for your feedback. Support to user defined types is in our roadmap, it will be implemented soon. We will keep this issue open to notify you when we have any news about this.

Regards,

William Ivanski

**Comment by francoisoger** [comment]
Great to read that and thanks for your (very) quick answer!

Regards

**Comment by wind39** [comment]
Hi @francoisoger ,

We released OmniDB 2.14 last week with this feature. Now it is possible to see and manage custom data types and domains in the tree view. Your feedback would be much appreciated.

Regards,

William

**Comment by francoisoger** [comment]
Hi @wind39 ,

I've just downloaded and installed the 2.14 version and this new feature is perfect! Thanks!

Will raise one or two more feature ideas and I think that omnidb will be a perfect match with my needs!

**Comment by wind39** [comment]
Hi @francoisoger ,

Thank you for your feedback :)

Best regards,

William
