### ISSUE TITLE
Could set configuration to service on RHEL 7.5

### ISSUE THREAD

**Issue by PauloLaScience** [OmniDB/OmniDB#788]
When I start omnidb-server as:
`omnidb-server -p 8000 -w 25482 -H 0.0.0.0`
No problem to connect from my PC browser so I modify omnidb.conf
`listening_address = 0.0.0.0` the service don't use this config:
`[root@pgsqlmonitor-001 omnidb-server][0]# systemctl status omnidb.service
* omnidb.service - OmniDB server daemon
   Loaded: loaded (/etc/systemd/system/omnidb.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
 
Nov 29 09:18:42 pgsqlmonitor-001.pol.be bash[26736]: Checking port availability...
Nov 29 09:18:42 pgsqlmonitor-001.pol.be bash[26736]: Starting websocket server at port 25482.
Nov 29 09:18:42 pgsqlmonitor-001.pol.be bash[26736]: Starting OmniDB server...
Nov 29 09:18:42 pgsqlmonitor-001.pol.be bash[26736]: Checking port availability...
Nov 29 09:18:42 pgsqlmonitor-001.pol.be bash[26736]: Starting server OmniDB 2.12.0 at 127.0.0.1:8000.
Nov 29 09:18:43 pgsqlmonitor-001.pol.be bash[26736]: User database version 2.12.0 is already matching server version.
Nov 29 09:18:43 pgsqlmonitor-001.pol.be bash[26736]: Open OmniDB in your favorite browser
Nov 29 09:18:43 pgsqlmonitor-001.pol.be bash[26736]: Press Ctrl+C to exit
`
As you can see in the screenshot of `systemctl status omnidb.service`

I try also to execute omnidb-config-server -d /opt/omnidb-server

Regards,
Paul-Emmanuel Devadder

_Originally posted by @PauloLaScience in https://github.com/OmniDB/OmniDB/issues/600#issuecomment-442790716_

**Comment by wind39** [comment]
Hi @PauloLaScience ,

Thanks for reaching out, I replied to you [in #600](https://github.com/OmniDB/OmniDB/issues/600#issuecomment-442879862).

Regards,

William

**Comment by wind39** [comment]
Hi @PauloLaScience ,

We are releasing 2.13.0 today, and the `omnidb` server will use the configuration file `/etc/omnidb.conf`.

I'll keep this issue open in case you want to give us your valuable feedback.

Thanks in advance,

William

**Comment by wind39** [comment]
Closing this issue now.
