### ISSUE TITLE
No way to browse custom types (created with CREATE TYPE)

### ISSUE THREAD

**Issue by qris** [OmniDB/OmniDB#793]
In pgAdmin, one of the types of browsable object that can be enabled is "type". But it doesn't seem possible to enable them in OmniDB.

For example, I can create a new ENUM type:

    create type foo as enum ('bar', 'baz');

But then I have no way to browse it:

![image](https://user-images.githubusercontent.com/754175/49861371-96949400-fdf3-11e8-9242-1b45112aafbb.png)

**Comment by qris** [comment]
Great, thanks. Closing this one then.

**Comment by wind39** [comment]
Hi @qris ,

We have released this feature in OmniDB 2.14 last week.

Regards,

William
