### ISSUE TITLE
Problem installing Omnidb-app on Centos

### ISSUE THREAD

**Issue by Agwurme** [OmniDB/OmniDB#801]
downloaded the correct version for Centos and arranged for my hosting company to install the rpm. They did so and I can run the command omnidb-app but nothing happens (no output, no errors) and there in no .db file or anything. They installed it into /usr/bin. Any ideas?

**Comment by wind39** [comment]
Hi @Agwurme ,

Thanks for reaching out. If you are planning on host OmniDB, the correct flavor would be "server" and not "app". OmniDB server is a web server that allows users connections from other machines via a web browser, and OmniDB app is a desktop application meant to be installed in your local machine.

Also please bear in mind that OmniDB app requires CentOS 7 or better, while there are packages for OmniDB server to be installed on CentOS 6 or CentOS 7.

Please let me know if I understood your issue correctly.

Best regards,

William

**Comment by Agwurme** [comment]
Hi William,
Yes you are correct and I have now requested my hosting company to install the server edition. It is Centos 7 it will be running on, so that is not a problem, but it is an online server so that is what I really need.

Thanks

Dave G
