### ISSUE TITLE
OmniDB breaks at years BC (postgres)

### ISSUE THREAD

**Issue by pgaro** [OmniDB/OmniDB#810]
Hello,

OmniDB breaks at years BC. For instance the query 

> select '0001-01-01 BC'::timestamp;

breaks with

> year 0 is out of range

Regards
pgaro

**Comment by pgaro** [comment]
Also mentioned in #708 .

Regards
pgaro

**Comment by wind39** [comment]
Hi @pgaro ,

I managed to fix this:

![image](https://user-images.githubusercontent.com/7719686/53177260-77259e80-35ce-11e9-9334-7ad12efc3f9a.png)

The fix is going out on next release, 2.15, which will be published on April this year.

Best regards,
William
