### ISSUE TITLE
Service file /etc/systemd/system/omnidb.service is missing on RHEL 7.5

### ISSUE THREAD

**Issue by PauloLaScience** [OmniDB/OmniDB#817]
Hi
I upgrade Omnidb 2.12 to 2.13 and omnidb.Service is missing.
I will restore the file from backup.
But config file /etc/omnidb.conf is correct and working.

Kind regards,
Paulem

**Comment by PauloLaScience** [comment]
Restore of /etc/systemd/system/omnidb.service is working fine.
systemctl daemon-reload
systemctl start omnidb

Kind regards,
Paulem

**Comment by wind39** [comment]
Hi @PauloLaScience ,

Thanks for reaching out. The file `/etc/systemd/system/omnidb.service` in versions prior to 2.13 didn't use the config file `/etc/omnidb.conf`. So please make sure your `omnidb.service` file has the following content:

```
[Unit]
Description=OmniDB server daemon
After=network.target

[Service]
Type=forking
ExecStart=/bin/bash -c "/opt/omnidb-server/omnidb-server -c /etc/omnidb.conf &"
RemainAfterExit=yes
User=root
Group=root

[Install]
WantedBy=multi-user.target
```

I will investigate about the file being missing after an upgrade from 2.12 to 2.13 on RHEL 7.5.

Best regards,

William

**Comment by wind39** [comment]
Hi @PauloLaScience ,

Thank you very much for reporting this. I managed to simulate and fixed this already. The fix will come in next OmniDB version. I will keep this issue open until then.

Regards,

William

**Comment by PauloLaScience** [comment]
Thanks

**Comment by wind39** [comment]
Hi @PauloLaScience ,

Last week we released OmniDB 2.14 with a fix for this issue. Can you please try it and provide your valuable feedback?

Thanks in advance,

William

**Comment by wind39** [comment]
Closing this.

**Comment by PauloLaScience** [comment]
Sorry for late notice but issue fixed. Working fine on RHEL 7.5
