### ISSUE TITLE
Edit Data não traz nenhuma informação

### ISSUE THREAD

**Issue by thiago-mattos** [OmniDB/OmniDB#818]
Bom dia, ao clicar em uma tabela e acessar Data Actions>EditaData, não me traz nenhuma informação da tabela, somente o nome da chave primária no seguinte formato
'"nomeDaChavePrimaria"'

**Comment by wind39** [comment]
Bom dia, Thiago, tudo bem?

Obrigado por entrar em contato. A funcionalidade `Data Actions -> Edit Data` permite que o usuário altere dados em uma tabela. Para maiores informações, por favor consulte a documentação sobre a funcionalidade aqui: https://omnidb.org/en/documentation-en/data-management-en

Se ainda assim você tiver dúvidas, por favor nos retorne com mais detalhes sobre a sua necessidade, para que possamos melhor atendê-lo.

William

**Comment by thiago-mattos** [comment]
William, obrigado pela resposta, já verifiquei a documentação mas ainda não consegui. Se eu vou na opção Query Data, os registros são listados normalmente, porém na edit data, que já trás por padrão essa consulta abaixo, não retorno nenhum registro, vou deixar abaixo também o link do print para teres uma ideia: 

select * from public "Atividade" t
order by t."CodigoInternoAtividade"

https://ibb.co/WzPgjJL

**Comment by wind39** [comment]
Olá, @thiago-mattos ,

Muito obrigado pelo print, agora parece bem claramente que é um bug. Vamos tentar investigar e resolver isso para a próxima versão.

Te informarei sobre o progresso por aqui :)

William

**Comment by thiago-mattos** [comment]
@wind39 obrigado pela atenção, fico no aguardo!

**Comment by wind39** [comment]
@thiago-mattos ,

Imaginando que o problema seria causado pela PK com aspas, tentei fazer um teste simples para simular o problema. Criei uma tabela:

```
CREATE TABLE "Atividade" ("CodigoInternoAtividade" integer primary key);
```

Mas o EditData funcionou como deveria:

![image](https://user-images.githubusercontent.com/7719686/50522079-3ae32f80-0ab0-11e9-86ea-1a343108ec19.png)

Então por favor envie mais informações para nos ajudar a simular o problema, por exemplo a versão do PostgreSQL que você está usando e, se possível, a DDL de criação dessa tabela.

William

**Comment by thiago-mattos** [comment]
Willian, a versão do Postgres é 9.6.8,  criei uma outra Tabela para teste, somente com uma chave estrangeira, continuou com o mesmo problema.

CREATE TABLE "Teste" (
    "TesteInternoAtividade" integer NOT NULL
);
ALTER TABLE "Teste" ADD CONSTRAINT "Teste_pkey"
  PRIMARY KEY ("TesteInternoAtividade");

ALTER TABLE "Teste" OWNER TO postgres;


**Abaixo segue a DDL da tabela original .**

-- Type: TABLE ; Name: Atividade; Owner: postgres

CREATE TABLE "Atividade" (
    "CodigoInternoAtividade" integer NOT NULL,
    "CodigoEmpresaAtividade" integer NOT NULL,
    "NomeAtividade" character varying(50) NOT NULL,
    "DataUltimaAlteracao" timestamp(0) without time zone,
    "UsuarioUltimaAlteracao" integer,
    "CodigoEmpresaIdentificador" integer NOT NULL,
    "CodigoInternoIdentificador" integer NOT NULL,
    "OrigemUltimaAlteracao" character varying(10),
    "AtivoAtividade" boolean,
    "CodigoConversao" text
) WITH OIDS;


ALTER TABLE public."Atividade" ALTER "CodigoInternoAtividade" SET DEFAULT nextval('public."Atividade_CodigoInternoAtividade_seq"'::regclass);
ALTER TABLE public."Atividade" ALTER "CodigoEmpresaAtividade" SET DEFAULT 0;
ALTER TABLE public."Atividade" ALTER "AtivoAtividade" SET DEFAULT false;

ALTER TABLE "Atividade" ADD CONSTRAINT "Atividade_CodigoInternoAtividade_PK"
  PRIMARY KEY ("CodigoInternoAtividade");

CREATE UNIQUE INDEX "Atividade_CodigoEmpresa_UpperNome_I" ON public."Atividade" USING btree ("CodigoEmpresaAtividade", ts_convertetextoacentuado(("NomeAtividade")::text));
CREATE INDEX "Atividade_DataUltimaAlteracao_I" ON public."Atividade" USING btree ("DataUltimaAlteracao");
CREATE UNIQUE INDEX "Atividade_EmpresaIdentificador_InternoIdentificador_I" ON public."Atividade" USING btree ("CodigoEmpresaIdentificador", "CodigoInternoIdentificador");

CREATE TRIGGER "TriggerGravaIdentificador" BEFORE INSERT ON "Atividade" FOR EACH ROW EXECUTE PROCEDURE "FuncaoGravaIdentificadorAtividade"();
CREATE TRIGGER "TriggerGravaRegistroExcluido" AFTER DELETE ON "Atividade" FOR EACH ROW EXECUTE PROCEDURE ts_gravaregistroexcluido();
CREATE TRIGGER "TriggerGravaUltimaAlteracao" BEFORE INSERT OR UPDATE ON "Atividade" FOR EACH ROW EXECUTE PROCEDURE "FuncaoGravaUltimaAlteracao"();

ALTER TABLE "Atividade" OWNER TO postgres;

**Comment by wind39** [comment]
Olá, @thiago-mattos ,

Muito obrigado pelas informações. Conseguimos simular o problema. Detalhe que para o problema acontecer, é necessário o seguinte:

- Nome da coluna da PK precisa ter aspas
- Tabela precisa ter pelo menos 1 registro

![image](https://user-images.githubusercontent.com/7719686/50525410-6e2eba00-0ac2-11e9-9481-f966f10d9d7b.png)

Também já conseguimos corrigir o bug:

![image](https://user-images.githubusercontent.com/7719686/50525429-9ae2d180-0ac2-11e9-8004-b98191baaa09.png)

A correção foi feita [neste commit](https://github.com/OmniDB/OmniDB/pull/820/commits/0f596a6fd3ae8dbb57c9951045c79423a0a86b01) e será publicada na próxima release do OmniDB.

Manteremos essa issue aberta para te notificar quando a próxima release do OmniDB for lançada. Novamente agradecemos por relatar o bug e por ajudar a melhorar o OmniDB :)

Atenciosamente,

William

**Comment by thiago-mattos** [comment]
Willian, obrigado pela agilidade e dedicação!

**Comment by wind39** [comment]
Olá, @thiago-mattos ,

Semana passada lançamos o OmniDB 2.14 corrigindo este problema. Você poderia tentar novamente por favor?

Agradeço desde já,

William

**Comment by thiago-mattos** [comment]
Boa tarde @wind39 , testei no mesmo dia que foi lançada a atualização, está funcionando perfeitamente agora, obrigado pela atenção!

**Comment by wind39** [comment]
Obrigado por confirmar :)
