### ISSUE TITLE
Sorting by group in 'Connections' does not work

### ISSUE THREAD

**Issue by kobaz** [OmniDB/OmniDB#823]
Looks like everything is nicely sortable in 'Connections', except for 'Group'.  If i want to make all the servers that are checked, show up at the top (or bottom).  I would expect to sort the 'Group' column.  But the sorting of the checked/unchecked seems to be nondeterministic.

**Comment by wind39** [comment]
Hi @kobaz ,

Thanks for reaching out, we will investigate.

Hi @barthisrael ,

Would you please take a look at this?

Thanks in advance,

William

**Comment by barthisrael** [comment]
Hi @wind39 ,

Sure, I'll take a look soon.

Sorry for the delay.

**Comment by wind39** [comment]
Hi @kobaz ,

We just released OmniDB 2.15, containing an implementation from @barthisrael which allows users to sort connections by group in connection grid.

Can you please try it and provide your valuable feedback?

Keeping this ticket open for a few more days.

Regards,

William

**Comment by wind39** [comment]
Closing this now.
