### ISSUE TITLE
Foreign key displayed twice

### ISSUE THREAD

**Issue by kobaz** [OmniDB/OmniDB#828]
Just created a foreign key and it's duplicated in the gui.

If you right click and do a drop on one of them, they both go away.

![db](https://user-images.githubusercontent.com/1695852/50548697-689ab680-0c1f-11e9-8c65-21b0a52f20d0.png)

**Comment by wind39** [comment]
Hi @kobaz ,

Thanks for reporting this. What is the database engine?

Regards,

William

**Comment by kobaz** [comment]
I'm actually having trouble reproducing this.  Maybe some changes in the latest release have fixed this issue?  Not sure... I'll keep an eye out for recurrence.

**Comment by wind39** [comment]
Hi @kobaz ,

Closing this now. Please open a new ticket if you see this again.

Thanks and regards,

William
