### ISSUE TITLE
Duplicating Foreign keys during conversion from MariaDB to PostgreSQL

### ISSUE THREAD

**Issue by lucasmnovais** [OmniDB/OmniDB#83]
When I tried to convert from MariaDB to PostgreSQL in the process of create tables the application inserted the foreigns keys as normal column, and when tried to add the foreign key to the database I got this error:
**foreign key referenced-columns list must not contain duplicates**

**Comment by wind39** [comment]
Please download [OmniDB 1.6.4](https://github.com/OmniDB/OmniDB/releases/tag/v1.6.4) and try to perform the conversion again.

**Comment by lucasmnovais** [comment]
I've updated to 1.6.4 and tried make the conversion again. Unfortunately I still got the same error.
The application tries do an alter table and stops on this error, my database ends with no relationship at all and no data in most tables.

**Comment by wind39** [comment]
Can you send the conversion log generated by OmniDB?
Also, if you could send a dump of (a part of) your database, so we could replicate the error here, it would be better.

**Comment by wind39** [comment]
Unfortunately the C# OmniConvert is not supported anymore. We plan to implement this feature into OmniDB Python version. Closing this for now.
