### ISSUE TITLE
Linux Copy/Paste doesn't always work

### ISSUE THREAD

**Issue by kobaz** [OmniDB/OmniDB#830]
Steps to reproduce:

Select text from a panel inside omni
Ctrl-c
Move cursor to another panel inside omni
Ctrl-v

Meanwile, this process results in 100% success when doing a ctrl-v paste into another application like a notepad
![gifrecord_2018-12-30_144449](https://user-images.githubusercontent.com/1695852/50550603-8f69e480-0c41-11e9-9d01-bf052abac422.gif)

**Comment by wind39** [comment]
Hi @kobaz ,

Recently we released OmniDB 2.15 with a major upgrade on the Electron component.

Can you please try to see if it had fixed this issue for you?

Regards,

William

**Comment by wind39** [comment]
Closing this now.
