### ISSUE TITLE
Use comma as default delimiter in CSV, or allow configuration

### ISSUE THREAD

**Issue by brylie** [OmniDB/OmniDB#835]
When exporting a results table as CSV, the default delimiter seems to be a semicolon. Please allow the delimiter to be configured, and/or use comma as default.

**Comment by wind39** [comment]
Hi @brylie ,

Thanks for reaching out. The CSV delimiter can be configured in the User Options, as you can see here:

![image](https://user-images.githubusercontent.com/7719686/51378441-6fb53600-1af4-11e9-9f5d-5745356b7ff3.png)

Best regards,

William
