### ISSUE TITLE
How to create dashboard in App version

### ISSUE THREAD

**Issue by Ssubhan** [OmniDB/OmniDB#839]
Team,

Please let me know how to create dashboard in App version

**Comment by wind39** [comment]
Hi @Ssubhan ,

The Monitoring Dashboard can be accessed when you right-click on the tree view root node and go to `Monitoring -> Dashboard`. Note that currently it is only accessible when managing PostgreSQL databases.

I hope this answers your question. If not, please let me know.

Regards,

William

**Comment by wind39** [comment]
Closing this.
