### ISSUE TITLE
Oracle error

### ISSUE THREAD

**Issue by davichowar** [OmniDB/OmniDB#840]
Hello, when i want to connect oracle DB with OmniDB App i have get the following error:

Oracle is not supported. Please install it with 'pip install Spartacus[oracle]'.

I already install anaconda and execute "pip install Spartacus[oracle]" on anaconda prompt, but it not fix the error. I install too Oracle Instant Client on OmniDB installation folder, it not fix the error.

**Comment by wind39** [comment]
Hi @davichowar ,

Thanks for reaching out. What is the OmniDB version and what is the operating system you are using?

Regards,

William

**Comment by davichowar** [comment]
Thanks for your response @wind39 

OmniDB version: 2.13.0
OS: Windows 10 Pro 64bits

**Comment by anubischpc** [comment]
I have the same Issue, someone can help us?

**Comment by wind39** [comment]
Hi @davichowar and @anubischpc ,

Please extract the contents of the Oracle Instant Client zip file, it will create a folder called `instantclient_x_y`. Copy the contents of this folder into the folder `C:\OmniDB-app\resources\app\omnidb-server\`, and not the folder `instantclient_x_y` itself.

Best regards,

William

**Comment by wind39** [comment]
Closing this now.
