### ISSUE TITLE
Show PostgreSQL 10+ partitioned tables recursively in the tree view

### ISSUE THREAD

**Issue by wind39** [OmniDB/OmniDB#842]
With PostgreSQL 10+ native partitioning support, a table can be partitioned but also a partition at the same time.
In the tree view, each table is fully functional, and we can see columns, triggers, indexes, etc. But in the Partitions node of a given table, each child node is a reference to a partition, allowing the user to drop or change the partition.
We want to implement fully functional tables also in the partition list, and optionally not show the partitions in the main table list.

**Comment by kattunga** [comment]
Please, not show the partitions in the main table list.
I have a table with about 200 partitions and my tree becomes unusable.

**Comment by pgaro** [comment]
@kattunga: Idk whether that's an option for you, but my usual approach is to use a different schema for the partitions.

Regards
pgaro

**Comment by kattunga** [comment]
@pgaro. Unfortunately is not an option, the application is in a custom schema (not public schema) and I cant move tables outside this schema.

**Comment by wind39** [comment]
Hi @pgaro , @kattunga ,

Instead of a recursive approach, we implemented categories so partitions are separated from the main tables:

![image](https://user-images.githubusercontent.com/7719686/59305352-79406580-8c70-11e9-9895-fa64bda4ab45.png)

This implementation is going out in 2.16, which will be released in the next few days.

Regards,

William

**Comment by wind39** [comment]
Hi @kattunga , @pgaro ,

Released 2.16.0 today with this implementation. Keeping this open for a few more days to hopefully get your valuable feedback, as always.

Thanks in advance,

William

**Comment by kattunga** [comment]
Works perfect!
Thank you!

**Comment by wind39** [comment]
Thank you for the feedback, much appreciated. Closing this now.
