### ISSUE TITLE
timestamp arrays

### ISSUE THREAD

**Issue by pgaro** [OmniDB/OmniDB#844]
Hello,

`select array_agg(a) from (select now() a) foo`
shows the internal python representation which has nothing to do with the actual data.

All the best
pgaro

**Comment by wind39** [comment]
Hi @pgaro ,

Thanks for reporting this. Now arrays are displayed as PostgreSQL arrays:

![image](https://user-images.githubusercontent.com/7719686/53172780-ed250800-35c4-11e9-88ce-7399033144dd.png)

It also helps when user changes arrays in EditData, as @stevenwinfield [suggested](https://github.com/OmniDB/OmniDB/issues/774#issuecomment-456449181) in #774 .

This fix will be published in next release, 2.15, going out next April.

Regards,
William

**Comment by wind39** [comment]
Hi @pgaro ,

We just released OmniDB 2.15 with this fix. Can you please try it and provide your valuable feedback?

Thanks in advance.

William

**Comment by pgaro** [comment]
Works like a charm! Thank you!
