### ISSUE TITLE
partitioned relation indexes

### ISSUE THREAD

**Issue by pgaro** [OmniDB/OmniDB#845]
If one creates a constraint on the parent table an views and trys to view the ddl of the corresponding index of a corresponding child table (partition) an error is thrown (subselect returned more than one row).

All the best
pgaro

**Comment by pgaro** [comment]
Viewing the child relations work now.
Yet there is a different bug: Indexes that a parent partitioned table has are not shown. Yet the inferred indexes on the child partitions are.

All the best
pgaro

**Comment by wind39** [comment]
Hi @pgaro ,

I managed to simulate this. It happens only for declarative partitioning, for partitioning using inheritance it works fine.

Just to let you know that I'll try to address this before next release, 2.16.

Best regards,

William

**Comment by wind39** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/7719686/59308535-a80e0a00-8c77-11e9-8d85-4e1d15f69904.png)

**Comment by wind39** [comment]
Hi @pgaro ,

Today we released OmniDB 2.16.0 with this fix. Would you please try it out and give us your valuable feedback, as always?

Thank you very much for your support.

Regards,

William

**Comment by pgaro** [comment]
Works at my end. Thank you!

Regards
pgaro
