### ISSUE TITLE
Cannot connect to websocket server with ports 25000 (external) and 25000 (internal). Trying again in 5 seconds...

### ISSUE THREAD

**Issue by dontsu** [OmniDB/OmniDB#861]
RHEL7 OS, no proxy/firewall etc

I have the omnidb running, I can login using default username and password, I could connect to mysql local db server and I can see the available databases, but after some time I get a message saying "Cannot connect to websocket server with ports 25000 (external) and 25000 (internal). Trying again in 5 seconds...". 
<img width="671" alt="screen shot 2019-02-19 at 5 48 24 pm" src="https://user-images.githubusercontent.com/1176297/53038272-344fb380-3474-11e9-99d4-6db1d5fdd8fe.png">

And second issue when I try to view tables of a certain DB, a popup that asks for password for a table:
<img width="832" alt="screen shot 2019-02-19 at 6 30 01 pm" src="https://user-images.githubusercontent.com/1176297/53038332-652fe880-3474-11e9-8e64-e24eb3c57193.png">

Any idea what is wrong with my configuration?

**Comment by wind39** [comment]
Hi @dontsu ,

Thanks for reaching out. What is the OmniDB version? Is it app or server? Also, what is the MySQL version?

Regards,

William

**Comment by dontsu** [comment]
> Hi @dontsu ,
> 
> Thanks for reaching out. What is the OmniDB version? Is it app or server? Also, what is the MySQL version?
> 
> Regards,
> 
> William
Hi @wind39 
It's latest server version of OmniDB (2.13.0), MySQL version is 8.0.15 MySQL Community Server.

**Comment by wind39** [comment]
Hi @dontsu ,

Thanks for the information. We specifically added improved support for MySQL 8.0 in OmniDB version 2.14 we released last week, so the `'table_name'` error should not appear again.

Would you please upgrade to 2.14 and try again?

Regards,

William

**Comment by dontsu** [comment]
> Hi @dontsu ,
> 
> Thanks for the information. We specifically added improved support for MySQL 8.0 in OmniDB version 2.14 we released last week, so the `'table_name'` error should not appear again.
> 
> Would you please upgrade to 2.14 and try again?
> 
> Regards,
> 
> William


@wind39 
thank you for pointing into the right direction. This solved the second issue. What about the first message that I keep getting?

Regards,
Diana

**Comment by wind39** [comment]
Thanks for confirming, Diana @dontsu .

@rafaelthca , can you please take a look at the websocket issue? Thanks in advance.

William

**Comment by rafaelthca** [comment]
hi @dontsu,

I will need to see how OmniDB was deployed in your environment? Are you using it behind Nginx or Apache? I see the interface is trying to connect to port 25000, is that port reachable from the browser?

If you can share all relevant configs (omnidb.conf, nginx or apache configs) and also a screenshot of the browser trying to connect to the websocket, something like:

![image](https://user-images.githubusercontent.com/9335851/53104488-38301400-350e-11e9-82bc-615abca5e951.png)

That interface can accessed in google chrome by using F12 to access developer tools, then go to Network and filter WS requests.

Rafael.

**Comment by PostPollux** [comment]
I guess I have a similar problem...

In my case I try to run OmniDB via docker behind a nginx reverse proxy ([jwilder/nginx-proxy](https://hub.docker.com/r/jwilder/nginx-proxy)). This reverse proxy generates the nginx configs automatically and I get only one "location". I don't find a way to get a configuration like at the bottom of [this docs](https://omnidb.org/en/documentation-en/19-deploying-omnidb-server) where there is a "/wss" location and a "/" location.
Any idea how I could manage to get it work with the jwilder/nginx-proxy and it's ssl companion container?

**Comment by dontsu** [comment]
Hi @rafaelthca 

I don't have any nginx, apache or anything else.
The wss is always penging:

![screen shot 2019-02-21 at 12 29 53 pm](https://user-images.githubusercontent.com/1176297/53169185-755ed980-35d4-11e9-9a82-03ef2f16c9c2.png)

The omnidb.conf is the default one, I didn't change anything in it. 
I am starting the server via:
omnidb-server -p 8080 -w 25000 -H 10.91.176.68

Regards,
Diana

**Comment by rafaelthca** [comment]
@dontsu,

Thanks. Please show the Headers that instead of Frames here:

![image](https://user-images.githubusercontent.com/9335851/53171230-e0061a00-35c0-11e9-9b8b-273070f1c024.png)

I need to see where the browser is trying to connect to, and the status.

**Comment by dontsu** [comment]
![screen shot 2019-02-21 at 1 15 24 pm](https://user-images.githubusercontent.com/1176297/53171499-cb368000-35da-11e9-92e7-493350e712ab.png)

**Comment by rafaelthca** [comment]
Thanks. Let's diagnose this is parts. When starting OmniDB you can provide 2 websocket ports:

```
  -w WSPORT, --wsport=WSPORT
                        websocket port
  -e EWSPORT, --ewsport=EWSPORT
                        external websocket port
```

`-w` is the port the websocket will listen to.

`-e` is the port the browser will connect to. Use this when OmniDB is not accessed directly, but via a reverse proxy, not your case.

You mentioned earlier that you used the following command:

```
omnidb-server -p 8080 -w 25000 -H 10.91.176.68
```

And then your last screenshot shows that the browser tried to connect to 25482, can you confirm that this is happening or are those different tests? Because the port 25482 is the default websocket port in the config file, used if you don't provide `-w` option. If you confirm that this is happening, there may be a bug.

Please refer to my test here:

#TEST 1:

`omnidb-server -w 25000 -H 127.0.0.1`

In this case the browser should try to connect only to port 25000, as `-e` was not specified:

![image](https://user-images.githubusercontent.com/9335851/53173916-67568c00-35c7-11e9-980b-65ef1abfa5e0.png)

#TEST 2:

`omnidb-server -w 25000 -e 25500 -H 127.0.0.1`

Here, the browser tries first 25500 and then 25000:

![image](https://user-images.githubusercontent.com/9335851/53174026-953bd080-35c7-11e9-9c29-62f4b859305d.png)

![image](https://user-images.githubusercontent.com/9335851/53174049-9ff66580-35c7-11e9-899f-ac3f24049fb4.png)

Can you check all the `ws` connection attempts in chrome and check if any of them try to connect to the port specified in `-w`? If yes, then one explanation is that the server hosting omnidb is blocking connections to that specific port, we can check that too.

Rafael.

**Comment by dontsu** [comment]
Dorry for confusion with the ports. I was trying both of them, just in case the one from config file is working, but no :( that is the reason you see two different ports in the screens.

In my case all the connections have the same result.

I was thinking of the fact that the server is blocking the connection and I've tried to alter the etc/services to add the port that I need, but it didn't help.

**Comment by rafaelthca** [comment]
No problem, we want users to be able to use without issues, and possibly identify bugs. Let's isolate the test then. If you try to start with `-w 25000`, does chrome try to connect to 25000 on the ws tab? If so, then OmniDB is ok, and we need to diagnose your network.

Is 10.91.176.68 a remote machine? You can try to use telnet from your location to that machine to see if the port is reachable. From the machine trying to reach omnidb:

```
telnet 10.91.176.68 25000
```

**Comment by dontsu** [comment]
@rafaelthca 
Using 25000, yes, the omnidb sends ws requests with no response.
telnet command returns connection refused. The server is a remote, internal one (not accessible from the outside network).

**Comment by rafaelthca** [comment]
Hm, ok. Let's first check if OmniDB is actually listening on that port. So, being on 10.91.176.68, run:

```
netstat -tulpn
```

OmniDB should appear in that list, on both ports (8080 and 25000).

If the command doesn't exist, you can install it with the package `net-tools`.

**Comment by dontsu** [comment]
![screen shot 2019-02-21 at 2 48 07 pm](https://user-images.githubusercontent.com/1176297/53177354-caf0b180-35e7-11e9-8c25-4aa9d242b1a1.png)

done

**Comment by rafaelthca** [comment]
Great. So I'm inclined to think that there is indeed something blocking port 25000 on that server. Going back to the telnet test, if you try with port 8080 it should work (can you try?), considering that the browser connected to OmniDB.

**Comment by dontsu** [comment]
![screen shot 2019-02-21 at 2 58 31 pm](https://user-images.githubusercontent.com/1176297/53178216-54ed4a00-35e9-11e9-9dc3-8d006c1efae9.png)

**Comment by rafaelthca** [comment]
You could try to start OmniDB avoiding high ports (like 25000), that tend to be blocked. So, for instance, you could try:

```
omnidb-server -p 8080 -w 8081 -H 10.91.176.68
```

**Comment by dontsu** [comment]
oh, it was so simple 

It worked!!!!

Thank you soooooo much :)

Thanks for both @rafaelthca  and @wind39  of you for your input, help and patience!

**Comment by rafaelthca** [comment]
Glad to help! Closing this.
