### ISSUE TITLE
cancel query 'NoneType'

### ISSUE THREAD

**Issue by pgaro** [OmniDB/OmniDB#866]
After canceling a query, I sometimes get 
'NoneType' object has no attribute 'execute'
if the error occurs the tab is "burned", i.e. can't be used unless I reconnect to OmniDB (I'm using the web version).

All the best
pgaro

**Comment by rafaelthca** [comment]
Hi @pgaro,

Thanks for reporting. Very annoying and critical issue. When you say that you need to reconnect to OmniDB, isn't only that query tab that is broken? Doesn't it work if you use a new query tab?

Now, talking about the issue itself, does it occur very often? Do you have a sequence of steps to reproduce it? Are you querying against PG, MySQL, MariaDB or Oracle?

Thanks.

**Comment by pgaro** [comment]
Other (connection) tabs work fine. Do a possible workaround would be to open a new one, copy the content query and close the old one.
I just wanted to point out that the broken part of the tab is connected to something in the session, that is not included in the saved state.

I had this error message with oracle and postgres, while it appears to much be more frequent with oracle. I got to admit that I don't recall whether I canceled the postgres query when the error occurred.

Additional information: I suspect that it's related to the password prompt. What happens when I cancel the query I inserted the password for and then start a new query?

All the best
pgaro

**Comment by francoisoger** [comment]
Hi, a quick message to say that I'm running to a similar issue when I leave a tab inactive for couple of minutes. Then, if I try to execute again the query, I'm facing the same error message.
It appears to be kind of connection timeout, and I can reproduce it with many versions of PG : 9.5, 9.6 and 10.

**Comment by rafaelthca** [comment]
Hi @francoisoger, can you share the exact error message? If possible, also the steps to reproduce. 

I'll try to fix that before the next release, coming out on Thursday.

Thanks.

**Comment by francoisoger** [comment]
Hi @rafaelthca,

so the scenario is :
- run a query (whatever the query is) in a tab
- leave this tab for a couple of minutes (I can't really determine how long do you need to leave the query)
- get back to the query, try to run it
- the query seems to run forever (event a select 1; for example)
- if you cancel the query and try to run again the query, I get the `'NoneType' object has no attribute 'execute'`

**Comment by rafaelthca** [comment]
Thanks for the details.

> P.S. : I'm running OmniDB 2.14 (even if the about tab indicates 2.12) on MacOS 10.4.4

Can you show me a screenshot of this? That's weird, I couldn't find this wrong version issue in the interface.

Can you check OmniDB logs, to see if there are any issues reported there? Logs are in:

`~/.omnidb/omnidb-app/omnidb.log`

I noticed that there is a region in the code that isn't logging properly. If there isn't anything useful in the logs, I would like to package a custom version for you to test if you agree. This custom package will have more verbosity in the logs (something I will include in the next release) and we will be able to identify where the issue is. But that will only work if you can reproduce the error.

**Comment by francoisoger** [comment]
Sure, will be happy to help.

Here is the screenshot of the wrong version number

![Screenshot 2019-04-15 at 15 27 11](https://user-images.githubusercontent.com/17593967/56136840-df23b000-5f93-11e9-912e-52850ddb5650.png)

And with a quick look on the logs, I can't find anything relevant in my opinion.
![Screenshot 2019-04-15 at 15 32 15](https://user-images.githubusercontent.com/17593967/56136895-f498da00-5f93-11e9-9263-25a7252f23d1.png)

this is the extract of the startup process. I tried a grep `error` on the log file but nothing relevant.

I also tried to reproduce the "connection issue" with a tail on the log file. After the inactivity, when I try to run again the query, the log indicates :
```
[04/15/2019 13:57:49] INFO [OmniDB_app.QueryServer:539] *** SQL Command ***
USER: admin,
START: 2019-04-15 13:57:12.279150,
END: 2019-04-15 13:57:49.090926,
DURATION: 00:00:36,
STATUS: error,
COMMAND: select *
from mytable
where id = 1
```
with a `timeout message` in the OmndiDB interface.

Then I try again the query, I got a `SSL SYSCALL error: EOF detected` message in the GUI, and 
```
[04/15/2019 13:59:40] INFO [OmniDB_app.QueryServer:539] *** SQL Command ***
USER: admin,
START: 2019-04-15 13:59:40.455154,
END: 2019-04-15 13:59:40.457218,
DURATION: 2.064 ms,
STATUS: error,
COMMAND: select *
from mytable
where id = 1
```
in the log file.

But in the third try, the query ran again.

I will try to reproduce the issue with relevant logging.

But there is no problem for trying a custom build with increased log verbosity.

**Comment by francoisoger** [comment]
Ok so, the `'NoneType' object has no attribute 'execute'` message occurs only if you try to re run a inactive query tab and cancel it before the timeout. Trying to be clear :
- run a query
- leave the tab inactive for couple of minutes
- try to run again the query
- cancel it before the timeout
- run again the query
=> the message `'NoneType' object has no attribute 'execute'` occurs.

But, unfortunately, no specific issue in the logs :
```
[04/15/2019 14:16:36] INFO [OmniDB_app.QueryServer:539] *** SQL Command ***
USER: admin,
START: 2019-04-15 14:16:18.048119,
END: 2019-04-15 14:16:36.132844,
DURATION: 00:00:18,
STATUS: error,
COMMAND: select 1
```

Sorry for the spam of messages :)

**Comment by rafaelthca** [comment]
Hi,

Here is the custom build:

https://omnidb.org/dist/2.14.0/omnidb-app_2.14.0-test-mac.dmg

After experiencing the issue, you should see a full stack trace in the log file.

**Comment by francoisoger** [comment]
Hi @rafaelthca ,

here is the stack appearing as the error occurs :
```
[04/16/2019 07:58:58] ERROR [OmniDB_app.QueryServer:927] *** Exception ***
Traceback (most recent call last):
  File "OmniDB/ws_core.py", line 796, in thread_query
  File "OmniDB_app/include/Spartacus/Database.py", line 1524, in QueryBlock
AttributeError: 'NoneType' object has no attribute 'execute'

[04/16/2019 07:58:58] INFO [OmniDB_app.QueryServer:539] *** SQL Command ***
USER: admin,
START: 2019-04-16 07:58:58.029099,
END: 2019-04-16 07:58:58.032126,
DURATION: 3.027 ms,
STATUS: error,
COMMAND: select ....
```

**Comment by rafaelthca** [comment]
Thanks @francoisoger, that trace was very helpful.

We could not reproduce the issue, but have an idea of what is going on, we'll attempt to fix for the next release.

**Comment by wind39** [comment]
Hi @pgaro and @francoisoger ,

Thanks to the information you provided, we managed to understand how the issue happens. As far as we understand, the issue is that OmniDB tries to cancel a Postgres backend, but the cancellation hangs. Then the web interface immediately returns to the user, who tries to run a new query while it is not possible, because the backend assigned to that tab is still busy trying to cancel the previous command.

Our approach to fix this is to cancel in background, while a new backend is opened and assigned to the web interface in that query tab.

This fix is going out in 2.15 tomorrow.

Regards,

William

**Comment by wind39** [comment]
Hi @pgaro and @francoisoger ,

OmniDB 2.15 is out. Please try it and provide your valuable feedback, as always.

I'm keeping this open for a few more days.

Best regards,

William

**Comment by francoisoger** [comment]
Hi @wind39,

I've just downloaded and install it, will use it on the two next working days and update the issue.

Thanks for this new release!

**Comment by francoisoger** [comment]
Hi @wind39 ,

just to confirm that I can't reproduce the issue any more.

I think that you can close the issue in my opinion.

**Comment by pgaro** [comment]
Sounds good to me, same thing here.
