### ISSUE TITLE
In Firefox, dragging tabs makes them unusable

### ISSUE THREAD

**Issue by andrey-utkin** [OmniDB/OmniDB#871]
I'm on master (2.14.0) now, but am observing this since 2.11 which i used before.

Dragging an activity tab (like query, console, edit etc), which reorders them in Chrome, makes tab caption to vanish, and makes it impossible to switch to such a broken tab with a click.

**Comment by andrey-utkin** [comment]
This is annoying because drag gesture gets detected sometimes even if you mean just to click on a tab.

**Comment by wind39** [comment]
Hi @andrey-utkin ,

Please assess if this is a duplicate of #636 , which is now closed because we didn't manage to simulate.

Regards,
William

**Comment by wind39** [comment]
Hi @andrey-utkin ,

We finally managed to fix this, the fix will be included in 2.15 to be released tomorrow.

Best regards,

William

**Comment by wind39** [comment]
Hi @andrey-utkin ,

We just released OmniDB 2.15.0 with this fix. Please try and provide your valuable feedback.

Thanks in advance,

William

**Comment by pgaro** [comment]
Works at my end.

Regards
pgaro

**Comment by wind39** [comment]
Thanks for confirming, @pgaro .

Closing this now.
