### ISSUE TITLE
Non-free files in vagrant oracle tests

### ISSUE THREAD

**Issue by df7cb** [OmniDB/OmniDB#892]
Hi,

while browsing the source code to see if everything in there is free software so it could be included into Debian, I noticed that there are oracle-copyrighted files in OmniDB/OmniDB_app/tests/vagrant/oracle-*, for example:

https://github.com/OmniDB/OmniDB/blob/351b598dbefbedbb50a74be752fd050901107e02/OmniDB/OmniDB_app/tests/vagrant/oracle-18cxe/scripts/install.sh#L3-L11

Please replace with a free version, I don't think this is distributable at all.

**Comment by wind39** [comment]
Hi @ChristophBerg ,

Thanks for the heads up, we will handle this and will let you know very soon.

Best regards,

William

**Comment by wind39** [comment]
Hi @ChristophBerg ,

In [this commit](https://github.com/OmniDB/OmniDB/pull/897/commits/8d055653a846a4b1eebb33bc98a0cf5868f9a136) I removed Oracle vagrant machines and wrote an equivalent Dockerfile for our tests.

Please note that before a release, we keep updating dev branch while master branch is frozen. Upon a new release, we throw all changes from the dev branch into the master branch.

Next release, 2.15, is planned for next week, on April 11. So next week you will see these changes in master branch.

Thanks and regards,

William

**Comment by wind39** [comment]
Hi @df7cb ,

This fix reached `master` branch now that we released 2.15.

Closing this now.

Thanks and regards,

William
