### ISSUE TITLE
Using scrypt instead pyscrypt?

### ISSUE THREAD

**Issue by df7cb** [OmniDB/OmniDB#896]
I'm not opening this as a PR because the patch is incomplete (missing requirements.txt etc.), but it seems like the pyscrypt module could just be replaced by scrypt. There are Debian packages for the latter, but not for the former.

In the Debian package, I have now:
```
--- a/OmniDB/OmniDB_app/include/Spartacus/Utils.py
+++ b/OmniDB/OmniDB_app/include/Spartacus/Utils.py
@@ -22,7 +22,7 @@ OUT OF OR IN CONNECTION WITH THE SOFTWAR
 SOFTWARE.
 '''
 
-import pyscrypt
+import scrypt
 import pyaes
 import base64
 import os
@@ -39,14 +39,13 @@ class Cryptor(object):
     def __init__(self, p_key, p_encoding='utf-8'):
         try:
             self.v_encoding = p_encoding
-            self.v_hash = pyscrypt.hash(
+            self.v_hash = scrypt.hash(
                 password = p_key.encode('utf-8'),
                 salt = '0123456789ABCDEF'.encode('utf-8'),
                 N = 1024,
                 r = 1,
-                p = 1,
-                dkLen = 32
-            )
+                p = 1
+            )[:32] # aes wants 32
         except Exception as exc:
             raise Spartacus.Utils.Exception(str(exc))
     def Encrypt(self, p_plaintext):
```

If you could merge that, I would have one patch less. Thanks for considering :)

**Comment by wind39** [comment]
Thanks, @ChristophBerg , I will do some tests and replace `pyscript` with `script`.

**Comment by wind39** [comment]
Hi @ChristophBerg ,

I replaced `pyscrypt` with `scrypt` in [this commit](https://github.com/OmniDB/OmniDB/pull/897/commits/8d055653a846a4b1eebb33bc98a0cf5868f9a136).

As I explained in #892 , these changes will make to the master branch only next week, when we will release 2.15.

Best regards,

William

**Comment by wind39** [comment]
Hi @df7cb ,

This implementation had to be changed due to some issues to install `scrypt` on Mac and Windows.

Now the code tries to import `scrypt` and, if not found, then imports `pyscrypt`. This covers our deployment and I hope it covers your needs too.

Keeping this open for a few more days so you can check.

Thanks,

William

**Comment by df7cb** [comment]
I'm currently on vacation and can't check now, but it should indeed fix the problem. Thanks!
