### ISSUE TITLE
Error encountered on OmniDB 2.13 or 2.14 WARNING [django.security.csrf:228] Forbidden (CSRF token missing or incorrect.): /check_session_message/ on alpine 3.9

### ISSUE THREAD

**Issue by thomasboussekey** [OmniDB/OmniDB#902]
Hello,

I'm working on a alpine container of omnidb.
It is working fine on Alpine 3.9 with OmniDB 2.13.
And I encounter errors like
```
[04/04/2019 20:56:35] WARNING [django.security.csrf:228] Forbidden (CSRF token missing or incorrect.): /check_session_message/
```
On OmniDB 2.13 or 2.14.

Here is my Dockerfile:
https://github.com/thomasboussekey/docker-omnidb/blob/Create_OmniDb214_on_Apline39/Dockerfile

Can you tell me what is incorrect in my configuration?

Thanks in advance,
Have a nice day,
Regards,
Thomas

**Comment by rafaelthca** [comment]
Hi Thomas,

Thanks for reaching out. Can you provide more details on your test? After starting your container, how are you trying to access OmniDB?

As I can see, that dockerfile starts OmniDB from source, not the compiled one. I'll reserve some time to test it.

**Comment by thomasboussekey** [comment]
Hello @rafaelthca ,

Many thanks for your quuck feedback!

My Dockerfile is using source, you're correct! I don't know package location for alpine, maybe I can use debian's ?? I'm not a linux expert!

The container `build` & `run` operation are **running correctly**.
I **encounter the error** when I try to `reach the login page` into my web browser. I get the error message into the shell window running the docker run command.

Here are my docker commands:

```sh
sudo docker build --tag omnidb214 --no-cache .
sudo docker run -it -p 127.0.0.1:8080:8080 -p 127.0.0.1:25482:25482 omnidb214 bash
```

Hope this helps,
Have a nice day,
Thomas

**Comment by thomasboussekey** [comment]
Hello,

I re-checked, and didn't face the issue again.
I wonder if the problem was not linked to cache settings or environment variables, because I didn't purge cache or use incognito mode between 2.12 and newer version tests!

I close the issue.
Sorry for the inconvenience,
Have a nice week,
Regards,
Thomas
