### ISSUE TITLE
Super user not able to login after creating regular users

### ISSUE THREAD

**Issue by diogojesus95** [OmniDB/OmniDB#908]
Hello,
after creating few users, I cannot login in back into admin account. The same error occurs when I try to login to any other super user account. Now, only the accounts which don't have super user are allowed to login. The error says: Invalid username or password.

---
EDIT
---

In the meantime, is there anyway to reset the admin password? As I didn't want to install everything again (setting up database connections all over again)

**Comment by rafaelthca** [comment]
hi @diogojesus95,

Did you change the password of the users who are not able to login anymore? If yes, did you change the passwords using the users grid or using the following interface:

![image](https://user-images.githubusercontent.com/9335851/55740374-55a73780-5a01-11e9-902e-fa9795e7f5f2.png)

**Comment by diogojesus95** [comment]
Hello, yes passwords were changed. Admin account was changed using that interface, the other super admin was with the user grid

**Comment by wind39** [comment]
Hi @diogojesus95 ,

We just released OmniDB 2.15 with a fix for this issue. Please try it and provide feedback if possible, it would be very important to us.

Thanks and regards,

William

**Comment by diogojesus95** [comment]
Hello, hadn't time yet for the implementation we're quite busy with other projects, hopefully next week I get enough time to retake this project. Thank you

**Comment by diogojesus95** [comment]
So far so good, this issue seems to be fixed, recreated the whole server created all the users while editing the admin password aswell and everything works as expected. Thank you

**Comment by wind39** [comment]
Thanks for your feedback, @diogojesus95 . Closing this issue now.
