### ISSUE TITLE
Windows 10 PostgreSQL 10 Connection via SSH

### ISSUE THREAD

**Issue by FriarMonk** [OmniDB/OmniDB#931]
I have read through issue #317 numerous times trying to figure out what I am missing and I am unable to... Here are the basics:

I am running on Windows 10 with OmniDB 2.15.0...  Here is my connection in OmniDB:

![image](https://user-images.githubusercontent.com/50025986/56822493-d7c39880-6816-11e9-898f-9eb633bc4885.png)

That does not work... I continually get a password dialog, which always fails. 

NOTE: If I create a tunnel outside... I.E:

alias tnlbi='ssh -N -L 5433:server:5432 me@server

Then run it in back ground:

tnlbi &

Then I can create a local connection that connects:

![image](https://user-images.githubusercontent.com/50025986/56822426-a1861900-6816-11e9-9c5c-7d2d89a81150.png)

So while this is a work around... I would really like to be able to bypass this requirement and understand what happened.

**Comment by wind39** [comment]
Hi @FriarMonk ,

You need to paste the contents of your private key in that field and not the path to the file.

Please try this way and let us know if it will work.

Best regards,

William

**Comment by FriarMonk** [comment]
Perfect… that is the piece I was missing… Thank you!

**Comment by wind39** [comment]
Hi @FriarMonk ,

Thanks for confirming it helped. Closing this case now.

Best regards,

William
