### ISSUE TITLE
Omnidb CPU usage on RDS

### ISSUE THREAD

**Issue by dcarpioCC** [OmniDB/OmniDB#935]
I'm using RDS with postgres10.6 I tried to configure the CPU usage on omnidb but I had this error: 

must be superuser to COPY to or from an external program
HINT:  Anyone can COPY to stdout or from stdin. psql's \copy command also works for anyone.

Please If someone can help me I will appreciate.  Thanks

**Comment by wind39** [comment]
Hi @dcarpioCC ,

Despite the fact that in RDS the concept of superuser is different from regular Postgres (you can't really connect as a real postgres superuser in RDS), you also won't be able to execute any Linux commands in RDS (and the CPU usage chart needs to execute Linux commands to get CPU usage information).

So I'm afraid you won't be able to use the CPU usage chart from Monitoring Dashboard.

Regards,

William

**Comment by wind39** [comment]
Closing this now.
