### ISSUE TITLE
Drag width of target set display

### ISSUE THREAD

**Issue by pgaro** [OmniDB/OmniDB#940]
The width of the target set display can only be changed when one is on the top of the return set of the corresponding query, i.e. after scrolling down the width can't be changed via dragging.

Regards
pgaro

**Comment by rafaelthca** [comment]
Fixed.

**Comment by wind39** [comment]
Hi @pgaro ,

This is fixed in 2.16.0. I would appreciate your confirmation on this one.

Thanks in advance,

William

**Comment by pgaro** [comment]
Thanks, works like a charm!

Regards
pgaro
