### ISSUE TITLE
SAML or LDAP integration for user authentication

### ISSUE THREAD

**Issue by svash3001** [OmniDB/OmniDB#98]
I was trying to locate this feature in the documentation but did not see it.

If this is to be a good web based tool then a strong user authentication via SAML or LDAP as a capability would be really great to have as part of this product.

**Comment by gamato** [comment]
Absolutely!  The other day I was setting up a new Graphite installation and connecting it to a local LDAP was very simple.  No need to manually maintain a separate user database when LDAP is readily available in most environments these days.  Thanks in advance!

**Comment by wind39** [comment]
Hi @svash3001 , @gamato ,

Thanks for your suggestion. LDAP support is on our roadmap, to be implemented and released soon.

**Comment by eXeDK** [comment]
Any news on this @wind39? Together with some audit logging for the users would be absolutely awesome!

**Comment by skotu-vida** [comment]
hey guys, was wondering if there is any update on this enhancement?

**Comment by wind39** [comment]
Hi @skotu-vida ,

We have been investigating this. Due to the number of requests from users we have increased priority of this ticket. I will let you know via this ticket.

Regards,

William

**Comment by lfavero** [comment]
Hi all,
have you news about Ldap integration ? 
Thanks 
Luigi Favero

**Comment by schmidax** [comment]
Hi all,
is there anything new about the ldap topic?
I need it urgently.

**Comment by denisgigli** [comment]
Good day folks!

Any updates, or plans for this feature?

thought it was on the roadmap.

**Comment by barthisrael** [comment]
Hello everyone,

OmniDB 3.0 beta was released and it includes LDAP authentication. We invite you to test it. More info about how to setup it can be found [here](https://omnidb.readthedocs.io/en/latest/en/03_omnidb-server_usability.html#authentication-methods)

Regards.

**Comment by leim** [comment]
Hey guys,

i am wondering if there is any updates about auditing user operations?

**Comment by Moulick** [comment]
@wind39 @barthisrael  possibility to add SAML or OIDC ?
